// Auto-generated by OpenLane
module async_fifo(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input wr_clk,
  input rd_clk,
  input arst_n,
  input wr_en,
  input[7:0] wr_data,
  input rd_en,
  output[7:0] rd_data,
  input[4:0] afull_threshold,
  input[4:0] aempty_threshold,
  output full,
  output empty,
  output afull,
  output aempty
);
endmodule
