/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module async_fifo(wr_clk, rd_clk, arst_n, wr_en, wr_data, rd_en, rd_data, afull_threshold, aempty_threshold, full, empty, afull, aempty);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  output aempty;
  wire aempty;
  wire aempty_next;
  input [4:0] aempty_threshold;
  wire [4:0] aempty_threshold;
  output afull;
  wire afull;
  wire afull_next;
  input [4:0] afull_threshold;
  wire [4:0] afull_threshold;
  input arst_n;
  wire arst_n;
  output empty;
  wire empty;
  wire empty_next;
  output full;
  wire full;
  wire \full_compare[0] ;
  wire \full_compare[1] ;
  wire \full_compare[2] ;
  wire full_next;
  wire \mem[0][0] ;
  wire \mem[0][1] ;
  wire \mem[0][2] ;
  wire \mem[0][3] ;
  wire \mem[0][4] ;
  wire \mem[0][5] ;
  wire \mem[0][6] ;
  wire \mem[0][7] ;
  wire \mem[10][0] ;
  wire \mem[10][1] ;
  wire \mem[10][2] ;
  wire \mem[10][3] ;
  wire \mem[10][4] ;
  wire \mem[10][5] ;
  wire \mem[10][6] ;
  wire \mem[10][7] ;
  wire \mem[11][0] ;
  wire \mem[11][1] ;
  wire \mem[11][2] ;
  wire \mem[11][3] ;
  wire \mem[11][4] ;
  wire \mem[11][5] ;
  wire \mem[11][6] ;
  wire \mem[11][7] ;
  wire \mem[12][0] ;
  wire \mem[12][1] ;
  wire \mem[12][2] ;
  wire \mem[12][3] ;
  wire \mem[12][4] ;
  wire \mem[12][5] ;
  wire \mem[12][6] ;
  wire \mem[12][7] ;
  wire \mem[13][0] ;
  wire \mem[13][1] ;
  wire \mem[13][2] ;
  wire \mem[13][3] ;
  wire \mem[13][4] ;
  wire \mem[13][5] ;
  wire \mem[13][6] ;
  wire \mem[13][7] ;
  wire \mem[14][0] ;
  wire \mem[14][1] ;
  wire \mem[14][2] ;
  wire \mem[14][3] ;
  wire \mem[14][4] ;
  wire \mem[14][5] ;
  wire \mem[14][6] ;
  wire \mem[14][7] ;
  wire \mem[15][0] ;
  wire \mem[15][1] ;
  wire \mem[15][2] ;
  wire \mem[15][3] ;
  wire \mem[15][4] ;
  wire \mem[15][5] ;
  wire \mem[15][6] ;
  wire \mem[15][7] ;
  wire \mem[1][0] ;
  wire \mem[1][1] ;
  wire \mem[1][2] ;
  wire \mem[1][3] ;
  wire \mem[1][4] ;
  wire \mem[1][5] ;
  wire \mem[1][6] ;
  wire \mem[1][7] ;
  wire \mem[2][0] ;
  wire \mem[2][1] ;
  wire \mem[2][2] ;
  wire \mem[2][3] ;
  wire \mem[2][4] ;
  wire \mem[2][5] ;
  wire \mem[2][6] ;
  wire \mem[2][7] ;
  wire \mem[3][0] ;
  wire \mem[3][1] ;
  wire \mem[3][2] ;
  wire \mem[3][3] ;
  wire \mem[3][4] ;
  wire \mem[3][5] ;
  wire \mem[3][6] ;
  wire \mem[3][7] ;
  wire \mem[4][0] ;
  wire \mem[4][1] ;
  wire \mem[4][2] ;
  wire \mem[4][3] ;
  wire \mem[4][4] ;
  wire \mem[4][5] ;
  wire \mem[4][6] ;
  wire \mem[4][7] ;
  wire \mem[5][0] ;
  wire \mem[5][1] ;
  wire \mem[5][2] ;
  wire \mem[5][3] ;
  wire \mem[5][4] ;
  wire \mem[5][5] ;
  wire \mem[5][6] ;
  wire \mem[5][7] ;
  wire \mem[6][0] ;
  wire \mem[6][1] ;
  wire \mem[6][2] ;
  wire \mem[6][3] ;
  wire \mem[6][4] ;
  wire \mem[6][5] ;
  wire \mem[6][6] ;
  wire \mem[6][7] ;
  wire \mem[7][0] ;
  wire \mem[7][1] ;
  wire \mem[7][2] ;
  wire \mem[7][3] ;
  wire \mem[7][4] ;
  wire \mem[7][5] ;
  wire \mem[7][6] ;
  wire \mem[7][7] ;
  wire \mem[8][0] ;
  wire \mem[8][1] ;
  wire \mem[8][2] ;
  wire \mem[8][3] ;
  wire \mem[8][4] ;
  wire \mem[8][5] ;
  wire \mem[8][6] ;
  wire \mem[8][7] ;
  wire \mem[9][0] ;
  wire \mem[9][1] ;
  wire \mem[9][2] ;
  wire \mem[9][3] ;
  wire \mem[9][4] ;
  wire \mem[9][5] ;
  wire \mem[9][6] ;
  wire \mem[9][7] ;
  wire \rd_bin[0] ;
  wire \rd_bin[1] ;
  wire \rd_bin[2] ;
  wire \rd_bin[3] ;
  wire \rd_bin[4] ;
  wire \rd_bin_next[0] ;
  wire \rd_bin_next[1] ;
  wire \rd_bin_next[2] ;
  wire \rd_bin_next[3] ;
  wire \rd_bin_next[4] ;
  wire \rd_bin_sync[4] ;
  input rd_clk;
  wire rd_clk;
  output [7:0] rd_data;
  wire [7:0] rd_data;
  input rd_en;
  wire rd_en;
  wire \rd_gray[0] ;
  wire \rd_gray[1] ;
  wire \rd_gray[2] ;
  wire \rd_gray[3] ;
  wire \rd_gray_next[0] ;
  wire \rd_gray_next[1] ;
  wire \rd_gray_next[2] ;
  wire \rd_gray_next[3] ;
  wire \rd_gray_sync1[0] ;
  wire \rd_gray_sync1[1] ;
  wire \rd_gray_sync1[2] ;
  wire \rd_gray_sync1[3] ;
  wire \rd_gray_sync1[4] ;
  wire \rd_gray_sync2[3] ;
  wire \wr_bin[0] ;
  wire \wr_bin[1] ;
  wire \wr_bin[2] ;
  wire \wr_bin[3] ;
  wire \wr_bin[4] ;
  wire \wr_bin_next[0] ;
  wire \wr_bin_next[1] ;
  wire \wr_bin_next[2] ;
  wire \wr_bin_next[3] ;
  wire \wr_bin_next[4] ;
  wire \wr_bin_sync[4] ;
  input wr_clk;
  wire wr_clk;
  input [7:0] wr_data;
  wire [7:0] wr_data;
  input wr_en;
  wire wr_en;
  wire \wr_gray[0] ;
  wire \wr_gray[1] ;
  wire \wr_gray[2] ;
  wire \wr_gray[3] ;
  wire \wr_gray_next[0] ;
  wire \wr_gray_next[1] ;
  wire \wr_gray_next[2] ;
  wire \wr_gray_next[3] ;
  wire \wr_gray_sync1[0] ;
  wire \wr_gray_sync1[1] ;
  wire \wr_gray_sync1[2] ;
  wire \wr_gray_sync1[3] ;
  wire \wr_gray_sync1[4] ;
  wire \wr_gray_sync2[0] ;
  wire \wr_gray_sync2[1] ;
  wire \wr_gray_sync2[2] ;
  wire \wr_gray_sync2[3] ;
  sky130_fd_sc_hd__inv_2 _352_ (
    .A(\full_compare[2] ),
    .Y(_136_)
  );
  sky130_fd_sc_hd__inv_2 _353_ (
    .A(\wr_bin[2] ),
    .Y(_137_)
  );
  sky130_fd_sc_hd__inv_2 _354_ (
    .A(\full_compare[1] ),
    .Y(_138_)
  );
  sky130_fd_sc_hd__inv_2 _355_ (
    .A(\full_compare[0] ),
    .Y(_139_)
  );
  sky130_fd_sc_hd__inv_2 _356_ (
    .A(afull_threshold[3]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__inv_2 _357_ (
    .A(afull_threshold[1]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__inv_2 _358_ (
    .A(\wr_gray_sync2[1] ),
    .Y(_142_)
  );
  sky130_fd_sc_hd__inv_2 _359_ (
    .A(\rd_bin[3] ),
    .Y(_143_)
  );
  sky130_fd_sc_hd__inv_2 _360_ (
    .A(\rd_bin[2] ),
    .Y(_144_)
  );
  sky130_fd_sc_hd__inv_2 _361_ (
    .A(aempty_threshold[2]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__inv_2 _362_ (
    .A(aempty_threshold[4]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__inv_2 _363_ (
    .A(full),
    .Y(_147_)
  );
  sky130_fd_sc_hd__and2_2 _364_ (
    .A(\rd_bin_sync[4] ),
    .B(\rd_gray_sync2[3] ),
    .X(_148_)
  );
  sky130_fd_sc_hd__nand2b_2 _365_ (
    .A_N(\rd_gray_sync2[3] ),
    .B(\rd_bin_sync[4] ),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2b_2 _366_ (
    .A_N(\rd_bin_sync[4] ),
    .B(\rd_gray_sync2[3] ),
    .Y(_150_)
  );
  sky130_fd_sc_hd__and3_2 _367_ (
    .A(_149_),
    .B(_150_),
    .C(\wr_bin[3] ),
    .X(_151_)
  );
  sky130_fd_sc_hd__nand3_2 _368_ (
    .A(_149_),
    .B(_150_),
    .C(\full_compare[2] ),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o21ai_2 _369_ (
    .A1(\rd_bin_sync[4] ),
    .A2(\rd_gray_sync2[3] ),
    .B1(_136_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand3_2 _370_ (
    .A(_136_),
    .B(_149_),
    .C(_150_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__o21ai_2 _371_ (
    .A1(\rd_bin_sync[4] ),
    .A2(\rd_gray_sync2[3] ),
    .B1(\full_compare[2] ),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o211ai_2 _372_ (
    .A1(_148_),
    .A2(_153_),
    .B1(\wr_bin[2] ),
    .C1(_152_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o211ai_2 _373_ (
    .A1(_155_),
    .A2(_148_),
    .B1(_137_),
    .C1(_154_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__and2_2 _374_ (
    .A(_156_),
    .B(_157_),
    .X(_158_)
  );
  sky130_fd_sc_hd__o211ai_2 _375_ (
    .A1(_148_),
    .A2(_155_),
    .B1(\full_compare[1] ),
    .C1(_154_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__o211ai_2 _376_ (
    .A1(_153_),
    .A2(_148_),
    .B1(_138_),
    .C1(_152_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__o211ai_2 _377_ (
    .A1(_148_),
    .A2(_153_),
    .B1(\full_compare[1] ),
    .C1(_152_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o211ai_2 _378_ (
    .A1(_155_),
    .A2(_148_),
    .B1(_138_),
    .C1(_154_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand3b_2 _379_ (
    .A_N(\wr_bin[1] ),
    .B(_159_),
    .C(_160_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nand3_2 _380_ (
    .A(_161_),
    .B(_162_),
    .C(\wr_bin[1] ),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand3_2 _381_ (
    .A(_159_),
    .B(_160_),
    .C(\full_compare[0] ),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand3_2 _382_ (
    .A(_139_),
    .B(_161_),
    .C(_162_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a31oi_2 _383_ (
    .A1(_139_),
    .A2(_161_),
    .A3(_162_),
    .B1(\wr_bin[0] ),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nand3b_2 _384_ (
    .A_N(\wr_bin[0] ),
    .B(_165_),
    .C(_166_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand4b_2 _385_ (
    .A_N(\wr_bin[0] ),
    .B(_164_),
    .C(_165_),
    .D(_166_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nand3_2 _386_ (
    .A(_169_),
    .B(_158_),
    .C(_163_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__and3b_2 _387_ (
    .A_N(\wr_bin[3] ),
    .B(_149_),
    .C(_150_),
    .X(_171_)
  );
  sky130_fd_sc_hd__a21boi_2 _388_ (
    .A1(_149_),
    .A2(_150_),
    .B1_N(\wr_bin[3] ),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nor2_2 _389_ (
    .A(_171_),
    .B(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a21oi_2 _390_ (
    .A1(_156_),
    .A2(_170_),
    .B1(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__o2bb2ai_2 _391_ (
    .A1_N(_156_),
    .A2_N(_170_),
    .B1(_171_),
    .B2(_172_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__xor2_2 _392_ (
    .A(\wr_bin[4] ),
    .B(\rd_bin_sync[4] ),
    .X(_176_)
  );
  sky130_fd_sc_hd__inv_2 _393_ (
    .A(_176_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nand3b_2 _394_ (
    .A_N(_151_),
    .B(_175_),
    .C(_177_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__o21ai_2 _395_ (
    .A1(_151_),
    .A2(_174_),
    .B1(_176_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__and2_2 _396_ (
    .A(_178_),
    .B(_179_),
    .X(_180_)
  );
  sky130_fd_sc_hd__nand3_2 _397_ (
    .A(_179_),
    .B(afull_threshold[4]),
    .C(_178_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nand3_2 _398_ (
    .A(_156_),
    .B(_170_),
    .C(_173_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__and2_2 _399_ (
    .A(_175_),
    .B(_182_),
    .X(_183_)
  );
  sky130_fd_sc_hd__nand2_2 _400_ (
    .A(_175_),
    .B(_182_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__a22o_2 _401_ (
    .A1(_156_),
    .A2(_157_),
    .B1(_163_),
    .B2(_169_),
    .X(_185_)
  );
  sky130_fd_sc_hd__a21boi_2 _402_ (
    .A1(_170_),
    .A2(_185_),
    .B1_N(afull_threshold[2]),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a31oi_2 _403_ (
    .A1(_169_),
    .A2(_158_),
    .A3(_163_),
    .B1(afull_threshold[2]),
    .Y(_187_)
  );
  sky130_fd_sc_hd__and2_2 _404_ (
    .A(_163_),
    .B(_164_),
    .X(_188_)
  );
  sky130_fd_sc_hd__nand2_2 _405_ (
    .A(_163_),
    .B(_164_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__a21oi_2 _406_ (
    .A1(_167_),
    .A2(_165_),
    .B1(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__a21oi_2 _407_ (
    .A1(_163_),
    .A2(_164_),
    .B1(_168_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__o21bai_2 _408_ (
    .A1(_190_),
    .A2(_191_),
    .B1_N(_141_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__a21bo_2 _409_ (
    .A1(_165_),
    .A2(_166_),
    .B1_N(\wr_bin[0] ),
    .X(_193_)
  );
  sky130_fd_sc_hd__o2111ai_2 _410_ (
    .A1(afull_threshold[1]),
    .A2(_188_),
    .B1(_193_),
    .C1(afull_threshold[0]),
    .D1(_168_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__a22oi_2 _411_ (
    .A1(_185_),
    .A2(_187_),
    .B1(_192_),
    .B2(_194_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__o22ai_2 _412_ (
    .A1(afull_threshold[3]),
    .A2(_184_),
    .B1(_186_),
    .B2(_195_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__o211ai_2 _413_ (
    .A1(_183_),
    .A2(_140_),
    .B1(_181_),
    .C1(_196_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__o21ai_2 _414_ (
    .A1(afull_threshold[4]),
    .A2(_180_),
    .B1(_197_),
    .Y(afull_next)
  );
  sky130_fd_sc_hd__xor2_2 _415_ (
    .A(\wr_bin_sync[4] ),
    .B(\rd_bin[4] ),
    .X(_198_)
  );
  sky130_fd_sc_hd__nand2b_2 _416_ (
    .A_N(\wr_bin_sync[4] ),
    .B(\wr_gray_sync2[3] ),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nand2b_2 _417_ (
    .A_N(\wr_gray_sync2[3] ),
    .B(\wr_bin_sync[4] ),
    .Y(_200_)
  );
  sky130_fd_sc_hd__and2_2 _418_ (
    .A(\wr_gray_sync2[3] ),
    .B(\wr_bin_sync[4] ),
    .X(_201_)
  );
  sky130_fd_sc_hd__nand2_2 _419_ (
    .A(\wr_gray_sync2[3] ),
    .B(\wr_bin_sync[4] ),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nor2_2 _420_ (
    .A(\wr_gray_sync2[3] ),
    .B(\wr_bin_sync[4] ),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nand2_2 _421_ (
    .A(_199_),
    .B(_200_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__or3_2 _422_ (
    .A(\rd_bin[3] ),
    .B(_201_),
    .C(_203_),
    .X(_205_)
  );
  sky130_fd_sc_hd__o21ai_2 _423_ (
    .A1(_201_),
    .A2(_203_),
    .B1(\rd_bin[3] ),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o21a_2 _424_ (
    .A1(\wr_gray_sync2[3] ),
    .A2(\wr_bin_sync[4] ),
    .B1(\wr_gray_sync2[2] ),
    .X(_207_)
  );
  sky130_fd_sc_hd__nand2_2 _425_ (
    .A(_207_),
    .B(_202_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nand3b_2 _426_ (
    .A_N(\wr_gray_sync2[2] ),
    .B(_199_),
    .C(_200_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand3_2 _427_ (
    .A(_199_),
    .B(_200_),
    .C(\wr_gray_sync2[2] ),
    .Y(_210_)
  );
  sky130_fd_sc_hd__o21bai_2 _428_ (
    .A1(\wr_gray_sync2[3] ),
    .A2(\wr_bin_sync[4] ),
    .B1_N(\wr_gray_sync2[2] ),
    .Y(_211_)
  );
  sky130_fd_sc_hd__o21ai_2 _429_ (
    .A1(_201_),
    .A2(_211_),
    .B1(_210_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__o211a_2 _430_ (
    .A1(_201_),
    .A2(_211_),
    .B1(\rd_bin[2] ),
    .C1(_210_),
    .X(_213_)
  );
  sky130_fd_sc_hd__and3_2 _431_ (
    .A(_144_),
    .B(_208_),
    .C(_209_),
    .X(_214_)
  );
  sky130_fd_sc_hd__nand2_2 _432_ (
    .A(_212_),
    .B(_144_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__o211ai_2 _433_ (
    .A1(_201_),
    .A2(_211_),
    .B1(\wr_gray_sync2[1] ),
    .C1(_210_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nand3_2 _434_ (
    .A(_142_),
    .B(_208_),
    .C(_209_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__o211ai_2 _435_ (
    .A1(_211_),
    .A2(_201_),
    .B1(_142_),
    .C1(_210_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nand3_2 _436_ (
    .A(_209_),
    .B(\wr_gray_sync2[1] ),
    .C(_208_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nand3_2 _437_ (
    .A(_217_),
    .B(\rd_bin[1] ),
    .C(_216_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nand3b_2 _438_ (
    .A_N(\rd_bin[1] ),
    .B(_218_),
    .C(_219_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand3_2 _439_ (
    .A(_217_),
    .B(\wr_gray_sync2[0] ),
    .C(_216_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nand3b_2 _440_ (
    .A_N(\wr_gray_sync2[0] ),
    .B(_218_),
    .C(_219_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__and3_2 _441_ (
    .A(_222_),
    .B(_223_),
    .C(\rd_bin[0] ),
    .X(_224_)
  );
  sky130_fd_sc_hd__nand3_2 _442_ (
    .A(_222_),
    .B(_223_),
    .C(\rd_bin[0] ),
    .Y(_225_)
  );
  sky130_fd_sc_hd__nand4_2 _443_ (
    .A(_221_),
    .B(_222_),
    .C(_223_),
    .D(\rd_bin[0] ),
    .Y(_226_)
  );
  sky130_fd_sc_hd__o211ai_2 _444_ (
    .A1(_144_),
    .A2(_212_),
    .B1(_220_),
    .C1(_226_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__o2bb2ai_2 _445_ (
    .A1_N(_215_),
    .A2_N(_227_),
    .B1(_143_),
    .B2(_204_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nand3b_2 _446_ (
    .A_N(_198_),
    .B(_205_),
    .C(_228_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nand3_2 _447_ (
    .A(_205_),
    .B(_215_),
    .C(_227_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__o211ai_2 _448_ (
    .A1(_143_),
    .A2(_204_),
    .B1(_198_),
    .C1(_230_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nand2_2 _449_ (
    .A(_229_),
    .B(_231_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nand2_2 _450_ (
    .A(_205_),
    .B(_206_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__nand2_2 _451_ (
    .A(_227_),
    .B(_233_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__a21o_2 _452_ (
    .A1(_215_),
    .A2(_227_),
    .B1(_233_),
    .X(_235_)
  );
  sky130_fd_sc_hd__o21ai_2 _453_ (
    .A1(_214_),
    .A2(_234_),
    .B1(_235_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__or2_2 _454_ (
    .A(_213_),
    .B(_214_),
    .X(_237_)
  );
  sky130_fd_sc_hd__a21oi_2 _455_ (
    .A1(_220_),
    .A2(_226_),
    .B1(_237_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__o211a_2 _456_ (
    .A1(_213_),
    .A2(_214_),
    .B1(_220_),
    .C1(_226_),
    .X(_239_)
  );
  sky130_fd_sc_hd__nor2_2 _457_ (
    .A(_238_),
    .B(_239_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__nand2_2 _458_ (
    .A(_220_),
    .B(_221_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__nand4_2 _459_ (
    .A(_222_),
    .B(_223_),
    .C(_241_),
    .D(\rd_bin[0] ),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nand3_2 _460_ (
    .A(_220_),
    .B(_221_),
    .C(_225_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nand2_2 _461_ (
    .A(_242_),
    .B(_243_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__a21oi_2 _462_ (
    .A1(_222_),
    .A2(_223_),
    .B1(\rd_bin[0] ),
    .Y(_245_)
  );
  sky130_fd_sc_hd__o21bai_2 _463_ (
    .A1(_224_),
    .A2(_245_),
    .B1_N(aempty_threshold[0]),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nand2_2 _464_ (
    .A(_244_),
    .B(aempty_threshold[1]),
    .Y(_247_)
  );
  sky130_fd_sc_hd__o21ai_2 _465_ (
    .A1(aempty_threshold[1]),
    .A2(_244_),
    .B1(_246_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__o311ai_2 _466_ (
    .A1(_145_),
    .A2(_238_),
    .A3(_239_),
    .B1(_247_),
    .C1(_248_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__o221ai_2 _467_ (
    .A1(aempty_threshold[2]),
    .A2(_240_),
    .B1(aempty_threshold[3]),
    .B2(_236_),
    .C1(_249_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__a32oi_2 _468_ (
    .A1(_229_),
    .A2(_231_),
    .A3(aempty_threshold[4]),
    .B1(_236_),
    .B2(aempty_threshold[3]),
    .Y(_251_)
  );
  sky130_fd_sc_hd__a22oi_2 _469_ (
    .A1(_146_),
    .A2(_232_),
    .B1(_251_),
    .B2(_250_),
    .Y(aempty_next)
  );
  sky130_fd_sc_hd__a21oi_2 _470_ (
    .A1(_147_),
    .A2(wr_en),
    .B1(\wr_bin[0] ),
    .Y(_252_)
  );
  sky130_fd_sc_hd__and3_2 _471_ (
    .A(_147_),
    .B(wr_en),
    .C(\wr_bin[0] ),
    .X(_253_)
  );
  sky130_fd_sc_hd__nor2_2 _472_ (
    .A(_252_),
    .B(_253_),
    .Y(\wr_bin_next[0] )
  );
  sky130_fd_sc_hd__nor2_2 _473_ (
    .A(\wr_bin[1] ),
    .B(_253_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__and4_2 _474_ (
    .A(_147_),
    .B(wr_en),
    .C(\wr_bin[0] ),
    .D(\wr_bin[1] ),
    .X(_255_)
  );
  sky130_fd_sc_hd__nor2_2 _475_ (
    .A(_254_),
    .B(_255_),
    .Y(\wr_bin_next[1] )
  );
  sky130_fd_sc_hd__a21oi_2 _476_ (
    .A1(\wr_bin[1] ),
    .A2(_253_),
    .B1(\wr_bin[2] ),
    .Y(_256_)
  );
  sky130_fd_sc_hd__and3_2 _477_ (
    .A(\wr_bin[2] ),
    .B(\wr_bin[1] ),
    .C(_253_),
    .X(_257_)
  );
  sky130_fd_sc_hd__nor2_2 _478_ (
    .A(_256_),
    .B(_257_),
    .Y(\wr_bin_next[2] )
  );
  sky130_fd_sc_hd__a311oi_2 _479_ (
    .A1(\wr_bin[2] ),
    .A2(\wr_bin[1] ),
    .A3(_253_),
    .B1(\wr_bin[3] ),
    .C1(\wr_bin[4] ),
    .Y(_258_)
  );
  sky130_fd_sc_hd__o21a_2 _480_ (
    .A1(\wr_bin[3] ),
    .A2(_257_),
    .B1(\wr_bin[4] ),
    .X(_259_)
  );
  sky130_fd_sc_hd__nor2_2 _481_ (
    .A(_258_),
    .B(_259_),
    .Y(\wr_gray_next[3] )
  );
  sky130_fd_sc_hd__xor2_2 _482_ (
    .A(\rd_gray_sync2[3] ),
    .B(\wr_gray_next[3] ),
    .X(_260_)
  );
  sky130_fd_sc_hd__xor2_2 _483_ (
    .A(\wr_bin[3] ),
    .B(_256_),
    .X(_261_)
  );
  sky130_fd_sc_hd__inv_2 _484_ (
    .A(_261_),
    .Y(\wr_gray_next[2] )
  );
  sky130_fd_sc_hd__xor2_2 _485_ (
    .A(_137_),
    .B(_254_),
    .X(\wr_gray_next[1] )
  );
  sky130_fd_sc_hd__xnor2_2 _486_ (
    .A(\wr_bin[1] ),
    .B(_252_),
    .Y(\wr_gray_next[0] )
  );
  sky130_fd_sc_hd__xor2_2 _487_ (
    .A(_139_),
    .B(\wr_gray_next[0] ),
    .X(_262_)
  );
  sky130_fd_sc_hd__and3_2 _488_ (
    .A(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .C(_255_),
    .X(_263_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _489_ (
    .A1_N(_138_),
    .A2_N(\wr_gray_next[1] ),
    .B1(_263_),
    .B2(_176_),
    .X(_264_)
  );
  sky130_fd_sc_hd__o22a_2 _490_ (
    .A1(_176_),
    .A2(_263_),
    .B1(\wr_gray_next[2] ),
    .B2(_136_),
    .X(_265_)
  );
  sky130_fd_sc_hd__o2111ai_2 _491_ (
    .A1(\full_compare[2] ),
    .A2(_261_),
    .B1(_262_),
    .C1(_265_),
    .D1(_260_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__a211oi_2 _492_ (
    .A1(_138_),
    .A2(\wr_gray_next[1] ),
    .B1(_264_),
    .C1(_266_),
    .Y(full_next)
  );
  sky130_fd_sc_hd__and2b_2 _493_ (
    .A_N(empty),
    .B(rd_en),
    .X(_267_)
  );
  sky130_fd_sc_hd__nor2_2 _494_ (
    .A(\rd_bin[0] ),
    .B(_267_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__and3b_2 _495_ (
    .A_N(empty),
    .B(rd_en),
    .C(\rd_bin[0] ),
    .X(_269_)
  );
  sky130_fd_sc_hd__nor2_2 _496_ (
    .A(_268_),
    .B(_269_),
    .Y(\rd_bin_next[0] )
  );
  sky130_fd_sc_hd__and3_2 _497_ (
    .A(\rd_bin[0] ),
    .B(\rd_bin[1] ),
    .C(_267_),
    .X(_270_)
  );
  sky130_fd_sc_hd__a21oi_2 _498_ (
    .A1(\rd_bin[0] ),
    .A2(_267_),
    .B1(\rd_bin[1] ),
    .Y(_271_)
  );
  sky130_fd_sc_hd__nor2_2 _499_ (
    .A(_270_),
    .B(_271_),
    .Y(\rd_bin_next[1] )
  );
  sky130_fd_sc_hd__a31o_2 _500_ (
    .A1(\rd_bin[0] ),
    .A2(\rd_bin[1] ),
    .A3(_267_),
    .B1(\rd_bin[2] ),
    .X(_272_)
  );
  sky130_fd_sc_hd__nand2_2 _501_ (
    .A(\rd_bin[2] ),
    .B(_270_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__and2_2 _502_ (
    .A(_272_),
    .B(_273_),
    .X(\rd_bin_next[2] )
  );
  sky130_fd_sc_hd__a31o_2 _503_ (
    .A1(\rd_bin[1] ),
    .A2(\rd_bin[2] ),
    .A3(_269_),
    .B1(\rd_bin[3] ),
    .X(_274_)
  );
  sky130_fd_sc_hd__xor2_2 _504_ (
    .A(\rd_bin[4] ),
    .B(_274_),
    .X(\rd_gray_next[3] )
  );
  sky130_fd_sc_hd__xnor2_2 _505_ (
    .A(\wr_gray_sync2[3] ),
    .B(\rd_gray_next[3] ),
    .Y(_275_)
  );
  sky130_fd_sc_hd__xor2_2 _506_ (
    .A(\rd_bin[2] ),
    .B(_271_),
    .X(_276_)
  );
  sky130_fd_sc_hd__inv_2 _507_ (
    .A(_276_),
    .Y(\rd_gray_next[1] )
  );
  sky130_fd_sc_hd__or3b_2 _508_ (
    .A(_143_),
    .B(_144_),
    .C_N(_270_),
    .X(_277_)
  );
  sky130_fd_sc_hd__xor2_2 _509_ (
    .A(_143_),
    .B(_272_),
    .X(_278_)
  );
  sky130_fd_sc_hd__inv_2 _510_ (
    .A(_278_),
    .Y(\rd_gray_next[2] )
  );
  sky130_fd_sc_hd__xnor2_2 _511_ (
    .A(\rd_bin[1] ),
    .B(_268_),
    .Y(\rd_gray_next[0] )
  );
  sky130_fd_sc_hd__xor2_2 _512_ (
    .A(\wr_gray_sync2[0] ),
    .B(\rd_gray_next[0] ),
    .X(_279_)
  );
  sky130_fd_sc_hd__o22a_2 _513_ (
    .A1(\wr_gray_sync2[1] ),
    .A2(_276_),
    .B1(_278_),
    .B2(\wr_gray_sync2[2] ),
    .X(_280_)
  );
  sky130_fd_sc_hd__a221o_2 _514_ (
    .A1(\wr_gray_sync2[1] ),
    .A2(_276_),
    .B1(_277_),
    .B2(_198_),
    .C1(_279_),
    .X(_281_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _515_ (
    .A1_N(_198_),
    .A2_N(_277_),
    .B1(_278_),
    .B2(\wr_gray_sync2[2] ),
    .X(_282_)
  );
  sky130_fd_sc_hd__nor2_2 _516_ (
    .A(_281_),
    .B(_282_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__and3_2 _517_ (
    .A(_283_),
    .B(_275_),
    .C(_280_),
    .X(empty_next)
  );
  sky130_fd_sc_hd__and4b_2 _518_ (
    .A_N(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .C(\wr_bin[1] ),
    .D(_253_),
    .X(_284_)
  );
  sky130_fd_sc_hd__a21boi_2 _519_ (
    .A1(\wr_bin[2] ),
    .A2(_255_),
    .B1_N(\wr_bin[3] ),
    .Y(_285_)
  );
  sky130_fd_sc_hd__or2_2 _520_ (
    .A(_284_),
    .B(_285_),
    .X(\wr_bin_next[3] )
  );
  sky130_fd_sc_hd__xor2_2 _521_ (
    .A(\wr_bin[4] ),
    .B(_263_),
    .X(\wr_bin_next[4] )
  );
  sky130_fd_sc_hd__and2_2 _522_ (
    .A(_274_),
    .B(_277_),
    .X(\rd_bin_next[3] )
  );
  sky130_fd_sc_hd__xnor2_2 _523_ (
    .A(\rd_bin[4] ),
    .B(_277_),
    .Y(\rd_bin_next[4] )
  );
  sky130_fd_sc_hd__mux4_2 _524_ (
    .A0(\mem[8][0] ),
    .A1(\mem[9][0] ),
    .A2(\mem[10][0] ),
    .A3(\mem[11][0] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_286_)
  );
  sky130_fd_sc_hd__mux4_2 _525_ (
    .A0(\mem[12][0] ),
    .A1(\mem[13][0] ),
    .A2(\mem[14][0] ),
    .A3(\mem[15][0] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_287_)
  );
  sky130_fd_sc_hd__mux4_2 _526_ (
    .A0(\mem[4][0] ),
    .A1(\mem[5][0] ),
    .A2(\mem[6][0] ),
    .A3(\mem[7][0] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_288_)
  );
  sky130_fd_sc_hd__mux4_2 _527_ (
    .A0(\mem[0][0] ),
    .A1(\mem[1][0] ),
    .A2(\mem[2][0] ),
    .A3(\mem[3][0] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_289_)
  );
  sky130_fd_sc_hd__mux4_2 _528_ (
    .A0(_286_),
    .A1(_287_),
    .A2(_289_),
    .A3(_288_),
    .S0(\rd_bin[2] ),
    .S1(_143_),
    .X(_290_)
  );
  sky130_fd_sc_hd__mux2_1 _529_ (
    .A0(rd_data[0]),
    .A1(_290_),
    .S(_267_),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux4_2 _530_ (
    .A0(\mem[8][1] ),
    .A1(\mem[9][1] ),
    .A2(\mem[10][1] ),
    .A3(\mem[11][1] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_291_)
  );
  sky130_fd_sc_hd__mux4_2 _531_ (
    .A0(\mem[12][1] ),
    .A1(\mem[13][1] ),
    .A2(\mem[14][1] ),
    .A3(\mem[15][1] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_292_)
  );
  sky130_fd_sc_hd__mux2_1 _532_ (
    .A0(_291_),
    .A1(_292_),
    .S(\rd_bin[2] ),
    .X(_293_)
  );
  sky130_fd_sc_hd__mux4_2 _533_ (
    .A0(\mem[4][1] ),
    .A1(\mem[5][1] ),
    .A2(\mem[6][1] ),
    .A3(\mem[7][1] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_294_)
  );
  sky130_fd_sc_hd__mux4_2 _534_ (
    .A0(\mem[0][1] ),
    .A1(\mem[1][1] ),
    .A2(\mem[2][1] ),
    .A3(\mem[3][1] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_295_)
  );
  sky130_fd_sc_hd__mux2_1 _535_ (
    .A0(_294_),
    .A1(_295_),
    .S(_144_),
    .X(_296_)
  );
  sky130_fd_sc_hd__mux2_1 _536_ (
    .A0(_293_),
    .A1(_296_),
    .S(_143_),
    .X(_297_)
  );
  sky130_fd_sc_hd__mux2_1 _537_ (
    .A0(rd_data[1]),
    .A1(_297_),
    .S(_267_),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux4_2 _538_ (
    .A0(\mem[4][2] ),
    .A1(\mem[5][2] ),
    .A2(\mem[6][2] ),
    .A3(\mem[7][2] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_298_)
  );
  sky130_fd_sc_hd__mux4_2 _539_ (
    .A0(\mem[0][2] ),
    .A1(\mem[1][2] ),
    .A2(\mem[2][2] ),
    .A3(\mem[3][2] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_299_)
  );
  sky130_fd_sc_hd__mux2_1 _540_ (
    .A0(_298_),
    .A1(_299_),
    .S(_144_),
    .X(_300_)
  );
  sky130_fd_sc_hd__mux4_2 _541_ (
    .A0(\mem[12][2] ),
    .A1(\mem[13][2] ),
    .A2(\mem[14][2] ),
    .A3(\mem[15][2] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_301_)
  );
  sky130_fd_sc_hd__mux4_2 _542_ (
    .A0(\mem[8][2] ),
    .A1(\mem[9][2] ),
    .A2(\mem[10][2] ),
    .A3(\mem[11][2] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_302_)
  );
  sky130_fd_sc_hd__mux2_1 _543_ (
    .A0(_301_),
    .A1(_302_),
    .S(_144_),
    .X(_303_)
  );
  sky130_fd_sc_hd__mux2_1 _544_ (
    .A0(_300_),
    .A1(_303_),
    .S(\rd_bin[3] ),
    .X(_304_)
  );
  sky130_fd_sc_hd__mux2_1 _545_ (
    .A0(rd_data[2]),
    .A1(_304_),
    .S(_267_),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux4_2 _546_ (
    .A0(\mem[4][3] ),
    .A1(\mem[5][3] ),
    .A2(\mem[6][3] ),
    .A3(\mem[7][3] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_305_)
  );
  sky130_fd_sc_hd__mux4_2 _547_ (
    .A0(\mem[0][3] ),
    .A1(\mem[1][3] ),
    .A2(\mem[2][3] ),
    .A3(\mem[3][3] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_306_)
  );
  sky130_fd_sc_hd__mux4_2 _548_ (
    .A0(\mem[12][3] ),
    .A1(\mem[13][3] ),
    .A2(\mem[14][3] ),
    .A3(\mem[15][3] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_307_)
  );
  sky130_fd_sc_hd__mux4_2 _549_ (
    .A0(\mem[8][3] ),
    .A1(\mem[9][3] ),
    .A2(\mem[10][3] ),
    .A3(\mem[11][3] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_308_)
  );
  sky130_fd_sc_hd__mux4_2 _550_ (
    .A0(_305_),
    .A1(_306_),
    .A2(_307_),
    .A3(_308_),
    .S0(_144_),
    .S1(\rd_bin[3] ),
    .X(_309_)
  );
  sky130_fd_sc_hd__mux2_1 _551_ (
    .A0(rd_data[3]),
    .A1(_309_),
    .S(_267_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux4_2 _552_ (
    .A0(\mem[4][4] ),
    .A1(\mem[5][4] ),
    .A2(\mem[6][4] ),
    .A3(\mem[7][4] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_310_)
  );
  sky130_fd_sc_hd__mux4_2 _553_ (
    .A0(\mem[0][4] ),
    .A1(\mem[1][4] ),
    .A2(\mem[2][4] ),
    .A3(\mem[3][4] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_311_)
  );
  sky130_fd_sc_hd__mux2_1 _554_ (
    .A0(_310_),
    .A1(_311_),
    .S(_144_),
    .X(_312_)
  );
  sky130_fd_sc_hd__mux4_2 _555_ (
    .A0(\mem[12][4] ),
    .A1(\mem[13][4] ),
    .A2(\mem[14][4] ),
    .A3(\mem[15][4] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_313_)
  );
  sky130_fd_sc_hd__mux4_2 _556_ (
    .A0(\mem[8][4] ),
    .A1(\mem[9][4] ),
    .A2(\mem[10][4] ),
    .A3(\mem[11][4] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_314_)
  );
  sky130_fd_sc_hd__mux2_1 _557_ (
    .A0(_313_),
    .A1(_314_),
    .S(_144_),
    .X(_315_)
  );
  sky130_fd_sc_hd__mux2_1 _558_ (
    .A0(_312_),
    .A1(_315_),
    .S(\rd_bin[3] ),
    .X(_316_)
  );
  sky130_fd_sc_hd__mux2_1 _559_ (
    .A0(rd_data[4]),
    .A1(_316_),
    .S(_267_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux4_2 _560_ (
    .A0(\mem[4][5] ),
    .A1(\mem[5][5] ),
    .A2(\mem[6][5] ),
    .A3(\mem[7][5] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_317_)
  );
  sky130_fd_sc_hd__mux4_2 _561_ (
    .A0(\mem[0][5] ),
    .A1(\mem[1][5] ),
    .A2(\mem[2][5] ),
    .A3(\mem[3][5] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_318_)
  );
  sky130_fd_sc_hd__mux4_2 _562_ (
    .A0(\mem[12][5] ),
    .A1(\mem[13][5] ),
    .A2(\mem[14][5] ),
    .A3(\mem[15][5] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_319_)
  );
  sky130_fd_sc_hd__mux4_2 _563_ (
    .A0(\mem[8][5] ),
    .A1(\mem[9][5] ),
    .A2(\mem[10][5] ),
    .A3(\mem[11][5] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_320_)
  );
  sky130_fd_sc_hd__mux4_2 _564_ (
    .A0(_317_),
    .A1(_318_),
    .A2(_319_),
    .A3(_320_),
    .S0(_144_),
    .S1(\rd_bin[3] ),
    .X(_321_)
  );
  sky130_fd_sc_hd__mux2_1 _565_ (
    .A0(rd_data[5]),
    .A1(_321_),
    .S(_267_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux4_2 _566_ (
    .A0(\mem[4][6] ),
    .A1(\mem[5][6] ),
    .A2(\mem[6][6] ),
    .A3(\mem[7][6] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_322_)
  );
  sky130_fd_sc_hd__mux4_2 _567_ (
    .A0(\mem[0][6] ),
    .A1(\mem[1][6] ),
    .A2(\mem[2][6] ),
    .A3(\mem[3][6] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_323_)
  );
  sky130_fd_sc_hd__mux2_1 _568_ (
    .A0(_322_),
    .A1(_323_),
    .S(_144_),
    .X(_324_)
  );
  sky130_fd_sc_hd__mux4_2 _569_ (
    .A0(\mem[12][6] ),
    .A1(\mem[13][6] ),
    .A2(\mem[14][6] ),
    .A3(\mem[15][6] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_325_)
  );
  sky130_fd_sc_hd__mux4_2 _570_ (
    .A0(\mem[8][6] ),
    .A1(\mem[9][6] ),
    .A2(\mem[10][6] ),
    .A3(\mem[11][6] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_326_)
  );
  sky130_fd_sc_hd__mux2_1 _571_ (
    .A0(_325_),
    .A1(_326_),
    .S(_144_),
    .X(_327_)
  );
  sky130_fd_sc_hd__mux2_1 _572_ (
    .A0(_324_),
    .A1(_327_),
    .S(\rd_bin[3] ),
    .X(_328_)
  );
  sky130_fd_sc_hd__mux2_1 _573_ (
    .A0(rd_data[6]),
    .A1(_328_),
    .S(_267_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux4_2 _574_ (
    .A0(\mem[4][7] ),
    .A1(\mem[5][7] ),
    .A2(\mem[6][7] ),
    .A3(\mem[7][7] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_329_)
  );
  sky130_fd_sc_hd__mux4_2 _575_ (
    .A0(\mem[0][7] ),
    .A1(\mem[1][7] ),
    .A2(\mem[2][7] ),
    .A3(\mem[3][7] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_330_)
  );
  sky130_fd_sc_hd__mux2_1 _576_ (
    .A0(_329_),
    .A1(_330_),
    .S(_144_),
    .X(_331_)
  );
  sky130_fd_sc_hd__mux4_2 _577_ (
    .A0(\mem[12][7] ),
    .A1(\mem[13][7] ),
    .A2(\mem[14][7] ),
    .A3(\mem[15][7] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_332_)
  );
  sky130_fd_sc_hd__mux4_2 _578_ (
    .A0(\mem[8][7] ),
    .A1(\mem[9][7] ),
    .A2(\mem[10][7] ),
    .A3(\mem[11][7] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_333_)
  );
  sky130_fd_sc_hd__mux2_1 _579_ (
    .A0(_332_),
    .A1(_333_),
    .S(_144_),
    .X(_334_)
  );
  sky130_fd_sc_hd__mux2_1 _580_ (
    .A0(_331_),
    .A1(_334_),
    .S(\rd_bin[3] ),
    .X(_335_)
  );
  sky130_fd_sc_hd__mux2_1 _581_ (
    .A0(rd_data[7]),
    .A1(_335_),
    .S(_267_),
    .X(_007_)
  );
  sky130_fd_sc_hd__and4b_2 _582_ (
    .A_N(\wr_bin[0] ),
    .B(_147_),
    .C(wr_en),
    .D(\wr_bin[1] ),
    .X(_336_)
  );
  sky130_fd_sc_hd__and3_2 _583_ (
    .A(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .C(_336_),
    .X(_337_)
  );
  sky130_fd_sc_hd__mux2_1 _584_ (
    .A0(\mem[14][0] ),
    .A1(wr_data[0]),
    .S(_337_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _585_ (
    .A0(\mem[14][1] ),
    .A1(wr_data[1]),
    .S(_337_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _586_ (
    .A0(\mem[14][2] ),
    .A1(wr_data[2]),
    .S(_337_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _587_ (
    .A0(\mem[14][3] ),
    .A1(wr_data[3]),
    .S(_337_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _588_ (
    .A0(\mem[14][4] ),
    .A1(wr_data[4]),
    .S(_337_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _589_ (
    .A0(\mem[14][5] ),
    .A1(wr_data[5]),
    .S(_337_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _590_ (
    .A0(\mem[14][6] ),
    .A1(wr_data[6]),
    .S(_337_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _591_ (
    .A0(\mem[14][7] ),
    .A1(wr_data[7]),
    .S(_337_),
    .X(_015_)
  );
  sky130_fd_sc_hd__and4b_2 _592_ (
    .A_N(\wr_bin[1] ),
    .B(_253_),
    .C(\wr_bin[3] ),
    .D(\wr_bin[2] ),
    .X(_338_)
  );
  sky130_fd_sc_hd__mux2_1 _593_ (
    .A0(\mem[13][0] ),
    .A1(wr_data[0]),
    .S(_338_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _594_ (
    .A0(\mem[13][1] ),
    .A1(wr_data[1]),
    .S(_338_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _595_ (
    .A0(\mem[13][2] ),
    .A1(wr_data[2]),
    .S(_338_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _596_ (
    .A0(\mem[13][3] ),
    .A1(wr_data[3]),
    .S(_338_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _597_ (
    .A0(\mem[13][4] ),
    .A1(wr_data[4]),
    .S(_338_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _598_ (
    .A0(\mem[13][5] ),
    .A1(wr_data[5]),
    .S(_338_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _599_ (
    .A0(\mem[13][6] ),
    .A1(wr_data[6]),
    .S(_338_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _600_ (
    .A0(\mem[13][7] ),
    .A1(wr_data[7]),
    .S(_338_),
    .X(_023_)
  );
  sky130_fd_sc_hd__and4bb_2 _601_ (
    .A_N(\wr_bin[1] ),
    .B_N(\wr_bin[0] ),
    .C(wr_en),
    .D(_147_),
    .X(_339_)
  );
  sky130_fd_sc_hd__and3_2 _602_ (
    .A(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .C(_339_),
    .X(_340_)
  );
  sky130_fd_sc_hd__mux2_1 _603_ (
    .A0(\mem[12][0] ),
    .A1(wr_data[0]),
    .S(_340_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _604_ (
    .A0(\mem[12][1] ),
    .A1(wr_data[1]),
    .S(_340_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _605_ (
    .A0(\mem[12][2] ),
    .A1(wr_data[2]),
    .S(_340_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _606_ (
    .A0(\mem[12][3] ),
    .A1(wr_data[3]),
    .S(_340_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _607_ (
    .A0(\mem[12][4] ),
    .A1(wr_data[4]),
    .S(_340_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _608_ (
    .A0(\mem[12][5] ),
    .A1(wr_data[5]),
    .S(_340_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _609_ (
    .A0(\mem[12][6] ),
    .A1(wr_data[6]),
    .S(_340_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _610_ (
    .A0(\mem[12][7] ),
    .A1(wr_data[7]),
    .S(_340_),
    .X(_031_)
  );
  sky130_fd_sc_hd__and3_2 _611_ (
    .A(\wr_bin[3] ),
    .B(_255_),
    .C(_137_),
    .X(_341_)
  );
  sky130_fd_sc_hd__mux2_1 _612_ (
    .A0(\mem[11][0] ),
    .A1(wr_data[0]),
    .S(_341_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _613_ (
    .A0(\mem[11][1] ),
    .A1(wr_data[1]),
    .S(_341_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _614_ (
    .A0(\mem[11][2] ),
    .A1(wr_data[2]),
    .S(_341_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _615_ (
    .A0(\mem[11][3] ),
    .A1(wr_data[3]),
    .S(_341_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _616_ (
    .A0(\mem[11][4] ),
    .A1(wr_data[4]),
    .S(_341_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _617_ (
    .A0(\mem[11][5] ),
    .A1(wr_data[5]),
    .S(_341_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _618_ (
    .A0(\mem[11][6] ),
    .A1(wr_data[6]),
    .S(_341_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _619_ (
    .A0(\mem[11][7] ),
    .A1(wr_data[7]),
    .S(_341_),
    .X(_039_)
  );
  sky130_fd_sc_hd__nor4b_2 _620_ (
    .A(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .C(\wr_bin[1] ),
    .D_N(_253_),
    .Y(_342_)
  );
  sky130_fd_sc_hd__mux2_1 _621_ (
    .A0(\mem[1][0] ),
    .A1(wr_data[0]),
    .S(_342_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _622_ (
    .A0(\mem[1][1] ),
    .A1(wr_data[1]),
    .S(_342_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _623_ (
    .A0(\mem[1][2] ),
    .A1(wr_data[2]),
    .S(_342_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _624_ (
    .A0(\mem[1][3] ),
    .A1(wr_data[3]),
    .S(_342_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _625_ (
    .A0(\mem[1][4] ),
    .A1(wr_data[4]),
    .S(_342_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _626_ (
    .A0(\mem[1][5] ),
    .A1(wr_data[5]),
    .S(_342_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _627_ (
    .A0(\mem[1][6] ),
    .A1(wr_data[6]),
    .S(_342_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _628_ (
    .A0(\mem[1][7] ),
    .A1(wr_data[7]),
    .S(_342_),
    .X(_047_)
  );
  sky130_fd_sc_hd__and3_2 _629_ (
    .A(\wr_bin[3] ),
    .B(_336_),
    .C(_137_),
    .X(_343_)
  );
  sky130_fd_sc_hd__mux2_1 _630_ (
    .A0(\mem[10][0] ),
    .A1(wr_data[0]),
    .S(_343_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _631_ (
    .A0(\mem[10][1] ),
    .A1(wr_data[1]),
    .S(_343_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _632_ (
    .A0(\mem[10][2] ),
    .A1(wr_data[2]),
    .S(_343_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _633_ (
    .A0(\mem[10][3] ),
    .A1(wr_data[3]),
    .S(_343_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _634_ (
    .A0(\mem[10][4] ),
    .A1(wr_data[4]),
    .S(_343_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _635_ (
    .A0(\mem[10][5] ),
    .A1(wr_data[5]),
    .S(_343_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _636_ (
    .A0(\mem[10][6] ),
    .A1(wr_data[6]),
    .S(_343_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _637_ (
    .A0(\mem[10][7] ),
    .A1(wr_data[7]),
    .S(_343_),
    .X(_055_)
  );
  sky130_fd_sc_hd__and3b_2 _638_ (
    .A_N(\wr_bin[3] ),
    .B(_339_),
    .C(_137_),
    .X(_344_)
  );
  sky130_fd_sc_hd__mux2_1 _639_ (
    .A0(\mem[0][0] ),
    .A1(wr_data[0]),
    .S(_344_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _640_ (
    .A0(\mem[0][1] ),
    .A1(wr_data[1]),
    .S(_344_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _641_ (
    .A0(\mem[0][2] ),
    .A1(wr_data[2]),
    .S(_344_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _642_ (
    .A0(\mem[0][3] ),
    .A1(wr_data[3]),
    .S(_344_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _643_ (
    .A0(\mem[0][4] ),
    .A1(wr_data[4]),
    .S(_344_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _644_ (
    .A0(\mem[0][5] ),
    .A1(wr_data[5]),
    .S(_344_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _645_ (
    .A0(\mem[0][6] ),
    .A1(wr_data[6]),
    .S(_344_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _646_ (
    .A0(\mem[0][7] ),
    .A1(wr_data[7]),
    .S(_344_),
    .X(_063_)
  );
  sky130_fd_sc_hd__and3_2 _647_ (
    .A(\wr_bin[3] ),
    .B(_339_),
    .C(_137_),
    .X(_345_)
  );
  sky130_fd_sc_hd__mux2_1 _648_ (
    .A0(\mem[8][0] ),
    .A1(wr_data[0]),
    .S(_345_),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2_1 _649_ (
    .A0(\mem[8][1] ),
    .A1(wr_data[1]),
    .S(_345_),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2_1 _650_ (
    .A0(\mem[8][2] ),
    .A1(wr_data[2]),
    .S(_345_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2_1 _651_ (
    .A0(\mem[8][3] ),
    .A1(wr_data[3]),
    .S(_345_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_1 _652_ (
    .A0(\mem[8][4] ),
    .A1(wr_data[4]),
    .S(_345_),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux2_1 _653_ (
    .A0(\mem[8][5] ),
    .A1(wr_data[5]),
    .S(_345_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_1 _654_ (
    .A0(\mem[8][6] ),
    .A1(wr_data[6]),
    .S(_345_),
    .X(_070_)
  );
  sky130_fd_sc_hd__mux2_1 _655_ (
    .A0(\mem[8][7] ),
    .A1(wr_data[7]),
    .S(_345_),
    .X(_071_)
  );
  sky130_fd_sc_hd__mux2_1 _656_ (
    .A0(\mem[7][0] ),
    .A1(wr_data[0]),
    .S(_284_),
    .X(_072_)
  );
  sky130_fd_sc_hd__mux2_1 _657_ (
    .A0(\mem[7][1] ),
    .A1(wr_data[1]),
    .S(_284_),
    .X(_073_)
  );
  sky130_fd_sc_hd__mux2_1 _658_ (
    .A0(\mem[7][2] ),
    .A1(wr_data[2]),
    .S(_284_),
    .X(_074_)
  );
  sky130_fd_sc_hd__mux2_1 _659_ (
    .A0(\mem[7][3] ),
    .A1(wr_data[3]),
    .S(_284_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux2_1 _660_ (
    .A0(\mem[7][4] ),
    .A1(wr_data[4]),
    .S(_284_),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux2_1 _661_ (
    .A0(\mem[7][5] ),
    .A1(wr_data[5]),
    .S(_284_),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux2_1 _662_ (
    .A0(\mem[7][6] ),
    .A1(wr_data[6]),
    .S(_284_),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux2_1 _663_ (
    .A0(\mem[7][7] ),
    .A1(wr_data[7]),
    .S(_284_),
    .X(_079_)
  );
  sky130_fd_sc_hd__and3b_2 _664_ (
    .A_N(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .C(_336_),
    .X(_346_)
  );
  sky130_fd_sc_hd__mux2_1 _665_ (
    .A0(\mem[6][0] ),
    .A1(wr_data[0]),
    .S(_346_),
    .X(_080_)
  );
  sky130_fd_sc_hd__mux2_1 _666_ (
    .A0(\mem[6][1] ),
    .A1(wr_data[1]),
    .S(_346_),
    .X(_081_)
  );
  sky130_fd_sc_hd__mux2_1 _667_ (
    .A0(\mem[6][2] ),
    .A1(wr_data[2]),
    .S(_346_),
    .X(_082_)
  );
  sky130_fd_sc_hd__mux2_1 _668_ (
    .A0(\mem[6][3] ),
    .A1(wr_data[3]),
    .S(_346_),
    .X(_083_)
  );
  sky130_fd_sc_hd__mux2_1 _669_ (
    .A0(\mem[6][4] ),
    .A1(wr_data[4]),
    .S(_346_),
    .X(_084_)
  );
  sky130_fd_sc_hd__mux2_1 _670_ (
    .A0(\mem[6][5] ),
    .A1(wr_data[5]),
    .S(_346_),
    .X(_085_)
  );
  sky130_fd_sc_hd__mux2_1 _671_ (
    .A0(\mem[6][6] ),
    .A1(wr_data[6]),
    .S(_346_),
    .X(_086_)
  );
  sky130_fd_sc_hd__mux2_1 _672_ (
    .A0(\mem[6][7] ),
    .A1(wr_data[7]),
    .S(_346_),
    .X(_087_)
  );
  sky130_fd_sc_hd__and3b_2 _673_ (
    .A_N(\wr_bin[3] ),
    .B(_336_),
    .C(_137_),
    .X(_347_)
  );
  sky130_fd_sc_hd__mux2_1 _674_ (
    .A0(\mem[2][0] ),
    .A1(wr_data[0]),
    .S(_347_),
    .X(_088_)
  );
  sky130_fd_sc_hd__mux2_1 _675_ (
    .A0(\mem[2][1] ),
    .A1(wr_data[1]),
    .S(_347_),
    .X(_089_)
  );
  sky130_fd_sc_hd__mux2_1 _676_ (
    .A0(\mem[2][2] ),
    .A1(wr_data[2]),
    .S(_347_),
    .X(_090_)
  );
  sky130_fd_sc_hd__mux2_1 _677_ (
    .A0(\mem[2][3] ),
    .A1(wr_data[3]),
    .S(_347_),
    .X(_091_)
  );
  sky130_fd_sc_hd__mux2_1 _678_ (
    .A0(\mem[2][4] ),
    .A1(wr_data[4]),
    .S(_347_),
    .X(_092_)
  );
  sky130_fd_sc_hd__mux2_1 _679_ (
    .A0(\mem[2][5] ),
    .A1(wr_data[5]),
    .S(_347_),
    .X(_093_)
  );
  sky130_fd_sc_hd__mux2_1 _680_ (
    .A0(\mem[2][6] ),
    .A1(wr_data[6]),
    .S(_347_),
    .X(_094_)
  );
  sky130_fd_sc_hd__mux2_1 _681_ (
    .A0(\mem[2][7] ),
    .A1(wr_data[7]),
    .S(_347_),
    .X(_095_)
  );
  sky130_fd_sc_hd__or3b_2 _682_ (
    .A(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .C_N(_255_),
    .X(_348_)
  );
  sky130_fd_sc_hd__mux2_1 _683_ (
    .A0(wr_data[0]),
    .A1(\mem[3][0] ),
    .S(_348_),
    .X(_096_)
  );
  sky130_fd_sc_hd__mux2_1 _684_ (
    .A0(wr_data[1]),
    .A1(\mem[3][1] ),
    .S(_348_),
    .X(_097_)
  );
  sky130_fd_sc_hd__mux2_1 _685_ (
    .A0(wr_data[2]),
    .A1(\mem[3][2] ),
    .S(_348_),
    .X(_098_)
  );
  sky130_fd_sc_hd__mux2_1 _686_ (
    .A0(wr_data[3]),
    .A1(\mem[3][3] ),
    .S(_348_),
    .X(_099_)
  );
  sky130_fd_sc_hd__mux2_1 _687_ (
    .A0(wr_data[4]),
    .A1(\mem[3][4] ),
    .S(_348_),
    .X(_100_)
  );
  sky130_fd_sc_hd__mux2_1 _688_ (
    .A0(wr_data[5]),
    .A1(\mem[3][5] ),
    .S(_348_),
    .X(_101_)
  );
  sky130_fd_sc_hd__mux2_1 _689_ (
    .A0(wr_data[6]),
    .A1(\mem[3][6] ),
    .S(_348_),
    .X(_102_)
  );
  sky130_fd_sc_hd__mux2_1 _690_ (
    .A0(wr_data[7]),
    .A1(\mem[3][7] ),
    .S(_348_),
    .X(_103_)
  );
  sky130_fd_sc_hd__and4bb_2 _691_ (
    .A_N(\wr_bin[3] ),
    .B_N(\wr_bin[1] ),
    .C(_253_),
    .D(\wr_bin[2] ),
    .X(_349_)
  );
  sky130_fd_sc_hd__mux2_1 _692_ (
    .A0(\mem[5][0] ),
    .A1(wr_data[0]),
    .S(_349_),
    .X(_104_)
  );
  sky130_fd_sc_hd__mux2_1 _693_ (
    .A0(\mem[5][1] ),
    .A1(wr_data[1]),
    .S(_349_),
    .X(_105_)
  );
  sky130_fd_sc_hd__mux2_1 _694_ (
    .A0(\mem[5][2] ),
    .A1(wr_data[2]),
    .S(_349_),
    .X(_106_)
  );
  sky130_fd_sc_hd__mux2_1 _695_ (
    .A0(\mem[5][3] ),
    .A1(wr_data[3]),
    .S(_349_),
    .X(_107_)
  );
  sky130_fd_sc_hd__mux2_1 _696_ (
    .A0(\mem[5][4] ),
    .A1(wr_data[4]),
    .S(_349_),
    .X(_108_)
  );
  sky130_fd_sc_hd__mux2_1 _697_ (
    .A0(\mem[5][5] ),
    .A1(wr_data[5]),
    .S(_349_),
    .X(_109_)
  );
  sky130_fd_sc_hd__mux2_1 _698_ (
    .A0(\mem[5][6] ),
    .A1(wr_data[6]),
    .S(_349_),
    .X(_110_)
  );
  sky130_fd_sc_hd__mux2_1 _699_ (
    .A0(\mem[5][7] ),
    .A1(wr_data[7]),
    .S(_349_),
    .X(_111_)
  );
  sky130_fd_sc_hd__and3b_2 _700_ (
    .A_N(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .C(_339_),
    .X(_350_)
  );
  sky130_fd_sc_hd__mux2_1 _701_ (
    .A0(\mem[4][0] ),
    .A1(wr_data[0]),
    .S(_350_),
    .X(_112_)
  );
  sky130_fd_sc_hd__mux2_1 _702_ (
    .A0(\mem[4][1] ),
    .A1(wr_data[1]),
    .S(_350_),
    .X(_113_)
  );
  sky130_fd_sc_hd__mux2_1 _703_ (
    .A0(\mem[4][2] ),
    .A1(wr_data[2]),
    .S(_350_),
    .X(_114_)
  );
  sky130_fd_sc_hd__mux2_1 _704_ (
    .A0(\mem[4][3] ),
    .A1(wr_data[3]),
    .S(_350_),
    .X(_115_)
  );
  sky130_fd_sc_hd__mux2_1 _705_ (
    .A0(\mem[4][4] ),
    .A1(wr_data[4]),
    .S(_350_),
    .X(_116_)
  );
  sky130_fd_sc_hd__mux2_1 _706_ (
    .A0(\mem[4][5] ),
    .A1(wr_data[5]),
    .S(_350_),
    .X(_117_)
  );
  sky130_fd_sc_hd__mux2_1 _707_ (
    .A0(\mem[4][6] ),
    .A1(wr_data[6]),
    .S(_350_),
    .X(_118_)
  );
  sky130_fd_sc_hd__mux2_1 _708_ (
    .A0(\mem[4][7] ),
    .A1(wr_data[7]),
    .S(_350_),
    .X(_119_)
  );
  sky130_fd_sc_hd__mux2_1 _709_ (
    .A0(\mem[15][0] ),
    .A1(wr_data[0]),
    .S(_263_),
    .X(_120_)
  );
  sky130_fd_sc_hd__mux2_1 _710_ (
    .A0(\mem[15][1] ),
    .A1(wr_data[1]),
    .S(_263_),
    .X(_121_)
  );
  sky130_fd_sc_hd__mux2_1 _711_ (
    .A0(\mem[15][2] ),
    .A1(wr_data[2]),
    .S(_263_),
    .X(_122_)
  );
  sky130_fd_sc_hd__mux2_1 _712_ (
    .A0(\mem[15][3] ),
    .A1(wr_data[3]),
    .S(_263_),
    .X(_123_)
  );
  sky130_fd_sc_hd__mux2_1 _713_ (
    .A0(\mem[15][4] ),
    .A1(wr_data[4]),
    .S(_263_),
    .X(_124_)
  );
  sky130_fd_sc_hd__mux2_1 _714_ (
    .A0(\mem[15][5] ),
    .A1(wr_data[5]),
    .S(_263_),
    .X(_125_)
  );
  sky130_fd_sc_hd__mux2_1 _715_ (
    .A0(\mem[15][6] ),
    .A1(wr_data[6]),
    .S(_263_),
    .X(_126_)
  );
  sky130_fd_sc_hd__mux2_1 _716_ (
    .A0(\mem[15][7] ),
    .A1(wr_data[7]),
    .S(_263_),
    .X(_127_)
  );
  sky130_fd_sc_hd__and4bb_2 _717_ (
    .A_N(\wr_bin[2] ),
    .B_N(\wr_bin[1] ),
    .C(_253_),
    .D(\wr_bin[3] ),
    .X(_351_)
  );
  sky130_fd_sc_hd__mux2_1 _718_ (
    .A0(\mem[9][0] ),
    .A1(wr_data[0]),
    .S(_351_),
    .X(_128_)
  );
  sky130_fd_sc_hd__mux2_1 _719_ (
    .A0(\mem[9][1] ),
    .A1(wr_data[1]),
    .S(_351_),
    .X(_129_)
  );
  sky130_fd_sc_hd__mux2_1 _720_ (
    .A0(\mem[9][2] ),
    .A1(wr_data[2]),
    .S(_351_),
    .X(_130_)
  );
  sky130_fd_sc_hd__mux2_1 _721_ (
    .A0(\mem[9][3] ),
    .A1(wr_data[3]),
    .S(_351_),
    .X(_131_)
  );
  sky130_fd_sc_hd__mux2_1 _722_ (
    .A0(\mem[9][4] ),
    .A1(wr_data[4]),
    .S(_351_),
    .X(_132_)
  );
  sky130_fd_sc_hd__mux2_1 _723_ (
    .A0(\mem[9][5] ),
    .A1(wr_data[5]),
    .S(_351_),
    .X(_133_)
  );
  sky130_fd_sc_hd__mux2_1 _724_ (
    .A0(\mem[9][6] ),
    .A1(wr_data[6]),
    .S(_351_),
    .X(_134_)
  );
  sky130_fd_sc_hd__mux2_1 _725_ (
    .A0(\mem[9][7] ),
    .A1(wr_data[7]),
    .S(_351_),
    .X(_135_)
  );
  sky130_fd_sc_hd__dfrtp_2 _726_ (
    .CLK(rd_clk),
    .D(_000_),
    .Q(rd_data[0]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _727_ (
    .CLK(rd_clk),
    .D(_001_),
    .Q(rd_data[1]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _728_ (
    .CLK(rd_clk),
    .D(_002_),
    .Q(rd_data[2]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _729_ (
    .CLK(rd_clk),
    .D(_003_),
    .Q(rd_data[3]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _730_ (
    .CLK(rd_clk),
    .D(_004_),
    .Q(rd_data[4]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _731_ (
    .CLK(rd_clk),
    .D(_005_),
    .Q(rd_data[5]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _732_ (
    .CLK(rd_clk),
    .D(_006_),
    .Q(rd_data[6]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _733_ (
    .CLK(rd_clk),
    .D(_007_),
    .Q(rd_data[7]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfxtp_2 _734_ (
    .CLK(wr_clk),
    .D(_008_),
    .Q(\mem[14][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _735_ (
    .CLK(wr_clk),
    .D(_009_),
    .Q(\mem[14][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _736_ (
    .CLK(wr_clk),
    .D(_010_),
    .Q(\mem[14][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _737_ (
    .CLK(wr_clk),
    .D(_011_),
    .Q(\mem[14][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _738_ (
    .CLK(wr_clk),
    .D(_012_),
    .Q(\mem[14][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _739_ (
    .CLK(wr_clk),
    .D(_013_),
    .Q(\mem[14][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _740_ (
    .CLK(wr_clk),
    .D(_014_),
    .Q(\mem[14][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _741_ (
    .CLK(wr_clk),
    .D(_015_),
    .Q(\mem[14][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _742_ (
    .CLK(wr_clk),
    .D(_016_),
    .Q(\mem[13][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _743_ (
    .CLK(wr_clk),
    .D(_017_),
    .Q(\mem[13][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _744_ (
    .CLK(wr_clk),
    .D(_018_),
    .Q(\mem[13][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _745_ (
    .CLK(wr_clk),
    .D(_019_),
    .Q(\mem[13][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _746_ (
    .CLK(wr_clk),
    .D(_020_),
    .Q(\mem[13][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _747_ (
    .CLK(wr_clk),
    .D(_021_),
    .Q(\mem[13][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _748_ (
    .CLK(wr_clk),
    .D(_022_),
    .Q(\mem[13][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _749_ (
    .CLK(wr_clk),
    .D(_023_),
    .Q(\mem[13][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _750_ (
    .CLK(wr_clk),
    .D(_024_),
    .Q(\mem[12][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _751_ (
    .CLK(wr_clk),
    .D(_025_),
    .Q(\mem[12][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _752_ (
    .CLK(wr_clk),
    .D(_026_),
    .Q(\mem[12][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _753_ (
    .CLK(wr_clk),
    .D(_027_),
    .Q(\mem[12][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _754_ (
    .CLK(wr_clk),
    .D(_028_),
    .Q(\mem[12][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _755_ (
    .CLK(wr_clk),
    .D(_029_),
    .Q(\mem[12][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _756_ (
    .CLK(wr_clk),
    .D(_030_),
    .Q(\mem[12][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _757_ (
    .CLK(wr_clk),
    .D(_031_),
    .Q(\mem[12][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _758_ (
    .CLK(wr_clk),
    .D(_032_),
    .Q(\mem[11][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _759_ (
    .CLK(wr_clk),
    .D(_033_),
    .Q(\mem[11][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _760_ (
    .CLK(wr_clk),
    .D(_034_),
    .Q(\mem[11][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _761_ (
    .CLK(wr_clk),
    .D(_035_),
    .Q(\mem[11][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _762_ (
    .CLK(wr_clk),
    .D(_036_),
    .Q(\mem[11][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _763_ (
    .CLK(wr_clk),
    .D(_037_),
    .Q(\mem[11][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _764_ (
    .CLK(wr_clk),
    .D(_038_),
    .Q(\mem[11][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _765_ (
    .CLK(wr_clk),
    .D(_039_),
    .Q(\mem[11][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _766_ (
    .CLK(wr_clk),
    .D(_040_),
    .Q(\mem[1][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _767_ (
    .CLK(wr_clk),
    .D(_041_),
    .Q(\mem[1][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _768_ (
    .CLK(wr_clk),
    .D(_042_),
    .Q(\mem[1][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _769_ (
    .CLK(wr_clk),
    .D(_043_),
    .Q(\mem[1][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _770_ (
    .CLK(wr_clk),
    .D(_044_),
    .Q(\mem[1][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _771_ (
    .CLK(wr_clk),
    .D(_045_),
    .Q(\mem[1][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _772_ (
    .CLK(wr_clk),
    .D(_046_),
    .Q(\mem[1][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _773_ (
    .CLK(wr_clk),
    .D(_047_),
    .Q(\mem[1][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _774_ (
    .CLK(wr_clk),
    .D(_048_),
    .Q(\mem[10][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _775_ (
    .CLK(wr_clk),
    .D(_049_),
    .Q(\mem[10][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _776_ (
    .CLK(wr_clk),
    .D(_050_),
    .Q(\mem[10][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _777_ (
    .CLK(wr_clk),
    .D(_051_),
    .Q(\mem[10][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _778_ (
    .CLK(wr_clk),
    .D(_052_),
    .Q(\mem[10][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _779_ (
    .CLK(wr_clk),
    .D(_053_),
    .Q(\mem[10][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _780_ (
    .CLK(wr_clk),
    .D(_054_),
    .Q(\mem[10][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _781_ (
    .CLK(wr_clk),
    .D(_055_),
    .Q(\mem[10][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _782_ (
    .CLK(wr_clk),
    .D(_056_),
    .Q(\mem[0][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _783_ (
    .CLK(wr_clk),
    .D(_057_),
    .Q(\mem[0][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _784_ (
    .CLK(wr_clk),
    .D(_058_),
    .Q(\mem[0][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _785_ (
    .CLK(wr_clk),
    .D(_059_),
    .Q(\mem[0][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _786_ (
    .CLK(wr_clk),
    .D(_060_),
    .Q(\mem[0][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _787_ (
    .CLK(wr_clk),
    .D(_061_),
    .Q(\mem[0][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _788_ (
    .CLK(wr_clk),
    .D(_062_),
    .Q(\mem[0][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _789_ (
    .CLK(wr_clk),
    .D(_063_),
    .Q(\mem[0][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _790_ (
    .CLK(wr_clk),
    .D(_064_),
    .Q(\mem[8][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _791_ (
    .CLK(wr_clk),
    .D(_065_),
    .Q(\mem[8][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _792_ (
    .CLK(wr_clk),
    .D(_066_),
    .Q(\mem[8][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _793_ (
    .CLK(wr_clk),
    .D(_067_),
    .Q(\mem[8][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _794_ (
    .CLK(wr_clk),
    .D(_068_),
    .Q(\mem[8][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _795_ (
    .CLK(wr_clk),
    .D(_069_),
    .Q(\mem[8][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _796_ (
    .CLK(wr_clk),
    .D(_070_),
    .Q(\mem[8][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _797_ (
    .CLK(wr_clk),
    .D(_071_),
    .Q(\mem[8][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _798_ (
    .CLK(wr_clk),
    .D(_072_),
    .Q(\mem[7][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _799_ (
    .CLK(wr_clk),
    .D(_073_),
    .Q(\mem[7][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _800_ (
    .CLK(wr_clk),
    .D(_074_),
    .Q(\mem[7][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _801_ (
    .CLK(wr_clk),
    .D(_075_),
    .Q(\mem[7][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _802_ (
    .CLK(wr_clk),
    .D(_076_),
    .Q(\mem[7][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _803_ (
    .CLK(wr_clk),
    .D(_077_),
    .Q(\mem[7][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _804_ (
    .CLK(wr_clk),
    .D(_078_),
    .Q(\mem[7][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _805_ (
    .CLK(wr_clk),
    .D(_079_),
    .Q(\mem[7][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _806_ (
    .CLK(wr_clk),
    .D(_080_),
    .Q(\mem[6][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _807_ (
    .CLK(wr_clk),
    .D(_081_),
    .Q(\mem[6][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _808_ (
    .CLK(wr_clk),
    .D(_082_),
    .Q(\mem[6][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _809_ (
    .CLK(wr_clk),
    .D(_083_),
    .Q(\mem[6][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _810_ (
    .CLK(wr_clk),
    .D(_084_),
    .Q(\mem[6][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _811_ (
    .CLK(wr_clk),
    .D(_085_),
    .Q(\mem[6][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _812_ (
    .CLK(wr_clk),
    .D(_086_),
    .Q(\mem[6][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _813_ (
    .CLK(wr_clk),
    .D(_087_),
    .Q(\mem[6][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _814_ (
    .CLK(wr_clk),
    .D(_088_),
    .Q(\mem[2][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _815_ (
    .CLK(wr_clk),
    .D(_089_),
    .Q(\mem[2][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _816_ (
    .CLK(wr_clk),
    .D(_090_),
    .Q(\mem[2][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _817_ (
    .CLK(wr_clk),
    .D(_091_),
    .Q(\mem[2][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _818_ (
    .CLK(wr_clk),
    .D(_092_),
    .Q(\mem[2][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _819_ (
    .CLK(wr_clk),
    .D(_093_),
    .Q(\mem[2][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _820_ (
    .CLK(wr_clk),
    .D(_094_),
    .Q(\mem[2][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _821_ (
    .CLK(wr_clk),
    .D(_095_),
    .Q(\mem[2][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _822_ (
    .CLK(wr_clk),
    .D(_096_),
    .Q(\mem[3][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _823_ (
    .CLK(wr_clk),
    .D(_097_),
    .Q(\mem[3][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _824_ (
    .CLK(wr_clk),
    .D(_098_),
    .Q(\mem[3][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _825_ (
    .CLK(wr_clk),
    .D(_099_),
    .Q(\mem[3][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _826_ (
    .CLK(wr_clk),
    .D(_100_),
    .Q(\mem[3][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _827_ (
    .CLK(wr_clk),
    .D(_101_),
    .Q(\mem[3][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _828_ (
    .CLK(wr_clk),
    .D(_102_),
    .Q(\mem[3][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _829_ (
    .CLK(wr_clk),
    .D(_103_),
    .Q(\mem[3][7] )
  );
  sky130_fd_sc_hd__dfstp_2 _830_ (
    .CLK(rd_clk),
    .D(empty_next),
    .Q(empty),
    .SET_B(arst_n)
  );
  sky130_fd_sc_hd__dfxtp_2 _831_ (
    .CLK(wr_clk),
    .D(_104_),
    .Q(\mem[5][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _832_ (
    .CLK(wr_clk),
    .D(_105_),
    .Q(\mem[5][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _833_ (
    .CLK(wr_clk),
    .D(_106_),
    .Q(\mem[5][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _834_ (
    .CLK(wr_clk),
    .D(_107_),
    .Q(\mem[5][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _835_ (
    .CLK(wr_clk),
    .D(_108_),
    .Q(\mem[5][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _836_ (
    .CLK(wr_clk),
    .D(_109_),
    .Q(\mem[5][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _837_ (
    .CLK(wr_clk),
    .D(_110_),
    .Q(\mem[5][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _838_ (
    .CLK(wr_clk),
    .D(_111_),
    .Q(\mem[5][7] )
  );
  sky130_fd_sc_hd__dfstp_2 _839_ (
    .CLK(rd_clk),
    .D(aempty_next),
    .Q(aempty),
    .SET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _840_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[0] ),
    .Q(\rd_bin[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _841_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[1] ),
    .Q(\rd_bin[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _842_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[2] ),
    .Q(\rd_bin[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _843_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[3] ),
    .Q(\rd_bin[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _844_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[4] ),
    .Q(\rd_bin[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _845_ (
    .CLK(rd_clk),
    .D(\rd_gray_next[0] ),
    .Q(\rd_gray[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _846_ (
    .CLK(rd_clk),
    .D(\rd_gray_next[1] ),
    .Q(\rd_gray[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _847_ (
    .CLK(rd_clk),
    .D(\rd_gray_next[2] ),
    .Q(\rd_gray[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _848_ (
    .CLK(rd_clk),
    .D(\rd_gray_next[3] ),
    .Q(\rd_gray[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _849_ (
    .CLK(wr_clk),
    .D(full_next),
    .Q(full),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _850_ (
    .CLK(wr_clk),
    .D(afull_next),
    .Q(afull),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _851_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[0] ),
    .Q(\wr_bin[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _852_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[1] ),
    .Q(\wr_bin[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _853_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[2] ),
    .Q(\wr_bin[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _854_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[3] ),
    .Q(\wr_bin[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _855_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[4] ),
    .Q(\wr_bin[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfxtp_2 _856_ (
    .CLK(wr_clk),
    .D(_112_),
    .Q(\mem[4][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _857_ (
    .CLK(wr_clk),
    .D(_113_),
    .Q(\mem[4][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _858_ (
    .CLK(wr_clk),
    .D(_114_),
    .Q(\mem[4][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _859_ (
    .CLK(wr_clk),
    .D(_115_),
    .Q(\mem[4][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _860_ (
    .CLK(wr_clk),
    .D(_116_),
    .Q(\mem[4][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _861_ (
    .CLK(wr_clk),
    .D(_117_),
    .Q(\mem[4][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _862_ (
    .CLK(wr_clk),
    .D(_118_),
    .Q(\mem[4][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _863_ (
    .CLK(wr_clk),
    .D(_119_),
    .Q(\mem[4][7] )
  );
  sky130_fd_sc_hd__dfrtp_2 _864_ (
    .CLK(wr_clk),
    .D(\wr_gray_next[0] ),
    .Q(\wr_gray[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _865_ (
    .CLK(wr_clk),
    .D(\wr_gray_next[1] ),
    .Q(\wr_gray[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _866_ (
    .CLK(wr_clk),
    .D(\wr_gray_next[2] ),
    .Q(\wr_gray[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _867_ (
    .CLK(wr_clk),
    .D(\wr_gray_next[3] ),
    .Q(\wr_gray[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _868_ (
    .CLK(rd_clk),
    .D(\wr_gray[0] ),
    .Q(\wr_gray_sync1[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _869_ (
    .CLK(rd_clk),
    .D(\wr_gray[1] ),
    .Q(\wr_gray_sync1[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _870_ (
    .CLK(rd_clk),
    .D(\wr_gray[2] ),
    .Q(\wr_gray_sync1[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _871_ (
    .CLK(rd_clk),
    .D(\wr_gray[3] ),
    .Q(\wr_gray_sync1[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _872_ (
    .CLK(rd_clk),
    .D(\wr_bin[4] ),
    .Q(\wr_gray_sync1[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _873_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[0] ),
    .Q(\wr_gray_sync2[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _874_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[1] ),
    .Q(\wr_gray_sync2[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _875_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[2] ),
    .Q(\wr_gray_sync2[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _876_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[3] ),
    .Q(\wr_gray_sync2[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _877_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[4] ),
    .Q(\wr_bin_sync[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _878_ (
    .CLK(wr_clk),
    .D(\rd_gray[0] ),
    .Q(\rd_gray_sync1[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _879_ (
    .CLK(wr_clk),
    .D(\rd_gray[1] ),
    .Q(\rd_gray_sync1[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _880_ (
    .CLK(wr_clk),
    .D(\rd_gray[2] ),
    .Q(\rd_gray_sync1[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _881_ (
    .CLK(wr_clk),
    .D(\rd_gray[3] ),
    .Q(\rd_gray_sync1[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _882_ (
    .CLK(wr_clk),
    .D(\rd_bin[4] ),
    .Q(\rd_gray_sync1[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _883_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[0] ),
    .Q(\full_compare[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _884_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[1] ),
    .Q(\full_compare[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _885_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[2] ),
    .Q(\full_compare[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _886_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[3] ),
    .Q(\rd_gray_sync2[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _887_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[4] ),
    .Q(\rd_bin_sync[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfxtp_2 _888_ (
    .CLK(wr_clk),
    .D(_120_),
    .Q(\mem[15][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _889_ (
    .CLK(wr_clk),
    .D(_121_),
    .Q(\mem[15][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _890_ (
    .CLK(wr_clk),
    .D(_122_),
    .Q(\mem[15][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _891_ (
    .CLK(wr_clk),
    .D(_123_),
    .Q(\mem[15][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _892_ (
    .CLK(wr_clk),
    .D(_124_),
    .Q(\mem[15][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _893_ (
    .CLK(wr_clk),
    .D(_125_),
    .Q(\mem[15][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _894_ (
    .CLK(wr_clk),
    .D(_126_),
    .Q(\mem[15][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _895_ (
    .CLK(wr_clk),
    .D(_127_),
    .Q(\mem[15][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _896_ (
    .CLK(wr_clk),
    .D(_128_),
    .Q(\mem[9][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _897_ (
    .CLK(wr_clk),
    .D(_129_),
    .Q(\mem[9][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _898_ (
    .CLK(wr_clk),
    .D(_130_),
    .Q(\mem[9][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _899_ (
    .CLK(wr_clk),
    .D(_131_),
    .Q(\mem[9][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _900_ (
    .CLK(wr_clk),
    .D(_132_),
    .Q(\mem[9][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _901_ (
    .CLK(wr_clk),
    .D(_133_),
    .Q(\mem[9][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _902_ (
    .CLK(wr_clk),
    .D(_134_),
    .Q(\mem[9][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _903_ (
    .CLK(wr_clk),
    .D(_135_),
    .Q(\mem[9][7] )
  );
endmodule
