/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module async_fifo(wr_clk, rd_clk, arst_n, wr_en, wr_data, rd_en, rd_data, afull_threshold, aempty_threshold, full, empty, afull, aempty);
  wire [3:0] _000_;
  wire [7:0] _001_;
  wire [7:0] _002_;
  wire [7:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire [7:0] _034_;
  wire [7:0] _035_;
  wire [7:0] _036_;
  wire [7:0] _037_;
  wire [7:0] _038_;
  wire [7:0] _039_;
  wire [7:0] _040_;
  wire [7:0] _041_;
  wire [7:0] _042_;
  wire [7:0] _043_;
  wire [7:0] _044_;
  wire [7:0] _045_;
  wire [7:0] _046_;
  wire [7:0] _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  output aempty;
  reg aempty;
  wire aempty_next;
  input [4:0] aempty_threshold;
  wire [4:0] aempty_threshold;
  output afull;
  reg afull;
  wire afull_next;
  input [4:0] afull_threshold;
  wire [4:0] afull_threshold;
  input arst_n;
  wire arst_n;
  output empty;
  reg empty;
  wire empty_next;
  output full;
  reg full;
  wire [4:0] full_compare;
  wire full_next;
  wire [4:0] \gray_to_binary$func$async_fifo.v:175$4.gray ;
  wire [31:0] \gray_to_binary$func$async_fifo.v:175$4.i ;
  wire [4:0] \gray_to_binary$func$async_fifo.v:178$5.gray ;
  wire [31:0] \gray_to_binary$func$async_fifo.v:178$5.i ;
  reg [7:0] \mem[0] ;
  reg [7:0] \mem[10] ;
  reg [7:0] \mem[11] ;
  reg [7:0] \mem[12] ;
  reg [7:0] \mem[13] ;
  reg [7:0] \mem[14] ;
  reg [7:0] \mem[15] ;
  reg [7:0] \mem[1] ;
  reg [7:0] \mem[2] ;
  reg [7:0] \mem[3] ;
  reg [7:0] \mem[4] ;
  reg [7:0] \mem[5] ;
  reg [7:0] \mem[6] ;
  reg [7:0] \mem[7] ;
  reg [7:0] \mem[8] ;
  reg [7:0] \mem[9] ;
  reg [4:0] rd_bin;
  wire [4:0] rd_bin_next;
  wire [4:0] rd_bin_sync;
  input rd_clk;
  wire rd_clk;
  output [7:0] rd_data;
  reg [7:0] rd_data;
  input rd_en;
  wire rd_en;
  reg [4:0] rd_gray;
  wire [4:0] rd_gray_next;
  reg [4:0] rd_gray_sync1;
  reg [4:0] rd_gray_sync2;
  wire [4:0] read_count;
  wire read_do;
  reg [4:0] wr_bin;
  wire [4:0] wr_bin_next;
  wire [4:0] wr_bin_sync;
  input wr_clk;
  wire wr_clk;
  input [7:0] wr_data;
  wire [7:0] wr_data;
  input wr_en;
  wire wr_en;
  reg [4:0] wr_gray;
  wire [4:0] wr_gray_next;
  reg [4:0] wr_gray_sync1;
  reg [4:0] wr_gray_sync2;
  wire [4:0] write_count;
  wire write_do;
  always @(posedge rd_clk, negedge arst_n)
    if (!arst_n) rd_data <= 8'h00;
    else if (read_do) rd_data <= _003_;
  assign wr_bin_next = wr_bin + write_do;
  assign rd_bin_next = rd_bin + read_do;
  always @(posedge wr_clk)
    if (_063_) \mem[9]  <= _001_;
  always @(posedge wr_clk)
    if (_062_) \mem[8]  <= _001_;
  always @(posedge wr_clk)
    if (_061_) \mem[7]  <= _001_;
  always @(posedge wr_clk)
    if (_060_) \mem[6]  <= _001_;
  always @(posedge wr_clk)
    if (_059_) \mem[5]  <= _001_;
  always @(posedge wr_clk)
    if (_058_) \mem[4]  <= _001_;
  always @(posedge wr_clk)
    if (_057_) \mem[3]  <= _001_;
  always @(posedge wr_clk)
    if (_056_) \mem[2]  <= _001_;
  always @(posedge wr_clk)
    if (_055_) \mem[1]  <= _001_;
  always @(posedge wr_clk)
    if (_054_) \mem[15]  <= _001_;
  always @(posedge wr_clk)
    if (_053_) \mem[14]  <= _001_;
  always @(posedge wr_clk)
    if (_052_) \mem[13]  <= _001_;
  always @(posedge wr_clk)
    if (_051_) \mem[12]  <= _001_;
  always @(posedge wr_clk)
    if (_050_) \mem[11]  <= _001_;
  always @(posedge wr_clk)
    if (_049_) \mem[10]  <= _001_;
  always @(posedge wr_clk)
    if (_048_) \mem[0]  <= _001_;
  assign _028_ = ~ _000_[0];
  assign _029_ = ~ _000_[1];
  assign _030_ = ~ _000_[2];
  assign _031_ = ~ _000_[3];
  assign _004_ = _028_ & _029_;
  assign _005_ = _030_ & _031_;
  assign _006_ = _004_ & _005_;
  assign _007_ = _000_[0] & _029_;
  assign _008_ = _007_ & _005_;
  assign _009_ = _028_ & _000_[1];
  assign _010_ = _009_ & _005_;
  assign _011_ = _000_[0] & _000_[1];
  assign _012_ = _011_ & _005_;
  assign _013_ = _000_[2] & _031_;
  assign _014_ = _004_ & _013_;
  assign _015_ = _007_ & _013_;
  assign _016_ = _009_ & _013_;
  assign _017_ = _011_ & _013_;
  assign _018_ = _030_ & _000_[3];
  assign _019_ = _004_ & _018_;
  assign _020_ = _007_ & _018_;
  assign _021_ = _009_ & _018_;
  assign _022_ = _011_ & _018_;
  assign _023_ = _000_[2] & _000_[3];
  assign _024_ = _004_ & _023_;
  assign _025_ = _007_ & _023_;
  assign _026_ = _009_ & _023_;
  assign _027_ = _011_ & _023_;
  assign full_next = wr_gray_next == { full_compare[4:3], rd_gray_sync2[2:0] };
  assign empty_next = rd_gray_next == wr_gray_sync2;
  assign afull_next = write_count >= afull_threshold;
  assign aempty_next = read_count <= aempty_threshold;
  assign write_do = wr_en && _032_;
  assign read_do = rd_en && _033_;
  assign _032_ = ! full;
  assign _033_ = ! empty;
  assign _003_ = rd_bin[3] ? _035_ : _034_;
  assign _034_ = rd_bin[2] ? _037_ : _036_;
  assign _035_ = rd_bin[2] ? _039_ : _038_;
  assign _036_ = rd_bin[1] ? _041_ : _040_;
  assign _037_ = rd_bin[1] ? _043_ : _042_;
  assign _038_ = rd_bin[1] ? _045_ : _044_;
  assign _039_ = rd_bin[1] ? _047_ : _046_;
  assign _040_ = rd_bin[0] ? \mem[1]  : \mem[0] ;
  assign _041_ = rd_bin[0] ? \mem[3]  : \mem[2] ;
  assign _042_ = rd_bin[0] ? \mem[5]  : \mem[4] ;
  assign _043_ = rd_bin[0] ? \mem[7]  : \mem[6] ;
  assign _044_ = rd_bin[0] ? \mem[9]  : \mem[8] ;
  assign _045_ = rd_bin[0] ? \mem[11]  : \mem[10] ;
  assign _046_ = rd_bin[0] ? \mem[13]  : \mem[12] ;
  assign _047_ = rd_bin[0] ? \mem[15]  : \mem[14] ;
  assign _048_ = _006_ & _002_[7];
  assign _049_ = _021_ & _002_[7];
  assign _050_ = _022_ & _002_[7];
  assign _051_ = _024_ & _002_[7];
  assign _052_ = _025_ & _002_[7];
  assign _053_ = _026_ & _002_[7];
  assign _054_ = _027_ & _002_[7];
  assign _055_ = _008_ & _002_[7];
  assign _056_ = _010_ & _002_[7];
  assign _057_ = _012_ & _002_[7];
  assign _058_ = _014_ & _002_[7];
  assign _059_ = _015_ & _002_[7];
  assign _060_ = _016_ & _002_[7];
  assign _061_ = _017_ & _002_[7];
  assign _062_ = _019_ & _002_[7];
  assign _063_ = _020_ & _002_[7];
  assign full_compare[4:3] = ~ rd_gray_sync2[4:3];
  always @(posedge wr_clk, negedge arst_n)
    if (!arst_n) full <= 1'h0;
    else full <= full_next;
  always @(posedge wr_clk, negedge arst_n)
    if (!arst_n) afull <= 1'h0;
    else afull <= afull_next;
  always @(posedge wr_clk, negedge arst_n)
    if (!arst_n) wr_bin <= 5'h00;
    else wr_bin <= wr_bin_next;
  always @(posedge wr_clk, negedge arst_n)
    if (!arst_n) wr_gray <= 5'h00;
    else wr_gray <= wr_gray_next;
  always @(posedge rd_clk, negedge arst_n)
    if (!arst_n) wr_gray_sync1 <= 5'h00;
    else wr_gray_sync1 <= wr_gray;
  always @(posedge rd_clk, negedge arst_n)
    if (!arst_n) wr_gray_sync2 <= 5'h00;
    else wr_gray_sync2 <= wr_gray_sync1;
  always @(posedge wr_clk, negedge arst_n)
    if (!arst_n) rd_gray_sync1 <= 5'h00;
    else rd_gray_sync1 <= rd_gray;
  always @(posedge wr_clk, negedge arst_n)
    if (!arst_n) rd_gray_sync2 <= 5'h00;
    else rd_gray_sync2 <= rd_gray_sync1;
  always @(posedge rd_clk, negedge arst_n)
    if (!arst_n) empty <= 1'h1;
    else empty <= empty_next;
  always @(posedge rd_clk, negedge arst_n)
    if (!arst_n) aempty <= 1'h1;
    else aempty <= aempty_next;
  always @(posedge rd_clk, negedge arst_n)
    if (!arst_n) rd_bin <= 5'h00;
    else rd_bin <= rd_bin_next;
  always @(posedge rd_clk, negedge arst_n)
    if (!arst_n) rd_gray <= 5'h00;
    else rd_gray <= rd_gray_next;
  assign _002_[7] = write_do ? 1'h1 : 1'h0;
  assign _001_ = write_do ? wr_data : 8'hxx;
  assign _000_ = write_do ? wr_bin[3:0] : 4'hx;
  assign write_count = wr_bin - { rd_gray_sync2[4], rd_bin_sync[3:0] };
  assign read_count = { wr_gray_sync2[4], wr_bin_sync[3:0] } - rd_bin;
  assign rd_bin_sync[3] = rd_gray_sync2[4] ^ rd_gray_sync2[3];
  assign rd_bin_sync[2] = rd_bin_sync[3] ^ rd_gray_sync2[2];
  assign rd_bin_sync[1] = rd_bin_sync[2] ^ rd_gray_sync2[1];
  assign rd_bin_sync[0] = rd_bin_sync[1] ^ rd_gray_sync2[0];
  assign wr_bin_sync[3] = wr_gray_sync2[4] ^ wr_gray_sync2[3];
  assign wr_bin_sync[2] = wr_bin_sync[3] ^ wr_gray_sync2[2];
  assign wr_bin_sync[1] = wr_bin_sync[2] ^ wr_gray_sync2[1];
  assign wr_bin_sync[0] = wr_bin_sync[1] ^ wr_gray_sync2[0];
  assign wr_gray_next = wr_bin_next ^ { 1'h0, wr_bin_next[4:1] };
  assign rd_gray_next = rd_bin_next ^ { 1'h0, rd_bin_next[4:1] };
  assign _002_[6:0] = { _002_[7], _002_[7], _002_[7], _002_[7], _002_[7], _002_[7], _002_[7] };
  assign full_compare[2:0] = rd_gray_sync2[2:0];
  assign \gray_to_binary$func$async_fifo.v:175$4.gray  = 5'hxx;
  assign \gray_to_binary$func$async_fifo.v:175$4.i  = 32'hxxxxxxxx;
  assign \gray_to_binary$func$async_fifo.v:178$5.gray  = 5'hxx;
  assign \gray_to_binary$func$async_fifo.v:178$5.i  = 32'hxxxxxxxx;
  assign rd_bin_sync[4] = rd_gray_sync2[4];
  assign wr_bin_sync[4] = wr_gray_sync2[4];
endmodule
