/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module async_fifo(wr_clk, rd_clk, arst_n, wr_en, wr_data, rd_en, rd_data, afull_threshold, aempty_threshold, full, empty, afull, aempty);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  output aempty;
  wire aempty;
  wire aempty_next;
  input [4:0] aempty_threshold;
  wire [4:0] aempty_threshold;
  output afull;
  wire afull;
  wire afull_next;
  input [4:0] afull_threshold;
  wire [4:0] afull_threshold;
  input arst_n;
  wire arst_n;
  output empty;
  wire empty;
  wire empty_next;
  output full;
  wire full;
  wire \full_compare[0] ;
  wire \full_compare[1] ;
  wire \full_compare[2] ;
  wire full_next;
  wire \mem[0][0] ;
  wire \mem[0][1] ;
  wire \mem[0][2] ;
  wire \mem[0][3] ;
  wire \mem[0][4] ;
  wire \mem[0][5] ;
  wire \mem[0][6] ;
  wire \mem[0][7] ;
  wire \mem[10][0] ;
  wire \mem[10][1] ;
  wire \mem[10][2] ;
  wire \mem[10][3] ;
  wire \mem[10][4] ;
  wire \mem[10][5] ;
  wire \mem[10][6] ;
  wire \mem[10][7] ;
  wire \mem[11][0] ;
  wire \mem[11][1] ;
  wire \mem[11][2] ;
  wire \mem[11][3] ;
  wire \mem[11][4] ;
  wire \mem[11][5] ;
  wire \mem[11][6] ;
  wire \mem[11][7] ;
  wire \mem[12][0] ;
  wire \mem[12][1] ;
  wire \mem[12][2] ;
  wire \mem[12][3] ;
  wire \mem[12][4] ;
  wire \mem[12][5] ;
  wire \mem[12][6] ;
  wire \mem[12][7] ;
  wire \mem[13][0] ;
  wire \mem[13][1] ;
  wire \mem[13][2] ;
  wire \mem[13][3] ;
  wire \mem[13][4] ;
  wire \mem[13][5] ;
  wire \mem[13][6] ;
  wire \mem[13][7] ;
  wire \mem[14][0] ;
  wire \mem[14][1] ;
  wire \mem[14][2] ;
  wire \mem[14][3] ;
  wire \mem[14][4] ;
  wire \mem[14][5] ;
  wire \mem[14][6] ;
  wire \mem[14][7] ;
  wire \mem[15][0] ;
  wire \mem[15][1] ;
  wire \mem[15][2] ;
  wire \mem[15][3] ;
  wire \mem[15][4] ;
  wire \mem[15][5] ;
  wire \mem[15][6] ;
  wire \mem[15][7] ;
  wire \mem[1][0] ;
  wire \mem[1][1] ;
  wire \mem[1][2] ;
  wire \mem[1][3] ;
  wire \mem[1][4] ;
  wire \mem[1][5] ;
  wire \mem[1][6] ;
  wire \mem[1][7] ;
  wire \mem[2][0] ;
  wire \mem[2][1] ;
  wire \mem[2][2] ;
  wire \mem[2][3] ;
  wire \mem[2][4] ;
  wire \mem[2][5] ;
  wire \mem[2][6] ;
  wire \mem[2][7] ;
  wire \mem[3][0] ;
  wire \mem[3][1] ;
  wire \mem[3][2] ;
  wire \mem[3][3] ;
  wire \mem[3][4] ;
  wire \mem[3][5] ;
  wire \mem[3][6] ;
  wire \mem[3][7] ;
  wire \mem[4][0] ;
  wire \mem[4][1] ;
  wire \mem[4][2] ;
  wire \mem[4][3] ;
  wire \mem[4][4] ;
  wire \mem[4][5] ;
  wire \mem[4][6] ;
  wire \mem[4][7] ;
  wire \mem[5][0] ;
  wire \mem[5][1] ;
  wire \mem[5][2] ;
  wire \mem[5][3] ;
  wire \mem[5][4] ;
  wire \mem[5][5] ;
  wire \mem[5][6] ;
  wire \mem[5][7] ;
  wire \mem[6][0] ;
  wire \mem[6][1] ;
  wire \mem[6][2] ;
  wire \mem[6][3] ;
  wire \mem[6][4] ;
  wire \mem[6][5] ;
  wire \mem[6][6] ;
  wire \mem[6][7] ;
  wire \mem[7][0] ;
  wire \mem[7][1] ;
  wire \mem[7][2] ;
  wire \mem[7][3] ;
  wire \mem[7][4] ;
  wire \mem[7][5] ;
  wire \mem[7][6] ;
  wire \mem[7][7] ;
  wire \mem[8][0] ;
  wire \mem[8][1] ;
  wire \mem[8][2] ;
  wire \mem[8][3] ;
  wire \mem[8][4] ;
  wire \mem[8][5] ;
  wire \mem[8][6] ;
  wire \mem[8][7] ;
  wire \mem[9][0] ;
  wire \mem[9][1] ;
  wire \mem[9][2] ;
  wire \mem[9][3] ;
  wire \mem[9][4] ;
  wire \mem[9][5] ;
  wire \mem[9][6] ;
  wire \mem[9][7] ;
  wire \rd_bin[0] ;
  wire \rd_bin[1] ;
  wire \rd_bin[2] ;
  wire \rd_bin[3] ;
  wire \rd_bin[4] ;
  wire \rd_bin_next[0] ;
  wire \rd_bin_next[1] ;
  wire \rd_bin_next[2] ;
  wire \rd_bin_next[3] ;
  wire \rd_bin_next[4] ;
  wire \rd_bin_sync[4] ;
  input rd_clk;
  wire rd_clk;
  output [7:0] rd_data;
  wire [7:0] rd_data;
  input rd_en;
  wire rd_en;
  wire \rd_gray[0] ;
  wire \rd_gray[1] ;
  wire \rd_gray[2] ;
  wire \rd_gray[3] ;
  wire \rd_gray_next[0] ;
  wire \rd_gray_next[1] ;
  wire \rd_gray_next[2] ;
  wire \rd_gray_next[3] ;
  wire \rd_gray_sync1[0] ;
  wire \rd_gray_sync1[1] ;
  wire \rd_gray_sync1[2] ;
  wire \rd_gray_sync1[3] ;
  wire \rd_gray_sync1[4] ;
  wire \rd_gray_sync2[3] ;
  wire \wr_bin[0] ;
  wire \wr_bin[1] ;
  wire \wr_bin[2] ;
  wire \wr_bin[3] ;
  wire \wr_bin[4] ;
  wire \wr_bin_next[0] ;
  wire \wr_bin_next[1] ;
  wire \wr_bin_next[2] ;
  wire \wr_bin_next[3] ;
  wire \wr_bin_next[4] ;
  wire \wr_bin_sync[4] ;
  input wr_clk;
  wire wr_clk;
  input [7:0] wr_data;
  wire [7:0] wr_data;
  input wr_en;
  wire wr_en;
  wire \wr_gray[0] ;
  wire \wr_gray[1] ;
  wire \wr_gray[2] ;
  wire \wr_gray[3] ;
  wire \wr_gray_next[0] ;
  wire \wr_gray_next[1] ;
  wire \wr_gray_next[2] ;
  wire \wr_gray_next[3] ;
  wire \wr_gray_sync1[0] ;
  wire \wr_gray_sync1[1] ;
  wire \wr_gray_sync1[2] ;
  wire \wr_gray_sync1[3] ;
  wire \wr_gray_sync1[4] ;
  wire \wr_gray_sync2[0] ;
  wire \wr_gray_sync2[1] ;
  wire \wr_gray_sync2[2] ;
  wire \wr_gray_sync2[3] ;
  sky130_fd_sc_hd__mux2_2 _0493_ (
    .A0(\rd_gray_sync2[3] ),
    .A1(\rd_bin_sync[4] ),
    .S(\wr_bin[3] ),
    .X(_0136_)
  );
  sky130_fd_sc_hd__inv_2 _0494_ (
    .A(\rd_bin_sync[4] ),
    .Y(_0137_)
  );
  sky130_fd_sc_hd__mux2_2 _0495_ (
    .A0(_0137_),
    .A1(\rd_gray_sync2[3] ),
    .S(\wr_bin[3] ),
    .X(_0138_)
  );
  sky130_fd_sc_hd__o21a_2 _0496_ (
    .A1(\wr_bin[0] ),
    .A2(\full_compare[0] ),
    .B1(\wr_bin[1] ),
    .X(_0139_)
  );
  sky130_fd_sc_hd__xnor2_4 _0497_ (
    .A(\rd_bin_sync[4] ),
    .B(\rd_gray_sync2[3] ),
    .Y(_0140_)
  );
  sky130_fd_sc_hd__xor2_2 _0498_ (
    .A(\full_compare[2] ),
    .B(_0140_),
    .X(_0141_)
  );
  sky130_fd_sc_hd__mux2_2 _0499_ (
    .A0(_0141_),
    .A1(\wr_bin[2] ),
    .S(\full_compare[1] ),
    .X(_0142_)
  );
  sky130_fd_sc_hd__inv_2 _0500_ (
    .A(\wr_bin[1] ),
    .Y(_0143_)
  );
  sky130_fd_sc_hd__nor2b_2 _0501_ (
    .A(\wr_bin[0] ),
    .B_N(\full_compare[0] ),
    .Y(_0144_)
  );
  sky130_fd_sc_hd__nand2_2 _0502_ (
    .A(_0143_),
    .B(_0144_),
    .Y(_0145_)
  );
  sky130_fd_sc_hd__or2_2 _0503_ (
    .A(\wr_bin[2] ),
    .B(_0145_),
    .X(_0146_)
  );
  sky130_fd_sc_hd__a21o_2 _0504_ (
    .A1(\wr_bin[2] ),
    .A2(_0145_),
    .B1(_0141_),
    .X(_0147_)
  );
  sky130_fd_sc_hd__o211ai_2 _0505_ (
    .A1(_0139_),
    .A2(_0142_),
    .B1(_0146_),
    .C1(_0147_),
    .Y(_0148_)
  );
  sky130_fd_sc_hd__mux2_2 _0506_ (
    .A0(_0136_),
    .A1(_0138_),
    .S(_0148_),
    .X(_0149_)
  );
  sky130_fd_sc_hd__xnor2_2 _0507_ (
    .A(\wr_bin[4] ),
    .B(_0149_),
    .Y(_0150_)
  );
  sky130_fd_sc_hd__xnor2_2 _0508_ (
    .A(\wr_bin[3] ),
    .B(_0140_),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__xnor2_2 _0509_ (
    .A(_0148_),
    .B(_0151_),
    .Y(_0152_)
  );
  sky130_fd_sc_hd__xnor2_2 _0510_ (
    .A(\full_compare[2] ),
    .B(\full_compare[1] ),
    .Y(_0153_)
  );
  sky130_fd_sc_hd__xor2_2 _0511_ (
    .A(_0140_),
    .B(_0153_),
    .X(_0154_)
  );
  sky130_fd_sc_hd__inv_2 _0512_ (
    .A(\wr_bin[0] ),
    .Y(_0155_)
  );
  sky130_fd_sc_hd__and3_2 _0513_ (
    .A(_0155_),
    .B(afull_threshold[1]),
    .C(afull_threshold[0]),
    .X(_0156_)
  );
  sky130_fd_sc_hd__inv_2 _0514_ (
    .A(\full_compare[0] ),
    .Y(_0157_)
  );
  sky130_fd_sc_hd__o211a_2 _0515_ (
    .A1(_0155_),
    .A2(afull_threshold[0]),
    .B1(afull_threshold[1]),
    .C1(_0157_),
    .X(_0158_)
  );
  sky130_fd_sc_hd__a21o_2 _0516_ (
    .A1(_0154_),
    .A2(_0156_),
    .B1(_0158_),
    .X(_0159_)
  );
  sky130_fd_sc_hd__nor2b_2 _0517_ (
    .A(\full_compare[0] ),
    .B_N(afull_threshold[0]),
    .Y(_0160_)
  );
  sky130_fd_sc_hd__a211o_2 _0518_ (
    .A1(\full_compare[0] ),
    .A2(afull_threshold[0]),
    .B1(afull_threshold[1]),
    .C1(_0155_),
    .X(_0161_)
  );
  sky130_fd_sc_hd__xnor2_2 _0519_ (
    .A(_0140_),
    .B(_0153_),
    .Y(_0162_)
  );
  sky130_fd_sc_hd__o211a_2 _0520_ (
    .A1(\wr_bin[0] ),
    .A2(_0160_),
    .B1(_0161_),
    .C1(_0162_),
    .X(_0163_)
  );
  sky130_fd_sc_hd__a21o_2 _0521_ (
    .A1(\full_compare[0] ),
    .A2(afull_threshold[0]),
    .B1(\wr_bin[0] ),
    .X(_0164_)
  );
  sky130_fd_sc_hd__or3_2 _0522_ (
    .A(_0155_),
    .B(afull_threshold[1]),
    .C(_0160_),
    .X(_0165_)
  );
  sky130_fd_sc_hd__a31o_2 _0523_ (
    .A1(_0154_),
    .A2(_0164_),
    .A3(_0165_),
    .B1(_0143_),
    .X(_0166_)
  );
  sky130_fd_sc_hd__o211a_2 _0524_ (
    .A1(_0155_),
    .A2(afull_threshold[0]),
    .B1(afull_threshold[1]),
    .C1(\full_compare[0] ),
    .X(_0167_)
  );
  sky130_fd_sc_hd__a21o_2 _0525_ (
    .A1(_0162_),
    .A2(_0156_),
    .B1(_0167_),
    .X(_0168_)
  );
  sky130_fd_sc_hd__o32a_2 _0526_ (
    .A1(\wr_bin[1] ),
    .A2(_0159_),
    .A3(_0163_),
    .B1(_0166_),
    .B2(_0168_),
    .X(_0169_)
  );
  sky130_fd_sc_hd__nor2_2 _0527_ (
    .A(\full_compare[1] ),
    .B(_0144_),
    .Y(_0170_)
  );
  sky130_fd_sc_hd__o21a_2 _0528_ (
    .A1(_0139_),
    .A2(_0170_),
    .B1(_0141_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__a211o_2 _0529_ (
    .A1(\wr_bin[1] ),
    .A2(\wr_bin[0] ),
    .B1(_0144_),
    .C1(\full_compare[1] ),
    .X(_0172_)
  );
  sky130_fd_sc_hd__o21ai_2 _0530_ (
    .A1(_0141_),
    .A2(_0145_),
    .B1(_0172_),
    .Y(_0173_)
  );
  sky130_fd_sc_hd__o21ai_2 _0531_ (
    .A1(_0171_),
    .A2(_0173_),
    .B1(\wr_bin[2] ),
    .Y(_0174_)
  );
  sky130_fd_sc_hd__or3_2 _0532_ (
    .A(\wr_bin[2] ),
    .B(_0171_),
    .C(_0173_),
    .X(_0175_)
  );
  sky130_fd_sc_hd__a31o_2 _0533_ (
    .A1(_0169_),
    .A2(_0174_),
    .A3(_0175_),
    .B1(afull_threshold[2]),
    .X(_0176_)
  );
  sky130_fd_sc_hd__a21o_2 _0534_ (
    .A1(_0174_),
    .A2(_0175_),
    .B1(_0169_),
    .X(_0177_)
  );
  sky130_fd_sc_hd__a22o_2 _0535_ (
    .A1(afull_threshold[3]),
    .A2(_0152_),
    .B1(_0176_),
    .B2(_0177_),
    .X(_0178_)
  );
  sky130_fd_sc_hd__o221a_2 _0536_ (
    .A1(afull_threshold[4]),
    .A2(_0150_),
    .B1(_0152_),
    .B2(afull_threshold[3]),
    .C1(_0178_),
    .X(_0179_)
  );
  sky130_fd_sc_hd__a21oi_4 _0537_ (
    .A1(afull_threshold[4]),
    .A2(_0150_),
    .B1(_0179_),
    .Y(afull_next)
  );
  sky130_fd_sc_hd__xnor2_4 _0538_ (
    .A(\wr_gray_sync2[3] ),
    .B(\wr_bin_sync[4] ),
    .Y(_0180_)
  );
  sky130_fd_sc_hd__xor2_2 _0539_ (
    .A(\wr_gray_sync2[2] ),
    .B(_0180_),
    .X(_0181_)
  );
  sky130_fd_sc_hd__o2111ai_2 _0540_ (
    .A1(\rd_bin[2] ),
    .A2(_0181_),
    .B1(\wr_gray_sync2[0] ),
    .C1(\rd_bin[0] ),
    .D1(\rd_bin[1] ),
    .Y(_0182_)
  );
  sky130_fd_sc_hd__or3_4 _0541_ (
    .A(\wr_gray_sync2[2] ),
    .B(\wr_gray_sync2[1] ),
    .C(_0180_),
    .X(_0183_)
  );
  sky130_fd_sc_hd__inv_2 _0542_ (
    .A(\wr_gray_sync2[1] ),
    .Y(_0184_)
  );
  sky130_fd_sc_hd__nand3_2 _0543_ (
    .A(\wr_gray_sync2[2] ),
    .B(_0184_),
    .C(_0180_),
    .Y(_0185_)
  );
  sky130_fd_sc_hd__and2b_2 _0544_ (
    .A_N(\wr_gray_sync2[0] ),
    .B(\rd_bin[0] ),
    .X(_0186_)
  );
  sky130_fd_sc_hd__o22a_2 _0545_ (
    .A1(_0184_),
    .A2(\rd_bin[2] ),
    .B1(_0186_),
    .B2(\rd_bin[1] ),
    .X(_0187_)
  );
  sky130_fd_sc_hd__a32oi_2 _0546_ (
    .A1(_0183_),
    .A2(_0185_),
    .A3(_0187_),
    .B1(_0181_),
    .B2(\rd_bin[2] ),
    .Y(_0188_)
  );
  sky130_fd_sc_hd__nand2_2 _0547_ (
    .A(_0182_),
    .B(_0188_),
    .Y(_0189_)
  );
  sky130_fd_sc_hd__or3_2 _0548_ (
    .A(\wr_bin_sync[4] ),
    .B(\rd_bin[3] ),
    .C(_0189_),
    .X(_0190_)
  );
  sky130_fd_sc_hd__inv_2 _0549_ (
    .A(\wr_bin_sync[4] ),
    .Y(_0191_)
  );
  sky130_fd_sc_hd__inv_2 _0550_ (
    .A(\rd_bin[3] ),
    .Y(_0192_)
  );
  sky130_fd_sc_hd__bufinv_8 _0551_ (
    .A(\wr_gray_sync2[3] ),
    .Y(_0193_)
  );
  sky130_fd_sc_hd__a41o_2 _0552_ (
    .A1(\wr_bin_sync[4] ),
    .A2(_0192_),
    .A3(_0182_),
    .A4(_0188_),
    .B1(_0193_),
    .X(_0194_)
  );
  sky130_fd_sc_hd__a21o_2 _0553_ (
    .A1(_0182_),
    .A2(_0188_),
    .B1(_0192_),
    .X(_0195_)
  );
  sky130_fd_sc_hd__mux2_2 _0554_ (
    .A0(_0191_),
    .A1(_0194_),
    .S(_0195_),
    .X(_0196_)
  );
  sky130_fd_sc_hd__and3_4 _0555_ (
    .A(\rd_bin[4] ),
    .B(_0190_),
    .C(_0196_),
    .X(_0197_)
  );
  sky130_fd_sc_hd__a21oi_2 _0556_ (
    .A1(_0190_),
    .A2(_0196_),
    .B1(\rd_bin[4] ),
    .Y(_0198_)
  );
  sky130_fd_sc_hd__o21a_2 _0557_ (
    .A1(_0197_),
    .A2(_0198_),
    .B1(aempty_threshold[4]),
    .X(_0199_)
  );
  sky130_fd_sc_hd__bufinv_8 _0558_ (
    .A(\rd_bin[0] ),
    .Y(_0200_)
  );
  sky130_fd_sc_hd__a21o_2 _0559_ (
    .A1(_0200_),
    .A2(_0181_),
    .B1(_0186_),
    .X(_0201_)
  );
  sky130_fd_sc_hd__nand2_2 _0560_ (
    .A(\wr_gray_sync2[0] ),
    .B(\rd_bin[0] ),
    .Y(_0202_)
  );
  sky130_fd_sc_hd__a21boi_2 _0561_ (
    .A1(_0184_),
    .A2(_0202_),
    .B1_N(\rd_bin[1] ),
    .Y(_0203_)
  );
  sky130_fd_sc_hd__nor2_2 _0562_ (
    .A(\rd_bin[1] ),
    .B(_0186_),
    .Y(_0204_)
  );
  sky130_fd_sc_hd__mux2_2 _0563_ (
    .A0(_0203_),
    .A1(_0204_),
    .S(_0181_),
    .X(_0205_)
  );
  sky130_fd_sc_hd__a21oi_4 _0564_ (
    .A1(\wr_gray_sync2[1] ),
    .A2(_0201_),
    .B1(_0205_),
    .Y(_0206_)
  );
  sky130_fd_sc_hd__xnor2_4 _0565_ (
    .A(\rd_bin[2] ),
    .B(_0206_),
    .Y(_0207_)
  );
  sky130_fd_sc_hd__or3_2 _0566_ (
    .A(\wr_gray_sync2[0] ),
    .B(\rd_bin[0] ),
    .C(\rd_bin[1] ),
    .X(_0208_)
  );
  sky130_fd_sc_hd__xnor2_2 _0567_ (
    .A(\wr_gray_sync2[2] ),
    .B(\wr_gray_sync2[1] ),
    .Y(_0209_)
  );
  sky130_fd_sc_hd__xnor2_2 _0568_ (
    .A(_0180_),
    .B(_0209_),
    .Y(_0210_)
  );
  sky130_fd_sc_hd__a21boi_4 _0569_ (
    .A1(_0202_),
    .A2(_0208_),
    .B1_N(_0210_),
    .Y(_0211_)
  );
  sky130_fd_sc_hd__inv_2 _0570_ (
    .A(\wr_gray_sync2[0] ),
    .Y(_0212_)
  );
  sky130_fd_sc_hd__nor2_2 _0571_ (
    .A(_0212_),
    .B(\rd_bin[1] ),
    .Y(_0213_)
  );
  sky130_fd_sc_hd__and2_2 _0572_ (
    .A(_0212_),
    .B(\rd_bin[1] ),
    .X(_0214_)
  );
  sky130_fd_sc_hd__o21a_2 _0573_ (
    .A1(_0213_),
    .A2(_0214_),
    .B1(aempty_threshold[1]),
    .X(_0215_)
  );
  sky130_fd_sc_hd__and3_2 _0574_ (
    .A(\wr_gray_sync2[0] ),
    .B(_0200_),
    .C(\rd_bin[1] ),
    .X(_0216_)
  );
  sky130_fd_sc_hd__o21ba_2 _0575_ (
    .A1(_0186_),
    .A2(_0216_),
    .B1_N(_0210_),
    .X(_0217_)
  );
  sky130_fd_sc_hd__or4_4 _0576_ (
    .A(aempty_threshold[0]),
    .B(_0211_),
    .C(_0215_),
    .D(_0217_),
    .X(_0218_)
  );
  sky130_fd_sc_hd__or3_2 _0577_ (
    .A(\rd_bin[0] ),
    .B(\rd_bin[1] ),
    .C(aempty_threshold[1]),
    .X(_0219_)
  );
  sky130_fd_sc_hd__or2b_2 _0578_ (
    .A(\rd_bin[0] ),
    .B_N(\rd_bin[1] ),
    .X(_0220_)
  );
  sky130_fd_sc_hd__or2_2 _0579_ (
    .A(aempty_threshold[1]),
    .B(_0220_),
    .X(_0221_)
  );
  sky130_fd_sc_hd__mux2_2 _0580_ (
    .A0(_0219_),
    .A1(_0221_),
    .S(_0210_),
    .X(_0222_)
  );
  sky130_fd_sc_hd__o41a_2 _0581_ (
    .A1(_0200_),
    .A2(aempty_threshold[1]),
    .A3(_0213_),
    .A4(_0214_),
    .B1(_0222_),
    .X(_0223_)
  );
  sky130_fd_sc_hd__and3_4 _0582_ (
    .A(aempty_threshold[2]),
    .B(_0218_),
    .C(_0223_),
    .X(_0224_)
  );
  sky130_fd_sc_hd__a21o_2 _0583_ (
    .A1(aempty_threshold[2]),
    .A2(_0207_),
    .B1(_0224_),
    .X(_0225_)
  );
  sky130_fd_sc_hd__xnor2_2 _0584_ (
    .A(\rd_bin[3] ),
    .B(_0180_),
    .Y(_0226_)
  );
  sky130_fd_sc_hd__xnor2_2 _0585_ (
    .A(_0189_),
    .B(_0226_),
    .Y(_0227_)
  );
  sky130_fd_sc_hd__a31o_2 _0586_ (
    .A1(_0218_),
    .A2(_0223_),
    .A3(_0207_),
    .B1(_0227_),
    .X(_0228_)
  );
  sky130_fd_sc_hd__a21o_2 _0587_ (
    .A1(_0218_),
    .A2(_0223_),
    .B1(aempty_threshold[2]),
    .X(_0229_)
  );
  sky130_fd_sc_hd__o211a_4 _0588_ (
    .A1(_0224_),
    .A2(_0207_),
    .B1(_0229_),
    .C1(_0227_),
    .X(_0230_)
  );
  sky130_fd_sc_hd__o22a_2 _0589_ (
    .A1(_0225_),
    .A2(_0228_),
    .B1(_0230_),
    .B2(aempty_threshold[3]),
    .X(_0231_)
  );
  sky130_fd_sc_hd__or3_4 _0590_ (
    .A(aempty_threshold[4]),
    .B(_0197_),
    .C(_0198_),
    .X(_0232_)
  );
  sky130_fd_sc_hd__o21a_4 _0591_ (
    .A1(_0199_),
    .A2(_0231_),
    .B1(_0232_),
    .X(aempty_next)
  );
  sky130_fd_sc_hd__nor2b_2 _0592_ (
    .A(full),
    .B_N(wr_en),
    .Y(_0233_)
  );
  sky130_fd_sc_hd__xnor2_2 _0593_ (
    .A(_0155_),
    .B(_0233_),
    .Y(\wr_bin_next[0] )
  );
  sky130_fd_sc_hd__nand2b_2 _0594_ (
    .A_N(full),
    .B(wr_en),
    .Y(_0234_)
  );
  sky130_fd_sc_hd__nor2_2 _0595_ (
    .A(_0155_),
    .B(_0234_),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__nand2_2 _0596_ (
    .A(_0143_),
    .B(_0235_),
    .Y(_0236_)
  );
  sky130_fd_sc_hd__nand2_2 _0597_ (
    .A(\wr_bin[0] ),
    .B(_0233_),
    .Y(_0237_)
  );
  sky130_fd_sc_hd__nand2_2 _0598_ (
    .A(\wr_bin[1] ),
    .B(_0237_),
    .Y(_0238_)
  );
  sky130_fd_sc_hd__nand2_2 _0599_ (
    .A(_0236_),
    .B(_0238_),
    .Y(\wr_bin_next[1] )
  );
  sky130_fd_sc_hd__nor2_2 _0600_ (
    .A(_0143_),
    .B(_0237_),
    .Y(_0239_)
  );
  sky130_fd_sc_hd__xor2_2 _0601_ (
    .A(\wr_bin[2] ),
    .B(_0239_),
    .X(\wr_bin_next[2] )
  );
  sky130_fd_sc_hd__a21oi_2 _0602_ (
    .A1(\wr_bin[2] ),
    .A2(_0239_),
    .B1(\wr_bin[3] ),
    .Y(_0240_)
  );
  sky130_fd_sc_hd__xnor2_2 _0603_ (
    .A(\wr_bin[4] ),
    .B(_0240_),
    .Y(\wr_gray_next[3] )
  );
  sky130_fd_sc_hd__xor2_2 _0604_ (
    .A(\rd_gray_sync2[3] ),
    .B(\wr_gray_next[3] ),
    .X(_0241_)
  );
  sky130_fd_sc_hd__and2b_2 _0605_ (
    .A_N(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .X(_0242_)
  );
  sky130_fd_sc_hd__nor2_2 _0606_ (
    .A(\full_compare[2] ),
    .B(\wr_bin[2] ),
    .Y(_0243_)
  );
  sky130_fd_sc_hd__mux2_2 _0607_ (
    .A0(\full_compare[2] ),
    .A1(_0243_),
    .S(\wr_bin[3] ),
    .X(_0244_)
  );
  sky130_fd_sc_hd__xnor2_2 _0608_ (
    .A(\full_compare[2] ),
    .B(\wr_bin[2] ),
    .Y(_0245_)
  );
  sky130_fd_sc_hd__nand2_2 _0609_ (
    .A(\wr_bin[3] ),
    .B(_0245_),
    .Y(_0246_)
  );
  sky130_fd_sc_hd__o221a_2 _0610_ (
    .A1(\wr_bin[3] ),
    .A2(_0243_),
    .B1(_0237_),
    .B2(_0143_),
    .C1(_0246_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__a221o_2 _0611_ (
    .A1(\full_compare[2] ),
    .A2(_0242_),
    .B1(_0244_),
    .B2(_0239_),
    .C1(_0247_),
    .X(_0248_)
  );
  sky130_fd_sc_hd__and4b_2 _0612_ (
    .A_N(\full_compare[2] ),
    .B(\wr_bin[2] ),
    .C(_0239_),
    .D(\wr_bin[3] ),
    .X(_0249_)
  );
  sky130_fd_sc_hd__xnor2_2 _0613_ (
    .A(\wr_bin[4] ),
    .B(\rd_bin_sync[4] ),
    .Y(_0250_)
  );
  sky130_fd_sc_hd__mux2_2 _0614_ (
    .A0(_0248_),
    .A1(_0249_),
    .S(_0250_),
    .X(_0251_)
  );
  sky130_fd_sc_hd__xor2_2 _0615_ (
    .A(\wr_bin[2] ),
    .B(\full_compare[1] ),
    .X(_0252_)
  );
  sky130_fd_sc_hd__mux2_2 _0616_ (
    .A0(\wr_bin_next[0] ),
    .A1(_0235_),
    .S(_0252_),
    .X(_0253_)
  );
  sky130_fd_sc_hd__or4_2 _0617_ (
    .A(\wr_bin[0] ),
    .B(\full_compare[0] ),
    .C(_0233_),
    .D(_0252_),
    .X(_0254_)
  );
  sky130_fd_sc_hd__a21bo_2 _0618_ (
    .A1(\full_compare[0] ),
    .A2(_0253_),
    .B1_N(_0254_),
    .X(_0255_)
  );
  sky130_fd_sc_hd__nor2_2 _0619_ (
    .A(\wr_bin[0] ),
    .B(_0233_),
    .Y(_0256_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _0620_ (
    .A1_N(\full_compare[0] ),
    .A2_N(_0256_),
    .B1(_0234_),
    .B2(_0144_),
    .X(_0257_)
  );
  sky130_fd_sc_hd__and3_2 _0621_ (
    .A(\wr_bin[1] ),
    .B(_0252_),
    .C(_0257_),
    .X(_0258_)
  );
  sky130_fd_sc_hd__a21o_2 _0622_ (
    .A1(_0143_),
    .A2(_0255_),
    .B1(_0258_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__and3_2 _0623_ (
    .A(_0241_),
    .B(_0251_),
    .C(_0259_),
    .X(_0260_)
  );
  sky130_fd_sc_hd__buf_2 _0624_ (
    .A(_0260_),
    .X(full_next)
  );
  sky130_fd_sc_hd__nor2b_2 _0625_ (
    .A(empty),
    .B_N(rd_en),
    .Y(_0261_)
  );
  sky130_fd_sc_hd__xnor2_2 _0626_ (
    .A(_0200_),
    .B(_0261_),
    .Y(\rd_bin_next[0] )
  );
  sky130_fd_sc_hd__nand2_2 _0627_ (
    .A(\rd_bin[0] ),
    .B(_0261_),
    .Y(_0262_)
  );
  sky130_fd_sc_hd__xnor2_2 _0628_ (
    .A(\rd_bin[1] ),
    .B(_0262_),
    .Y(\rd_bin_next[1] )
  );
  sky130_fd_sc_hd__and3_2 _0629_ (
    .A(\rd_bin[0] ),
    .B(\rd_bin[1] ),
    .C(_0261_),
    .X(_0263_)
  );
  sky130_fd_sc_hd__buf_2 _0630_ (
    .A(_0263_),
    .X(_0264_)
  );
  sky130_fd_sc_hd__xor2_2 _0631_ (
    .A(\rd_bin[2] ),
    .B(_0264_),
    .X(\rd_bin_next[2] )
  );
  sky130_fd_sc_hd__nand2_2 _0632_ (
    .A(\rd_bin[2] ),
    .B(_0264_),
    .Y(_0265_)
  );
  sky130_fd_sc_hd__and2_2 _0633_ (
    .A(_0192_),
    .B(_0265_),
    .X(_0266_)
  );
  sky130_fd_sc_hd__xnor2_2 _0634_ (
    .A(\rd_bin[4] ),
    .B(_0266_),
    .Y(\rd_gray_next[3] )
  );
  sky130_fd_sc_hd__or2_2 _0635_ (
    .A(\wr_gray_sync2[3] ),
    .B(\rd_gray_next[3] ),
    .X(_0267_)
  );
  sky130_fd_sc_hd__nand2_2 _0636_ (
    .A(\wr_gray_sync2[3] ),
    .B(\rd_gray_next[3] ),
    .Y(_0268_)
  );
  sky130_fd_sc_hd__xnor2_2 _0637_ (
    .A(_0192_),
    .B(_0264_),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__nor2_2 _0638_ (
    .A(\rd_bin[2] ),
    .B(_0264_),
    .Y(_0270_)
  );
  sky130_fd_sc_hd__mux2_2 _0639_ (
    .A0(_0264_),
    .A1(_0270_),
    .S(\rd_bin[3] ),
    .X(_0271_)
  );
  sky130_fd_sc_hd__or3_2 _0640_ (
    .A(\wr_gray_sync2[2] ),
    .B(_0192_),
    .C(_0264_),
    .X(_0272_)
  );
  sky130_fd_sc_hd__a21bo_2 _0641_ (
    .A1(\wr_gray_sync2[2] ),
    .A2(_0192_),
    .B1_N(_0272_),
    .X(_0273_)
  );
  sky130_fd_sc_hd__a22oi_2 _0642_ (
    .A1(\wr_gray_sync2[2] ),
    .A2(_0271_),
    .B1(_0273_),
    .B2(\rd_bin[2] ),
    .Y(_0274_)
  );
  sky130_fd_sc_hd__o31a_2 _0643_ (
    .A1(\wr_gray_sync2[2] ),
    .A2(\rd_bin[2] ),
    .A3(_0269_),
    .B1(_0274_),
    .X(_0275_)
  );
  sky130_fd_sc_hd__or3_2 _0644_ (
    .A(\wr_gray_sync2[2] ),
    .B(_0192_),
    .C(_0265_),
    .X(_0276_)
  );
  sky130_fd_sc_hd__xor2_2 _0645_ (
    .A(\wr_bin_sync[4] ),
    .B(\rd_bin[4] ),
    .X(_0277_)
  );
  sky130_fd_sc_hd__mux2_2 _0646_ (
    .A0(_0275_),
    .A1(_0276_),
    .S(_0277_),
    .X(_0278_)
  );
  sky130_fd_sc_hd__o22a_2 _0647_ (
    .A1(_0220_),
    .A2(_0261_),
    .B1(_0262_),
    .B2(\rd_bin[1] ),
    .X(_0279_)
  );
  sky130_fd_sc_hd__or2b_2 _0648_ (
    .A(\rd_bin[1] ),
    .B_N(\rd_bin_next[0] ),
    .X(_0280_)
  );
  sky130_fd_sc_hd__buf_1 _0649_ (
    .A(_0261_),
    .X(_0281_)
  );
  sky130_fd_sc_hd__o21ai_2 _0650_ (
    .A1(\rd_bin[0] ),
    .A2(_0281_),
    .B1(\rd_bin[1] ),
    .Y(_0282_)
  );
  sky130_fd_sc_hd__or3_2 _0651_ (
    .A(\rd_bin[0] ),
    .B(\rd_bin[1] ),
    .C(_0261_),
    .X(_0283_)
  );
  sky130_fd_sc_hd__xnor2_2 _0652_ (
    .A(\wr_gray_sync2[1] ),
    .B(\rd_bin[2] ),
    .Y(_0284_)
  );
  sky130_fd_sc_hd__mux4_2 _0653_ (
    .A0(_0279_),
    .A1(_0280_),
    .A2(_0282_),
    .A3(_0283_),
    .S0(_0284_),
    .S1(_0212_),
    .X(_0285_)
  );
  sky130_fd_sc_hd__a211oi_4 _0654_ (
    .A1(_0267_),
    .A2(_0268_),
    .B1(_0278_),
    .C1(_0285_),
    .Y(empty_next)
  );
  sky130_fd_sc_hd__a21bo_2 _0655_ (
    .A1(\wr_bin[2] ),
    .A2(_0239_),
    .B1_N(\wr_bin[3] ),
    .X(_0286_)
  );
  sky130_fd_sc_hd__nand2_2 _0656_ (
    .A(_0239_),
    .B(_0242_),
    .Y(_0287_)
  );
  sky130_fd_sc_hd__nand2_2 _0657_ (
    .A(_0286_),
    .B(_0287_),
    .Y(\wr_bin_next[3] )
  );
  sky130_fd_sc_hd__nand2_2 _0658_ (
    .A(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .Y(_0288_)
  );
  sky130_fd_sc_hd__or3_2 _0659_ (
    .A(_0143_),
    .B(_0237_),
    .C(_0288_),
    .X(_0289_)
  );
  sky130_fd_sc_hd__buf_1 _0660_ (
    .A(_0289_),
    .X(_0290_)
  );
  sky130_fd_sc_hd__xnor2_2 _0661_ (
    .A(\wr_bin[4] ),
    .B(_0290_),
    .Y(\wr_bin_next[4] )
  );
  sky130_fd_sc_hd__and2_2 _0662_ (
    .A(_0283_),
    .B(_0282_),
    .X(_0291_)
  );
  sky130_fd_sc_hd__buf_1 _0663_ (
    .A(_0291_),
    .X(\rd_gray_next[0] )
  );
  sky130_fd_sc_hd__a21oi_2 _0664_ (
    .A1(\rd_bin[0] ),
    .A2(_0281_),
    .B1(\rd_bin[1] ),
    .Y(_0292_)
  );
  sky130_fd_sc_hd__xnor2_2 _0665_ (
    .A(\rd_bin[2] ),
    .B(_0292_),
    .Y(\rd_gray_next[1] )
  );
  sky130_fd_sc_hd__xnor2_2 _0666_ (
    .A(\rd_bin[3] ),
    .B(_0265_),
    .Y(\rd_bin_next[3] )
  );
  sky130_fd_sc_hd__xnor2_2 _0667_ (
    .A(\rd_bin[3] ),
    .B(_0270_),
    .Y(\rd_gray_next[2] )
  );
  sky130_fd_sc_hd__nor2_2 _0668_ (
    .A(_0192_),
    .B(_0265_),
    .Y(_0293_)
  );
  sky130_fd_sc_hd__xor2_2 _0669_ (
    .A(\rd_bin[4] ),
    .B(_0293_),
    .X(\rd_bin_next[4] )
  );
  sky130_fd_sc_hd__xnor2_2 _0670_ (
    .A(\wr_bin[1] ),
    .B(_0256_),
    .Y(\wr_gray_next[0] )
  );
  sky130_fd_sc_hd__nor2_2 _0671_ (
    .A(\wr_bin[1] ),
    .B(_0235_),
    .Y(_0294_)
  );
  sky130_fd_sc_hd__xnor2_2 _0672_ (
    .A(\wr_bin[2] ),
    .B(_0294_),
    .Y(\wr_gray_next[1] )
  );
  sky130_fd_sc_hd__nor2_2 _0673_ (
    .A(\wr_bin[2] ),
    .B(_0239_),
    .Y(_0295_)
  );
  sky130_fd_sc_hd__xnor2_2 _0674_ (
    .A(\wr_bin[3] ),
    .B(_0295_),
    .Y(\wr_gray_next[2] )
  );
  sky130_fd_sc_hd__mux4_2 _0675_ (
    .A0(\mem[0][0] ),
    .A1(\mem[1][0] ),
    .A2(\mem[2][0] ),
    .A3(\mem[3][0] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0296_)
  );
  sky130_fd_sc_hd__mux4_2 _0676_ (
    .A0(\mem[8][0] ),
    .A1(\mem[9][0] ),
    .A2(\mem[10][0] ),
    .A3(\mem[11][0] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0297_)
  );
  sky130_fd_sc_hd__mux4_2 _0677_ (
    .A0(\mem[4][0] ),
    .A1(\mem[5][0] ),
    .A2(\mem[6][0] ),
    .A3(\mem[7][0] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0298_)
  );
  sky130_fd_sc_hd__mux4_2 _0678_ (
    .A0(\mem[12][0] ),
    .A1(\mem[13][0] ),
    .A2(\mem[14][0] ),
    .A3(\mem[15][0] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0299_)
  );
  sky130_fd_sc_hd__mux4_2 _0679_ (
    .A0(_0296_),
    .A1(_0297_),
    .A2(_0298_),
    .A3(_0299_),
    .S0(\rd_bin[3] ),
    .S1(\rd_bin[2] ),
    .X(_0300_)
  );
  sky130_fd_sc_hd__mux2_2 _0680_ (
    .A0(rd_data[0]),
    .A1(_0300_),
    .S(_0281_),
    .X(_0301_)
  );
  sky130_fd_sc_hd__buf_1 _0681_ (
    .A(_0301_),
    .X(_0000_)
  );
  sky130_fd_sc_hd__mux4_2 _0682_ (
    .A0(\mem[0][1] ),
    .A1(\mem[1][1] ),
    .A2(\mem[2][1] ),
    .A3(\mem[3][1] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0302_)
  );
  sky130_fd_sc_hd__mux4_2 _0683_ (
    .A0(\mem[8][1] ),
    .A1(\mem[9][1] ),
    .A2(\mem[10][1] ),
    .A3(\mem[11][1] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0303_)
  );
  sky130_fd_sc_hd__mux4_2 _0684_ (
    .A0(\mem[4][1] ),
    .A1(\mem[5][1] ),
    .A2(\mem[6][1] ),
    .A3(\mem[7][1] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0304_)
  );
  sky130_fd_sc_hd__mux4_2 _0685_ (
    .A0(\mem[12][1] ),
    .A1(\mem[13][1] ),
    .A2(\mem[14][1] ),
    .A3(\mem[15][1] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0305_)
  );
  sky130_fd_sc_hd__mux4_2 _0686_ (
    .A0(_0302_),
    .A1(_0303_),
    .A2(_0304_),
    .A3(_0305_),
    .S0(\rd_bin[3] ),
    .S1(\rd_bin[2] ),
    .X(_0306_)
  );
  sky130_fd_sc_hd__mux2_2 _0687_ (
    .A0(rd_data[1]),
    .A1(_0306_),
    .S(_0281_),
    .X(_0307_)
  );
  sky130_fd_sc_hd__buf_1 _0688_ (
    .A(_0307_),
    .X(_0001_)
  );
  sky130_fd_sc_hd__mux4_2 _0689_ (
    .A0(\mem[0][2] ),
    .A1(\mem[1][2] ),
    .A2(\mem[2][2] ),
    .A3(\mem[3][2] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0308_)
  );
  sky130_fd_sc_hd__mux4_2 _0690_ (
    .A0(\mem[8][2] ),
    .A1(\mem[9][2] ),
    .A2(\mem[10][2] ),
    .A3(\mem[11][2] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0309_)
  );
  sky130_fd_sc_hd__mux4_2 _0691_ (
    .A0(\mem[4][2] ),
    .A1(\mem[5][2] ),
    .A2(\mem[6][2] ),
    .A3(\mem[7][2] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0310_)
  );
  sky130_fd_sc_hd__mux4_2 _0692_ (
    .A0(\mem[12][2] ),
    .A1(\mem[13][2] ),
    .A2(\mem[14][2] ),
    .A3(\mem[15][2] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0311_)
  );
  sky130_fd_sc_hd__mux4_2 _0693_ (
    .A0(_0308_),
    .A1(_0309_),
    .A2(_0310_),
    .A3(_0311_),
    .S0(\rd_bin[3] ),
    .S1(\rd_bin[2] ),
    .X(_0312_)
  );
  sky130_fd_sc_hd__mux2_2 _0694_ (
    .A0(rd_data[2]),
    .A1(_0312_),
    .S(_0281_),
    .X(_0313_)
  );
  sky130_fd_sc_hd__buf_1 _0695_ (
    .A(_0313_),
    .X(_0002_)
  );
  sky130_fd_sc_hd__mux4_2 _0696_ (
    .A0(\mem[0][3] ),
    .A1(\mem[1][3] ),
    .A2(\mem[2][3] ),
    .A3(\mem[3][3] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0314_)
  );
  sky130_fd_sc_hd__mux4_2 _0697_ (
    .A0(\mem[8][3] ),
    .A1(\mem[9][3] ),
    .A2(\mem[10][3] ),
    .A3(\mem[11][3] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0315_)
  );
  sky130_fd_sc_hd__mux4_2 _0698_ (
    .A0(\mem[4][3] ),
    .A1(\mem[5][3] ),
    .A2(\mem[6][3] ),
    .A3(\mem[7][3] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0316_)
  );
  sky130_fd_sc_hd__mux4_2 _0699_ (
    .A0(\mem[12][3] ),
    .A1(\mem[13][3] ),
    .A2(\mem[14][3] ),
    .A3(\mem[15][3] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0317_)
  );
  sky130_fd_sc_hd__mux4_2 _0700_ (
    .A0(_0314_),
    .A1(_0315_),
    .A2(_0316_),
    .A3(_0317_),
    .S0(\rd_bin[3] ),
    .S1(\rd_bin[2] ),
    .X(_0318_)
  );
  sky130_fd_sc_hd__mux2_2 _0701_ (
    .A0(rd_data[3]),
    .A1(_0318_),
    .S(_0281_),
    .X(_0319_)
  );
  sky130_fd_sc_hd__buf_1 _0702_ (
    .A(_0319_),
    .X(_0003_)
  );
  sky130_fd_sc_hd__mux4_2 _0703_ (
    .A0(\mem[0][4] ),
    .A1(\mem[1][4] ),
    .A2(\mem[2][4] ),
    .A3(\mem[3][4] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0320_)
  );
  sky130_fd_sc_hd__mux4_2 _0704_ (
    .A0(\mem[8][4] ),
    .A1(\mem[9][4] ),
    .A2(\mem[10][4] ),
    .A3(\mem[11][4] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0321_)
  );
  sky130_fd_sc_hd__mux4_2 _0705_ (
    .A0(\mem[4][4] ),
    .A1(\mem[5][4] ),
    .A2(\mem[6][4] ),
    .A3(\mem[7][4] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0322_)
  );
  sky130_fd_sc_hd__mux4_2 _0706_ (
    .A0(\mem[12][4] ),
    .A1(\mem[13][4] ),
    .A2(\mem[14][4] ),
    .A3(\mem[15][4] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0323_)
  );
  sky130_fd_sc_hd__mux4_2 _0707_ (
    .A0(_0320_),
    .A1(_0321_),
    .A2(_0322_),
    .A3(_0323_),
    .S0(\rd_bin[3] ),
    .S1(\rd_bin[2] ),
    .X(_0324_)
  );
  sky130_fd_sc_hd__mux2_2 _0708_ (
    .A0(rd_data[4]),
    .A1(_0324_),
    .S(_0281_),
    .X(_0325_)
  );
  sky130_fd_sc_hd__buf_1 _0709_ (
    .A(_0325_),
    .X(_0004_)
  );
  sky130_fd_sc_hd__mux4_2 _0710_ (
    .A0(\mem[0][5] ),
    .A1(\mem[1][5] ),
    .A2(\mem[2][5] ),
    .A3(\mem[3][5] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0326_)
  );
  sky130_fd_sc_hd__mux4_2 _0711_ (
    .A0(\mem[8][5] ),
    .A1(\mem[9][5] ),
    .A2(\mem[10][5] ),
    .A3(\mem[11][5] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0327_)
  );
  sky130_fd_sc_hd__mux4_2 _0712_ (
    .A0(\mem[4][5] ),
    .A1(\mem[5][5] ),
    .A2(\mem[6][5] ),
    .A3(\mem[7][5] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0328_)
  );
  sky130_fd_sc_hd__mux4_2 _0713_ (
    .A0(\mem[12][5] ),
    .A1(\mem[13][5] ),
    .A2(\mem[14][5] ),
    .A3(\mem[15][5] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0329_)
  );
  sky130_fd_sc_hd__mux4_2 _0714_ (
    .A0(_0326_),
    .A1(_0327_),
    .A2(_0328_),
    .A3(_0329_),
    .S0(\rd_bin[3] ),
    .S1(\rd_bin[2] ),
    .X(_0330_)
  );
  sky130_fd_sc_hd__mux2_2 _0715_ (
    .A0(rd_data[5]),
    .A1(_0330_),
    .S(_0281_),
    .X(_0331_)
  );
  sky130_fd_sc_hd__buf_1 _0716_ (
    .A(_0331_),
    .X(_0005_)
  );
  sky130_fd_sc_hd__mux4_2 _0717_ (
    .A0(\mem[0][6] ),
    .A1(\mem[1][6] ),
    .A2(\mem[2][6] ),
    .A3(\mem[3][6] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0332_)
  );
  sky130_fd_sc_hd__mux4_2 _0718_ (
    .A0(\mem[8][6] ),
    .A1(\mem[9][6] ),
    .A2(\mem[10][6] ),
    .A3(\mem[11][6] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0333_)
  );
  sky130_fd_sc_hd__mux4_2 _0719_ (
    .A0(\mem[4][6] ),
    .A1(\mem[5][6] ),
    .A2(\mem[6][6] ),
    .A3(\mem[7][6] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0334_)
  );
  sky130_fd_sc_hd__mux4_2 _0720_ (
    .A0(\mem[12][6] ),
    .A1(\mem[13][6] ),
    .A2(\mem[14][6] ),
    .A3(\mem[15][6] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0335_)
  );
  sky130_fd_sc_hd__mux4_2 _0721_ (
    .A0(_0332_),
    .A1(_0333_),
    .A2(_0334_),
    .A3(_0335_),
    .S0(\rd_bin[3] ),
    .S1(\rd_bin[2] ),
    .X(_0336_)
  );
  sky130_fd_sc_hd__mux2_2 _0722_ (
    .A0(rd_data[6]),
    .A1(_0336_),
    .S(_0281_),
    .X(_0337_)
  );
  sky130_fd_sc_hd__buf_1 _0723_ (
    .A(_0337_),
    .X(_0006_)
  );
  sky130_fd_sc_hd__mux4_2 _0724_ (
    .A0(\mem[0][7] ),
    .A1(\mem[1][7] ),
    .A2(\mem[2][7] ),
    .A3(\mem[3][7] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0338_)
  );
  sky130_fd_sc_hd__mux4_2 _0725_ (
    .A0(\mem[8][7] ),
    .A1(\mem[9][7] ),
    .A2(\mem[10][7] ),
    .A3(\mem[11][7] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0339_)
  );
  sky130_fd_sc_hd__mux4_2 _0726_ (
    .A0(\mem[4][7] ),
    .A1(\mem[5][7] ),
    .A2(\mem[6][7] ),
    .A3(\mem[7][7] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0340_)
  );
  sky130_fd_sc_hd__mux4_2 _0727_ (
    .A0(\mem[12][7] ),
    .A1(\mem[13][7] ),
    .A2(\mem[14][7] ),
    .A3(\mem[15][7] ),
    .S0(\rd_bin[0] ),
    .S1(\rd_bin[1] ),
    .X(_0341_)
  );
  sky130_fd_sc_hd__mux4_2 _0728_ (
    .A0(_0338_),
    .A1(_0339_),
    .A2(_0340_),
    .A3(_0341_),
    .S0(\rd_bin[3] ),
    .S1(\rd_bin[2] ),
    .X(_0342_)
  );
  sky130_fd_sc_hd__mux2_2 _0729_ (
    .A0(rd_data[7]),
    .A1(_0342_),
    .S(_0281_),
    .X(_0343_)
  );
  sky130_fd_sc_hd__buf_1 _0730_ (
    .A(_0343_),
    .X(_0007_)
  );
  sky130_fd_sc_hd__or3_2 _0731_ (
    .A(_0143_),
    .B(\wr_bin[0] ),
    .C(_0234_),
    .X(_0344_)
  );
  sky130_fd_sc_hd__nor2_2 _0732_ (
    .A(_0288_),
    .B(_0344_),
    .Y(_0345_)
  );
  sky130_fd_sc_hd__mux2_2 _0733_ (
    .A0(\mem[14][0] ),
    .A1(wr_data[0]),
    .S(_0345_),
    .X(_0346_)
  );
  sky130_fd_sc_hd__buf_1 _0734_ (
    .A(_0346_),
    .X(_0008_)
  );
  sky130_fd_sc_hd__mux2_2 _0735_ (
    .A0(\mem[14][1] ),
    .A1(wr_data[1]),
    .S(_0345_),
    .X(_0347_)
  );
  sky130_fd_sc_hd__buf_1 _0736_ (
    .A(_0347_),
    .X(_0009_)
  );
  sky130_fd_sc_hd__mux2_2 _0737_ (
    .A0(\mem[14][2] ),
    .A1(wr_data[2]),
    .S(_0345_),
    .X(_0348_)
  );
  sky130_fd_sc_hd__buf_1 _0738_ (
    .A(_0348_),
    .X(_0010_)
  );
  sky130_fd_sc_hd__mux2_2 _0739_ (
    .A0(\mem[14][3] ),
    .A1(wr_data[3]),
    .S(_0345_),
    .X(_0349_)
  );
  sky130_fd_sc_hd__buf_1 _0740_ (
    .A(_0349_),
    .X(_0011_)
  );
  sky130_fd_sc_hd__mux2_2 _0741_ (
    .A0(\mem[14][4] ),
    .A1(wr_data[4]),
    .S(_0345_),
    .X(_0350_)
  );
  sky130_fd_sc_hd__buf_1 _0742_ (
    .A(_0350_),
    .X(_0012_)
  );
  sky130_fd_sc_hd__mux2_2 _0743_ (
    .A0(\mem[14][5] ),
    .A1(wr_data[5]),
    .S(_0345_),
    .X(_0351_)
  );
  sky130_fd_sc_hd__buf_1 _0744_ (
    .A(_0351_),
    .X(_0013_)
  );
  sky130_fd_sc_hd__mux2_2 _0745_ (
    .A0(\mem[14][6] ),
    .A1(wr_data[6]),
    .S(_0345_),
    .X(_0352_)
  );
  sky130_fd_sc_hd__buf_1 _0746_ (
    .A(_0352_),
    .X(_0014_)
  );
  sky130_fd_sc_hd__mux2_2 _0747_ (
    .A0(\mem[14][7] ),
    .A1(wr_data[7]),
    .S(_0345_),
    .X(_0353_)
  );
  sky130_fd_sc_hd__buf_1 _0748_ (
    .A(_0353_),
    .X(_0015_)
  );
  sky130_fd_sc_hd__nor2_2 _0749_ (
    .A(_0236_),
    .B(_0288_),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__mux2_2 _0750_ (
    .A0(\mem[13][0] ),
    .A1(wr_data[0]),
    .S(_0354_),
    .X(_0355_)
  );
  sky130_fd_sc_hd__buf_1 _0751_ (
    .A(_0355_),
    .X(_0016_)
  );
  sky130_fd_sc_hd__mux2_2 _0752_ (
    .A0(\mem[13][1] ),
    .A1(wr_data[1]),
    .S(_0354_),
    .X(_0356_)
  );
  sky130_fd_sc_hd__buf_1 _0753_ (
    .A(_0356_),
    .X(_0017_)
  );
  sky130_fd_sc_hd__mux2_2 _0754_ (
    .A0(\mem[13][2] ),
    .A1(wr_data[2]),
    .S(_0354_),
    .X(_0357_)
  );
  sky130_fd_sc_hd__buf_1 _0755_ (
    .A(_0357_),
    .X(_0018_)
  );
  sky130_fd_sc_hd__mux2_2 _0756_ (
    .A0(\mem[13][3] ),
    .A1(wr_data[3]),
    .S(_0354_),
    .X(_0358_)
  );
  sky130_fd_sc_hd__buf_1 _0757_ (
    .A(_0358_),
    .X(_0019_)
  );
  sky130_fd_sc_hd__mux2_2 _0758_ (
    .A0(\mem[13][4] ),
    .A1(wr_data[4]),
    .S(_0354_),
    .X(_0359_)
  );
  sky130_fd_sc_hd__buf_1 _0759_ (
    .A(_0359_),
    .X(_0020_)
  );
  sky130_fd_sc_hd__mux2_2 _0760_ (
    .A0(\mem[13][5] ),
    .A1(wr_data[5]),
    .S(_0354_),
    .X(_0360_)
  );
  sky130_fd_sc_hd__buf_1 _0761_ (
    .A(_0360_),
    .X(_0021_)
  );
  sky130_fd_sc_hd__mux2_2 _0762_ (
    .A0(\mem[13][6] ),
    .A1(wr_data[6]),
    .S(_0354_),
    .X(_0361_)
  );
  sky130_fd_sc_hd__buf_1 _0763_ (
    .A(_0361_),
    .X(_0022_)
  );
  sky130_fd_sc_hd__mux2_2 _0764_ (
    .A0(\mem[13][7] ),
    .A1(wr_data[7]),
    .S(_0354_),
    .X(_0362_)
  );
  sky130_fd_sc_hd__buf_1 _0765_ (
    .A(_0362_),
    .X(_0023_)
  );
  sky130_fd_sc_hd__or3_2 _0766_ (
    .A(\wr_bin[1] ),
    .B(\wr_bin[0] ),
    .C(_0234_),
    .X(_0363_)
  );
  sky130_fd_sc_hd__nor2_2 _0767_ (
    .A(_0288_),
    .B(_0363_),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__mux2_2 _0768_ (
    .A0(\mem[12][0] ),
    .A1(wr_data[0]),
    .S(_0364_),
    .X(_0365_)
  );
  sky130_fd_sc_hd__buf_1 _0769_ (
    .A(_0365_),
    .X(_0024_)
  );
  sky130_fd_sc_hd__mux2_2 _0770_ (
    .A0(\mem[12][1] ),
    .A1(wr_data[1]),
    .S(_0364_),
    .X(_0366_)
  );
  sky130_fd_sc_hd__buf_1 _0771_ (
    .A(_0366_),
    .X(_0025_)
  );
  sky130_fd_sc_hd__mux2_2 _0772_ (
    .A0(\mem[12][2] ),
    .A1(wr_data[2]),
    .S(_0364_),
    .X(_0367_)
  );
  sky130_fd_sc_hd__buf_1 _0773_ (
    .A(_0367_),
    .X(_0026_)
  );
  sky130_fd_sc_hd__mux2_2 _0774_ (
    .A0(\mem[12][3] ),
    .A1(wr_data[3]),
    .S(_0364_),
    .X(_0368_)
  );
  sky130_fd_sc_hd__buf_1 _0775_ (
    .A(_0368_),
    .X(_0027_)
  );
  sky130_fd_sc_hd__mux2_2 _0776_ (
    .A0(\mem[12][4] ),
    .A1(wr_data[4]),
    .S(_0364_),
    .X(_0369_)
  );
  sky130_fd_sc_hd__buf_1 _0777_ (
    .A(_0369_),
    .X(_0028_)
  );
  sky130_fd_sc_hd__mux2_2 _0778_ (
    .A0(\mem[12][5] ),
    .A1(wr_data[5]),
    .S(_0364_),
    .X(_0370_)
  );
  sky130_fd_sc_hd__buf_1 _0779_ (
    .A(_0370_),
    .X(_0029_)
  );
  sky130_fd_sc_hd__mux2_2 _0780_ (
    .A0(\mem[12][6] ),
    .A1(wr_data[6]),
    .S(_0364_),
    .X(_0371_)
  );
  sky130_fd_sc_hd__buf_1 _0781_ (
    .A(_0371_),
    .X(_0030_)
  );
  sky130_fd_sc_hd__mux2_2 _0782_ (
    .A0(\mem[12][7] ),
    .A1(wr_data[7]),
    .S(_0364_),
    .X(_0372_)
  );
  sky130_fd_sc_hd__buf_1 _0783_ (
    .A(_0372_),
    .X(_0031_)
  );
  sky130_fd_sc_hd__or2b_2 _0784_ (
    .A(\wr_bin[2] ),
    .B_N(\wr_bin[3] ),
    .X(_0373_)
  );
  sky130_fd_sc_hd__or3_2 _0785_ (
    .A(_0143_),
    .B(_0237_),
    .C(_0373_),
    .X(_0374_)
  );
  sky130_fd_sc_hd__buf_1 _0786_ (
    .A(_0374_),
    .X(_0375_)
  );
  sky130_fd_sc_hd__mux2_1 _0787_ (
    .A0(wr_data[0]),
    .A1(\mem[11][0] ),
    .S(_0375_),
    .X(_0376_)
  );
  sky130_fd_sc_hd__buf_1 _0788_ (
    .A(_0376_),
    .X(_0032_)
  );
  sky130_fd_sc_hd__mux2_1 _0789_ (
    .A0(wr_data[1]),
    .A1(\mem[11][1] ),
    .S(_0375_),
    .X(_0377_)
  );
  sky130_fd_sc_hd__buf_1 _0790_ (
    .A(_0377_),
    .X(_0033_)
  );
  sky130_fd_sc_hd__mux2_1 _0791_ (
    .A0(wr_data[2]),
    .A1(\mem[11][2] ),
    .S(_0375_),
    .X(_0378_)
  );
  sky130_fd_sc_hd__buf_1 _0792_ (
    .A(_0378_),
    .X(_0034_)
  );
  sky130_fd_sc_hd__mux2_1 _0793_ (
    .A0(wr_data[3]),
    .A1(\mem[11][3] ),
    .S(_0375_),
    .X(_0379_)
  );
  sky130_fd_sc_hd__buf_1 _0794_ (
    .A(_0379_),
    .X(_0035_)
  );
  sky130_fd_sc_hd__mux2_1 _0795_ (
    .A0(wr_data[4]),
    .A1(\mem[11][4] ),
    .S(_0375_),
    .X(_0380_)
  );
  sky130_fd_sc_hd__buf_1 _0796_ (
    .A(_0380_),
    .X(_0036_)
  );
  sky130_fd_sc_hd__mux2_1 _0797_ (
    .A0(wr_data[5]),
    .A1(\mem[11][5] ),
    .S(_0375_),
    .X(_0381_)
  );
  sky130_fd_sc_hd__buf_1 _0798_ (
    .A(_0381_),
    .X(_0037_)
  );
  sky130_fd_sc_hd__mux2_1 _0799_ (
    .A0(wr_data[6]),
    .A1(\mem[11][6] ),
    .S(_0375_),
    .X(_0382_)
  );
  sky130_fd_sc_hd__buf_1 _0800_ (
    .A(_0382_),
    .X(_0038_)
  );
  sky130_fd_sc_hd__mux2_1 _0801_ (
    .A0(wr_data[7]),
    .A1(\mem[11][7] ),
    .S(_0375_),
    .X(_0383_)
  );
  sky130_fd_sc_hd__buf_1 _0802_ (
    .A(_0383_),
    .X(_0039_)
  );
  sky130_fd_sc_hd__or2_2 _0803_ (
    .A(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .X(_0384_)
  );
  sky130_fd_sc_hd__nor2_2 _0804_ (
    .A(_0236_),
    .B(_0384_),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__mux2_2 _0805_ (
    .A0(\mem[1][0] ),
    .A1(wr_data[0]),
    .S(_0385_),
    .X(_0386_)
  );
  sky130_fd_sc_hd__buf_1 _0806_ (
    .A(_0386_),
    .X(_0040_)
  );
  sky130_fd_sc_hd__mux2_2 _0807_ (
    .A0(\mem[1][1] ),
    .A1(wr_data[1]),
    .S(_0385_),
    .X(_0387_)
  );
  sky130_fd_sc_hd__buf_1 _0808_ (
    .A(_0387_),
    .X(_0041_)
  );
  sky130_fd_sc_hd__mux2_2 _0809_ (
    .A0(\mem[1][2] ),
    .A1(wr_data[2]),
    .S(_0385_),
    .X(_0388_)
  );
  sky130_fd_sc_hd__buf_1 _0810_ (
    .A(_0388_),
    .X(_0042_)
  );
  sky130_fd_sc_hd__mux2_2 _0811_ (
    .A0(\mem[1][3] ),
    .A1(wr_data[3]),
    .S(_0385_),
    .X(_0389_)
  );
  sky130_fd_sc_hd__buf_1 _0812_ (
    .A(_0389_),
    .X(_0043_)
  );
  sky130_fd_sc_hd__mux2_2 _0813_ (
    .A0(\mem[1][4] ),
    .A1(wr_data[4]),
    .S(_0385_),
    .X(_0390_)
  );
  sky130_fd_sc_hd__buf_1 _0814_ (
    .A(_0390_),
    .X(_0044_)
  );
  sky130_fd_sc_hd__mux2_2 _0815_ (
    .A0(\mem[1][5] ),
    .A1(wr_data[5]),
    .S(_0385_),
    .X(_0391_)
  );
  sky130_fd_sc_hd__buf_1 _0816_ (
    .A(_0391_),
    .X(_0045_)
  );
  sky130_fd_sc_hd__mux2_2 _0817_ (
    .A0(\mem[1][6] ),
    .A1(wr_data[6]),
    .S(_0385_),
    .X(_0392_)
  );
  sky130_fd_sc_hd__buf_1 _0818_ (
    .A(_0392_),
    .X(_0046_)
  );
  sky130_fd_sc_hd__mux2_2 _0819_ (
    .A0(\mem[1][7] ),
    .A1(wr_data[7]),
    .S(_0385_),
    .X(_0393_)
  );
  sky130_fd_sc_hd__buf_1 _0820_ (
    .A(_0393_),
    .X(_0047_)
  );
  sky130_fd_sc_hd__nor2_2 _0821_ (
    .A(_0344_),
    .B(_0373_),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__mux2_2 _0822_ (
    .A0(\mem[10][0] ),
    .A1(wr_data[0]),
    .S(_0394_),
    .X(_0395_)
  );
  sky130_fd_sc_hd__buf_1 _0823_ (
    .A(_0395_),
    .X(_0048_)
  );
  sky130_fd_sc_hd__mux2_2 _0824_ (
    .A0(\mem[10][1] ),
    .A1(wr_data[1]),
    .S(_0394_),
    .X(_0396_)
  );
  sky130_fd_sc_hd__buf_1 _0825_ (
    .A(_0396_),
    .X(_0049_)
  );
  sky130_fd_sc_hd__mux2_2 _0826_ (
    .A0(\mem[10][2] ),
    .A1(wr_data[2]),
    .S(_0394_),
    .X(_0397_)
  );
  sky130_fd_sc_hd__buf_1 _0827_ (
    .A(_0397_),
    .X(_0050_)
  );
  sky130_fd_sc_hd__mux2_2 _0828_ (
    .A0(\mem[10][3] ),
    .A1(wr_data[3]),
    .S(_0394_),
    .X(_0398_)
  );
  sky130_fd_sc_hd__buf_1 _0829_ (
    .A(_0398_),
    .X(_0051_)
  );
  sky130_fd_sc_hd__mux2_2 _0830_ (
    .A0(\mem[10][4] ),
    .A1(wr_data[4]),
    .S(_0394_),
    .X(_0399_)
  );
  sky130_fd_sc_hd__buf_1 _0831_ (
    .A(_0399_),
    .X(_0052_)
  );
  sky130_fd_sc_hd__mux2_2 _0832_ (
    .A0(\mem[10][5] ),
    .A1(wr_data[5]),
    .S(_0394_),
    .X(_0400_)
  );
  sky130_fd_sc_hd__buf_1 _0833_ (
    .A(_0400_),
    .X(_0053_)
  );
  sky130_fd_sc_hd__mux2_2 _0834_ (
    .A0(\mem[10][6] ),
    .A1(wr_data[6]),
    .S(_0394_),
    .X(_0401_)
  );
  sky130_fd_sc_hd__buf_1 _0835_ (
    .A(_0401_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__mux2_2 _0836_ (
    .A0(\mem[10][7] ),
    .A1(wr_data[7]),
    .S(_0394_),
    .X(_0402_)
  );
  sky130_fd_sc_hd__buf_1 _0837_ (
    .A(_0402_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__nor2_2 _0838_ (
    .A(_0363_),
    .B(_0384_),
    .Y(_0403_)
  );
  sky130_fd_sc_hd__mux2_2 _0839_ (
    .A0(\mem[0][0] ),
    .A1(wr_data[0]),
    .S(_0403_),
    .X(_0404_)
  );
  sky130_fd_sc_hd__buf_1 _0840_ (
    .A(_0404_),
    .X(_0056_)
  );
  sky130_fd_sc_hd__mux2_2 _0841_ (
    .A0(\mem[0][1] ),
    .A1(wr_data[1]),
    .S(_0403_),
    .X(_0405_)
  );
  sky130_fd_sc_hd__buf_1 _0842_ (
    .A(_0405_),
    .X(_0057_)
  );
  sky130_fd_sc_hd__mux2_2 _0843_ (
    .A0(\mem[0][2] ),
    .A1(wr_data[2]),
    .S(_0403_),
    .X(_0406_)
  );
  sky130_fd_sc_hd__buf_1 _0844_ (
    .A(_0406_),
    .X(_0058_)
  );
  sky130_fd_sc_hd__mux2_2 _0845_ (
    .A0(\mem[0][3] ),
    .A1(wr_data[3]),
    .S(_0403_),
    .X(_0407_)
  );
  sky130_fd_sc_hd__buf_1 _0846_ (
    .A(_0407_),
    .X(_0059_)
  );
  sky130_fd_sc_hd__mux2_2 _0847_ (
    .A0(\mem[0][4] ),
    .A1(wr_data[4]),
    .S(_0403_),
    .X(_0408_)
  );
  sky130_fd_sc_hd__buf_1 _0848_ (
    .A(_0408_),
    .X(_0060_)
  );
  sky130_fd_sc_hd__mux2_2 _0849_ (
    .A0(\mem[0][5] ),
    .A1(wr_data[5]),
    .S(_0403_),
    .X(_0409_)
  );
  sky130_fd_sc_hd__buf_1 _0850_ (
    .A(_0409_),
    .X(_0061_)
  );
  sky130_fd_sc_hd__mux2_2 _0851_ (
    .A0(\mem[0][6] ),
    .A1(wr_data[6]),
    .S(_0403_),
    .X(_0410_)
  );
  sky130_fd_sc_hd__buf_1 _0852_ (
    .A(_0410_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__mux2_2 _0853_ (
    .A0(\mem[0][7] ),
    .A1(wr_data[7]),
    .S(_0403_),
    .X(_0411_)
  );
  sky130_fd_sc_hd__buf_1 _0854_ (
    .A(_0411_),
    .X(_0063_)
  );
  sky130_fd_sc_hd__nor2_2 _0855_ (
    .A(_0363_),
    .B(_0373_),
    .Y(_0412_)
  );
  sky130_fd_sc_hd__mux2_2 _0856_ (
    .A0(\mem[8][0] ),
    .A1(wr_data[0]),
    .S(_0412_),
    .X(_0413_)
  );
  sky130_fd_sc_hd__buf_1 _0857_ (
    .A(_0413_),
    .X(_0064_)
  );
  sky130_fd_sc_hd__mux2_2 _0858_ (
    .A0(\mem[8][1] ),
    .A1(wr_data[1]),
    .S(_0412_),
    .X(_0414_)
  );
  sky130_fd_sc_hd__buf_1 _0859_ (
    .A(_0414_),
    .X(_0065_)
  );
  sky130_fd_sc_hd__mux2_2 _0860_ (
    .A0(\mem[8][2] ),
    .A1(wr_data[2]),
    .S(_0412_),
    .X(_0415_)
  );
  sky130_fd_sc_hd__buf_1 _0861_ (
    .A(_0415_),
    .X(_0066_)
  );
  sky130_fd_sc_hd__mux2_2 _0862_ (
    .A0(\mem[8][3] ),
    .A1(wr_data[3]),
    .S(_0412_),
    .X(_0416_)
  );
  sky130_fd_sc_hd__buf_1 _0863_ (
    .A(_0416_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__mux2_2 _0864_ (
    .A0(\mem[8][4] ),
    .A1(wr_data[4]),
    .S(_0412_),
    .X(_0417_)
  );
  sky130_fd_sc_hd__buf_1 _0865_ (
    .A(_0417_),
    .X(_0068_)
  );
  sky130_fd_sc_hd__mux2_2 _0866_ (
    .A0(\mem[8][5] ),
    .A1(wr_data[5]),
    .S(_0412_),
    .X(_0418_)
  );
  sky130_fd_sc_hd__buf_1 _0867_ (
    .A(_0418_),
    .X(_0069_)
  );
  sky130_fd_sc_hd__mux2_2 _0868_ (
    .A0(\mem[8][6] ),
    .A1(wr_data[6]),
    .S(_0412_),
    .X(_0419_)
  );
  sky130_fd_sc_hd__buf_1 _0869_ (
    .A(_0419_),
    .X(_0070_)
  );
  sky130_fd_sc_hd__mux2_2 _0870_ (
    .A0(\mem[8][7] ),
    .A1(wr_data[7]),
    .S(_0412_),
    .X(_0420_)
  );
  sky130_fd_sc_hd__buf_1 _0871_ (
    .A(_0420_),
    .X(_0071_)
  );
  sky130_fd_sc_hd__mux2_2 _0872_ (
    .A0(wr_data[0]),
    .A1(\mem[7][0] ),
    .S(_0287_),
    .X(_0421_)
  );
  sky130_fd_sc_hd__buf_1 _0873_ (
    .A(_0421_),
    .X(_0072_)
  );
  sky130_fd_sc_hd__mux2_2 _0874_ (
    .A0(wr_data[1]),
    .A1(\mem[7][1] ),
    .S(_0287_),
    .X(_0422_)
  );
  sky130_fd_sc_hd__buf_1 _0875_ (
    .A(_0422_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__mux2_2 _0876_ (
    .A0(wr_data[2]),
    .A1(\mem[7][2] ),
    .S(_0287_),
    .X(_0423_)
  );
  sky130_fd_sc_hd__buf_1 _0877_ (
    .A(_0423_),
    .X(_0074_)
  );
  sky130_fd_sc_hd__mux2_2 _0878_ (
    .A0(wr_data[3]),
    .A1(\mem[7][3] ),
    .S(_0287_),
    .X(_0424_)
  );
  sky130_fd_sc_hd__buf_1 _0879_ (
    .A(_0424_),
    .X(_0075_)
  );
  sky130_fd_sc_hd__mux2_2 _0880_ (
    .A0(wr_data[4]),
    .A1(\mem[7][4] ),
    .S(_0287_),
    .X(_0425_)
  );
  sky130_fd_sc_hd__buf_1 _0881_ (
    .A(_0425_),
    .X(_0076_)
  );
  sky130_fd_sc_hd__mux2_2 _0882_ (
    .A0(wr_data[5]),
    .A1(\mem[7][5] ),
    .S(_0287_),
    .X(_0426_)
  );
  sky130_fd_sc_hd__buf_1 _0883_ (
    .A(_0426_),
    .X(_0077_)
  );
  sky130_fd_sc_hd__mux2_2 _0884_ (
    .A0(wr_data[6]),
    .A1(\mem[7][6] ),
    .S(_0287_),
    .X(_0427_)
  );
  sky130_fd_sc_hd__buf_1 _0885_ (
    .A(_0427_),
    .X(_0078_)
  );
  sky130_fd_sc_hd__mux2_2 _0886_ (
    .A0(wr_data[7]),
    .A1(\mem[7][7] ),
    .S(_0287_),
    .X(_0428_)
  );
  sky130_fd_sc_hd__buf_1 _0887_ (
    .A(_0428_),
    .X(_0079_)
  );
  sky130_fd_sc_hd__or2b_2 _0888_ (
    .A(\wr_bin[3] ),
    .B_N(\wr_bin[2] ),
    .X(_0429_)
  );
  sky130_fd_sc_hd__nor2_2 _0889_ (
    .A(_0429_),
    .B(_0344_),
    .Y(_0430_)
  );
  sky130_fd_sc_hd__mux2_2 _0890_ (
    .A0(\mem[6][0] ),
    .A1(wr_data[0]),
    .S(_0430_),
    .X(_0431_)
  );
  sky130_fd_sc_hd__buf_1 _0891_ (
    .A(_0431_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__mux2_2 _0892_ (
    .A0(\mem[6][1] ),
    .A1(wr_data[1]),
    .S(_0430_),
    .X(_0432_)
  );
  sky130_fd_sc_hd__buf_1 _0893_ (
    .A(_0432_),
    .X(_0081_)
  );
  sky130_fd_sc_hd__mux2_2 _0894_ (
    .A0(\mem[6][2] ),
    .A1(wr_data[2]),
    .S(_0430_),
    .X(_0433_)
  );
  sky130_fd_sc_hd__buf_1 _0895_ (
    .A(_0433_),
    .X(_0082_)
  );
  sky130_fd_sc_hd__mux2_2 _0896_ (
    .A0(\mem[6][3] ),
    .A1(wr_data[3]),
    .S(_0430_),
    .X(_0434_)
  );
  sky130_fd_sc_hd__buf_1 _0897_ (
    .A(_0434_),
    .X(_0083_)
  );
  sky130_fd_sc_hd__mux2_2 _0898_ (
    .A0(\mem[6][4] ),
    .A1(wr_data[4]),
    .S(_0430_),
    .X(_0435_)
  );
  sky130_fd_sc_hd__buf_1 _0899_ (
    .A(_0435_),
    .X(_0084_)
  );
  sky130_fd_sc_hd__mux2_2 _0900_ (
    .A0(\mem[6][5] ),
    .A1(wr_data[5]),
    .S(_0430_),
    .X(_0436_)
  );
  sky130_fd_sc_hd__buf_1 _0901_ (
    .A(_0436_),
    .X(_0085_)
  );
  sky130_fd_sc_hd__mux2_2 _0902_ (
    .A0(\mem[6][6] ),
    .A1(wr_data[6]),
    .S(_0430_),
    .X(_0437_)
  );
  sky130_fd_sc_hd__buf_1 _0903_ (
    .A(_0437_),
    .X(_0086_)
  );
  sky130_fd_sc_hd__mux2_2 _0904_ (
    .A0(\mem[6][7] ),
    .A1(wr_data[7]),
    .S(_0430_),
    .X(_0438_)
  );
  sky130_fd_sc_hd__buf_1 _0905_ (
    .A(_0438_),
    .X(_0087_)
  );
  sky130_fd_sc_hd__nor2_2 _0906_ (
    .A(_0344_),
    .B(_0384_),
    .Y(_0439_)
  );
  sky130_fd_sc_hd__mux2_2 _0907_ (
    .A0(\mem[2][0] ),
    .A1(wr_data[0]),
    .S(_0439_),
    .X(_0440_)
  );
  sky130_fd_sc_hd__buf_1 _0908_ (
    .A(_0440_),
    .X(_0088_)
  );
  sky130_fd_sc_hd__mux2_2 _0909_ (
    .A0(\mem[2][1] ),
    .A1(wr_data[1]),
    .S(_0439_),
    .X(_0441_)
  );
  sky130_fd_sc_hd__buf_1 _0910_ (
    .A(_0441_),
    .X(_0089_)
  );
  sky130_fd_sc_hd__mux2_2 _0911_ (
    .A0(\mem[2][2] ),
    .A1(wr_data[2]),
    .S(_0439_),
    .X(_0442_)
  );
  sky130_fd_sc_hd__buf_1 _0912_ (
    .A(_0442_),
    .X(_0090_)
  );
  sky130_fd_sc_hd__mux2_2 _0913_ (
    .A0(\mem[2][3] ),
    .A1(wr_data[3]),
    .S(_0439_),
    .X(_0443_)
  );
  sky130_fd_sc_hd__buf_1 _0914_ (
    .A(_0443_),
    .X(_0091_)
  );
  sky130_fd_sc_hd__mux2_2 _0915_ (
    .A0(\mem[2][4] ),
    .A1(wr_data[4]),
    .S(_0439_),
    .X(_0444_)
  );
  sky130_fd_sc_hd__buf_1 _0916_ (
    .A(_0444_),
    .X(_0092_)
  );
  sky130_fd_sc_hd__mux2_2 _0917_ (
    .A0(\mem[2][5] ),
    .A1(wr_data[5]),
    .S(_0439_),
    .X(_0445_)
  );
  sky130_fd_sc_hd__buf_1 _0918_ (
    .A(_0445_),
    .X(_0093_)
  );
  sky130_fd_sc_hd__mux2_2 _0919_ (
    .A0(\mem[2][6] ),
    .A1(wr_data[6]),
    .S(_0439_),
    .X(_0446_)
  );
  sky130_fd_sc_hd__buf_1 _0920_ (
    .A(_0446_),
    .X(_0094_)
  );
  sky130_fd_sc_hd__mux2_2 _0921_ (
    .A0(\mem[2][7] ),
    .A1(wr_data[7]),
    .S(_0439_),
    .X(_0447_)
  );
  sky130_fd_sc_hd__buf_1 _0922_ (
    .A(_0447_),
    .X(_0095_)
  );
  sky130_fd_sc_hd__or3_2 _0923_ (
    .A(_0143_),
    .B(_0237_),
    .C(_0384_),
    .X(_0448_)
  );
  sky130_fd_sc_hd__buf_1 _0924_ (
    .A(_0448_),
    .X(_0449_)
  );
  sky130_fd_sc_hd__mux2_1 _0925_ (
    .A0(wr_data[0]),
    .A1(\mem[3][0] ),
    .S(_0449_),
    .X(_0450_)
  );
  sky130_fd_sc_hd__buf_1 _0926_ (
    .A(_0450_),
    .X(_0096_)
  );
  sky130_fd_sc_hd__mux2_1 _0927_ (
    .A0(wr_data[1]),
    .A1(\mem[3][1] ),
    .S(_0449_),
    .X(_0451_)
  );
  sky130_fd_sc_hd__buf_1 _0928_ (
    .A(_0451_),
    .X(_0097_)
  );
  sky130_fd_sc_hd__mux2_1 _0929_ (
    .A0(wr_data[2]),
    .A1(\mem[3][2] ),
    .S(_0449_),
    .X(_0452_)
  );
  sky130_fd_sc_hd__buf_1 _0930_ (
    .A(_0452_),
    .X(_0098_)
  );
  sky130_fd_sc_hd__mux2_1 _0931_ (
    .A0(wr_data[3]),
    .A1(\mem[3][3] ),
    .S(_0449_),
    .X(_0453_)
  );
  sky130_fd_sc_hd__buf_1 _0932_ (
    .A(_0453_),
    .X(_0099_)
  );
  sky130_fd_sc_hd__mux2_1 _0933_ (
    .A0(wr_data[4]),
    .A1(\mem[3][4] ),
    .S(_0449_),
    .X(_0454_)
  );
  sky130_fd_sc_hd__buf_1 _0934_ (
    .A(_0454_),
    .X(_0100_)
  );
  sky130_fd_sc_hd__mux2_1 _0935_ (
    .A0(wr_data[5]),
    .A1(\mem[3][5] ),
    .S(_0449_),
    .X(_0455_)
  );
  sky130_fd_sc_hd__buf_1 _0936_ (
    .A(_0455_),
    .X(_0101_)
  );
  sky130_fd_sc_hd__mux2_1 _0937_ (
    .A0(wr_data[6]),
    .A1(\mem[3][6] ),
    .S(_0449_),
    .X(_0456_)
  );
  sky130_fd_sc_hd__buf_1 _0938_ (
    .A(_0456_),
    .X(_0102_)
  );
  sky130_fd_sc_hd__mux2_1 _0939_ (
    .A0(wr_data[7]),
    .A1(\mem[3][7] ),
    .S(_0449_),
    .X(_0457_)
  );
  sky130_fd_sc_hd__buf_1 _0940_ (
    .A(_0457_),
    .X(_0103_)
  );
  sky130_fd_sc_hd__nor2_2 _0941_ (
    .A(_0236_),
    .B(_0429_),
    .Y(_0458_)
  );
  sky130_fd_sc_hd__mux2_2 _0942_ (
    .A0(\mem[5][0] ),
    .A1(wr_data[0]),
    .S(_0458_),
    .X(_0459_)
  );
  sky130_fd_sc_hd__buf_1 _0943_ (
    .A(_0459_),
    .X(_0104_)
  );
  sky130_fd_sc_hd__mux2_2 _0944_ (
    .A0(\mem[5][1] ),
    .A1(wr_data[1]),
    .S(_0458_),
    .X(_0460_)
  );
  sky130_fd_sc_hd__buf_1 _0945_ (
    .A(_0460_),
    .X(_0105_)
  );
  sky130_fd_sc_hd__mux2_2 _0946_ (
    .A0(\mem[5][2] ),
    .A1(wr_data[2]),
    .S(_0458_),
    .X(_0461_)
  );
  sky130_fd_sc_hd__buf_1 _0947_ (
    .A(_0461_),
    .X(_0106_)
  );
  sky130_fd_sc_hd__mux2_2 _0948_ (
    .A0(\mem[5][3] ),
    .A1(wr_data[3]),
    .S(_0458_),
    .X(_0462_)
  );
  sky130_fd_sc_hd__buf_1 _0949_ (
    .A(_0462_),
    .X(_0107_)
  );
  sky130_fd_sc_hd__mux2_2 _0950_ (
    .A0(\mem[5][4] ),
    .A1(wr_data[4]),
    .S(_0458_),
    .X(_0463_)
  );
  sky130_fd_sc_hd__buf_1 _0951_ (
    .A(_0463_),
    .X(_0108_)
  );
  sky130_fd_sc_hd__mux2_2 _0952_ (
    .A0(\mem[5][5] ),
    .A1(wr_data[5]),
    .S(_0458_),
    .X(_0464_)
  );
  sky130_fd_sc_hd__buf_1 _0953_ (
    .A(_0464_),
    .X(_0109_)
  );
  sky130_fd_sc_hd__mux2_2 _0954_ (
    .A0(\mem[5][6] ),
    .A1(wr_data[6]),
    .S(_0458_),
    .X(_0465_)
  );
  sky130_fd_sc_hd__buf_1 _0955_ (
    .A(_0465_),
    .X(_0110_)
  );
  sky130_fd_sc_hd__mux2_2 _0956_ (
    .A0(\mem[5][7] ),
    .A1(wr_data[7]),
    .S(_0458_),
    .X(_0466_)
  );
  sky130_fd_sc_hd__buf_1 _0957_ (
    .A(_0466_),
    .X(_0111_)
  );
  sky130_fd_sc_hd__nor2_2 _0958_ (
    .A(_0429_),
    .B(_0363_),
    .Y(_0467_)
  );
  sky130_fd_sc_hd__mux2_2 _0959_ (
    .A0(\mem[4][0] ),
    .A1(wr_data[0]),
    .S(_0467_),
    .X(_0468_)
  );
  sky130_fd_sc_hd__buf_1 _0960_ (
    .A(_0468_),
    .X(_0112_)
  );
  sky130_fd_sc_hd__mux2_2 _0961_ (
    .A0(\mem[4][1] ),
    .A1(wr_data[1]),
    .S(_0467_),
    .X(_0469_)
  );
  sky130_fd_sc_hd__buf_1 _0962_ (
    .A(_0469_),
    .X(_0113_)
  );
  sky130_fd_sc_hd__mux2_2 _0963_ (
    .A0(\mem[4][2] ),
    .A1(wr_data[2]),
    .S(_0467_),
    .X(_0470_)
  );
  sky130_fd_sc_hd__buf_1 _0964_ (
    .A(_0470_),
    .X(_0114_)
  );
  sky130_fd_sc_hd__mux2_2 _0965_ (
    .A0(\mem[4][3] ),
    .A1(wr_data[3]),
    .S(_0467_),
    .X(_0471_)
  );
  sky130_fd_sc_hd__buf_1 _0966_ (
    .A(_0471_),
    .X(_0115_)
  );
  sky130_fd_sc_hd__mux2_2 _0967_ (
    .A0(\mem[4][4] ),
    .A1(wr_data[4]),
    .S(_0467_),
    .X(_0472_)
  );
  sky130_fd_sc_hd__buf_1 _0968_ (
    .A(_0472_),
    .X(_0116_)
  );
  sky130_fd_sc_hd__mux2_2 _0969_ (
    .A0(\mem[4][5] ),
    .A1(wr_data[5]),
    .S(_0467_),
    .X(_0473_)
  );
  sky130_fd_sc_hd__buf_1 _0970_ (
    .A(_0473_),
    .X(_0117_)
  );
  sky130_fd_sc_hd__mux2_2 _0971_ (
    .A0(\mem[4][6] ),
    .A1(wr_data[6]),
    .S(_0467_),
    .X(_0474_)
  );
  sky130_fd_sc_hd__buf_1 _0972_ (
    .A(_0474_),
    .X(_0118_)
  );
  sky130_fd_sc_hd__mux2_2 _0973_ (
    .A0(\mem[4][7] ),
    .A1(wr_data[7]),
    .S(_0467_),
    .X(_0475_)
  );
  sky130_fd_sc_hd__buf_1 _0974_ (
    .A(_0475_),
    .X(_0119_)
  );
  sky130_fd_sc_hd__mux2_1 _0975_ (
    .A0(wr_data[0]),
    .A1(\mem[15][0] ),
    .S(_0290_),
    .X(_0476_)
  );
  sky130_fd_sc_hd__buf_1 _0976_ (
    .A(_0476_),
    .X(_0120_)
  );
  sky130_fd_sc_hd__mux2_1 _0977_ (
    .A0(wr_data[1]),
    .A1(\mem[15][1] ),
    .S(_0290_),
    .X(_0477_)
  );
  sky130_fd_sc_hd__buf_1 _0978_ (
    .A(_0477_),
    .X(_0121_)
  );
  sky130_fd_sc_hd__mux2_1 _0979_ (
    .A0(wr_data[2]),
    .A1(\mem[15][2] ),
    .S(_0290_),
    .X(_0478_)
  );
  sky130_fd_sc_hd__buf_1 _0980_ (
    .A(_0478_),
    .X(_0122_)
  );
  sky130_fd_sc_hd__mux2_1 _0981_ (
    .A0(wr_data[3]),
    .A1(\mem[15][3] ),
    .S(_0290_),
    .X(_0479_)
  );
  sky130_fd_sc_hd__buf_1 _0982_ (
    .A(_0479_),
    .X(_0123_)
  );
  sky130_fd_sc_hd__mux2_1 _0983_ (
    .A0(wr_data[4]),
    .A1(\mem[15][4] ),
    .S(_0290_),
    .X(_0480_)
  );
  sky130_fd_sc_hd__buf_1 _0984_ (
    .A(_0480_),
    .X(_0124_)
  );
  sky130_fd_sc_hd__mux2_1 _0985_ (
    .A0(wr_data[5]),
    .A1(\mem[15][5] ),
    .S(_0290_),
    .X(_0481_)
  );
  sky130_fd_sc_hd__buf_1 _0986_ (
    .A(_0481_),
    .X(_0125_)
  );
  sky130_fd_sc_hd__mux2_1 _0987_ (
    .A0(wr_data[6]),
    .A1(\mem[15][6] ),
    .S(_0290_),
    .X(_0482_)
  );
  sky130_fd_sc_hd__buf_1 _0988_ (
    .A(_0482_),
    .X(_0126_)
  );
  sky130_fd_sc_hd__mux2_2 _0989_ (
    .A0(wr_data[7]),
    .A1(\mem[15][7] ),
    .S(_0290_),
    .X(_0483_)
  );
  sky130_fd_sc_hd__buf_1 _0990_ (
    .A(_0483_),
    .X(_0127_)
  );
  sky130_fd_sc_hd__nor2_2 _0991_ (
    .A(_0236_),
    .B(_0373_),
    .Y(_0484_)
  );
  sky130_fd_sc_hd__mux2_2 _0992_ (
    .A0(\mem[9][0] ),
    .A1(wr_data[0]),
    .S(_0484_),
    .X(_0485_)
  );
  sky130_fd_sc_hd__buf_1 _0993_ (
    .A(_0485_),
    .X(_0128_)
  );
  sky130_fd_sc_hd__mux2_2 _0994_ (
    .A0(\mem[9][1] ),
    .A1(wr_data[1]),
    .S(_0484_),
    .X(_0486_)
  );
  sky130_fd_sc_hd__buf_1 _0995_ (
    .A(_0486_),
    .X(_0129_)
  );
  sky130_fd_sc_hd__mux2_2 _0996_ (
    .A0(\mem[9][2] ),
    .A1(wr_data[2]),
    .S(_0484_),
    .X(_0487_)
  );
  sky130_fd_sc_hd__buf_1 _0997_ (
    .A(_0487_),
    .X(_0130_)
  );
  sky130_fd_sc_hd__mux2_2 _0998_ (
    .A0(\mem[9][3] ),
    .A1(wr_data[3]),
    .S(_0484_),
    .X(_0488_)
  );
  sky130_fd_sc_hd__buf_1 _0999_ (
    .A(_0488_),
    .X(_0131_)
  );
  sky130_fd_sc_hd__mux2_2 _1000_ (
    .A0(\mem[9][4] ),
    .A1(wr_data[4]),
    .S(_0484_),
    .X(_0489_)
  );
  sky130_fd_sc_hd__buf_1 _1001_ (
    .A(_0489_),
    .X(_0132_)
  );
  sky130_fd_sc_hd__mux2_2 _1002_ (
    .A0(\mem[9][5] ),
    .A1(wr_data[5]),
    .S(_0484_),
    .X(_0490_)
  );
  sky130_fd_sc_hd__buf_1 _1003_ (
    .A(_0490_),
    .X(_0133_)
  );
  sky130_fd_sc_hd__mux2_2 _1004_ (
    .A0(\mem[9][6] ),
    .A1(wr_data[6]),
    .S(_0484_),
    .X(_0491_)
  );
  sky130_fd_sc_hd__buf_1 _1005_ (
    .A(_0491_),
    .X(_0134_)
  );
  sky130_fd_sc_hd__mux2_2 _1006_ (
    .A0(\mem[9][7] ),
    .A1(wr_data[7]),
    .S(_0484_),
    .X(_0492_)
  );
  sky130_fd_sc_hd__buf_1 _1007_ (
    .A(_0492_),
    .X(_0135_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1008_ (
    .CLK(rd_clk),
    .D(_0000_),
    .Q(rd_data[0]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1009_ (
    .CLK(rd_clk),
    .D(_0001_),
    .Q(rd_data[1]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1010_ (
    .CLK(rd_clk),
    .D(_0002_),
    .Q(rd_data[2]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1011_ (
    .CLK(rd_clk),
    .D(_0003_),
    .Q(rd_data[3]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1012_ (
    .CLK(rd_clk),
    .D(_0004_),
    .Q(rd_data[4]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1013_ (
    .CLK(rd_clk),
    .D(_0005_),
    .Q(rd_data[5]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1014_ (
    .CLK(rd_clk),
    .D(_0006_),
    .Q(rd_data[6]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1015_ (
    .CLK(rd_clk),
    .D(_0007_),
    .Q(rd_data[7]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfxtp_2 _1016_ (
    .CLK(wr_clk),
    .D(_0008_),
    .Q(\mem[14][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1017_ (
    .CLK(wr_clk),
    .D(_0009_),
    .Q(\mem[14][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1018_ (
    .CLK(wr_clk),
    .D(_0010_),
    .Q(\mem[14][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1019_ (
    .CLK(wr_clk),
    .D(_0011_),
    .Q(\mem[14][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1020_ (
    .CLK(wr_clk),
    .D(_0012_),
    .Q(\mem[14][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1021_ (
    .CLK(wr_clk),
    .D(_0013_),
    .Q(\mem[14][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1022_ (
    .CLK(wr_clk),
    .D(_0014_),
    .Q(\mem[14][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1023_ (
    .CLK(wr_clk),
    .D(_0015_),
    .Q(\mem[14][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1024_ (
    .CLK(wr_clk),
    .D(_0016_),
    .Q(\mem[13][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1025_ (
    .CLK(wr_clk),
    .D(_0017_),
    .Q(\mem[13][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1026_ (
    .CLK(wr_clk),
    .D(_0018_),
    .Q(\mem[13][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1027_ (
    .CLK(wr_clk),
    .D(_0019_),
    .Q(\mem[13][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1028_ (
    .CLK(wr_clk),
    .D(_0020_),
    .Q(\mem[13][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1029_ (
    .CLK(wr_clk),
    .D(_0021_),
    .Q(\mem[13][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1030_ (
    .CLK(wr_clk),
    .D(_0022_),
    .Q(\mem[13][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1031_ (
    .CLK(wr_clk),
    .D(_0023_),
    .Q(\mem[13][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1032_ (
    .CLK(wr_clk),
    .D(_0024_),
    .Q(\mem[12][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1033_ (
    .CLK(wr_clk),
    .D(_0025_),
    .Q(\mem[12][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1034_ (
    .CLK(wr_clk),
    .D(_0026_),
    .Q(\mem[12][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1035_ (
    .CLK(wr_clk),
    .D(_0027_),
    .Q(\mem[12][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1036_ (
    .CLK(wr_clk),
    .D(_0028_),
    .Q(\mem[12][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1037_ (
    .CLK(wr_clk),
    .D(_0029_),
    .Q(\mem[12][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1038_ (
    .CLK(wr_clk),
    .D(_0030_),
    .Q(\mem[12][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1039_ (
    .CLK(wr_clk),
    .D(_0031_),
    .Q(\mem[12][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1040_ (
    .CLK(wr_clk),
    .D(_0032_),
    .Q(\mem[11][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1041_ (
    .CLK(wr_clk),
    .D(_0033_),
    .Q(\mem[11][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1042_ (
    .CLK(wr_clk),
    .D(_0034_),
    .Q(\mem[11][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1043_ (
    .CLK(wr_clk),
    .D(_0035_),
    .Q(\mem[11][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1044_ (
    .CLK(wr_clk),
    .D(_0036_),
    .Q(\mem[11][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1045_ (
    .CLK(wr_clk),
    .D(_0037_),
    .Q(\mem[11][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1046_ (
    .CLK(wr_clk),
    .D(_0038_),
    .Q(\mem[11][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1047_ (
    .CLK(wr_clk),
    .D(_0039_),
    .Q(\mem[11][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1048_ (
    .CLK(wr_clk),
    .D(_0040_),
    .Q(\mem[1][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1049_ (
    .CLK(wr_clk),
    .D(_0041_),
    .Q(\mem[1][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1050_ (
    .CLK(wr_clk),
    .D(_0042_),
    .Q(\mem[1][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1051_ (
    .CLK(wr_clk),
    .D(_0043_),
    .Q(\mem[1][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1052_ (
    .CLK(wr_clk),
    .D(_0044_),
    .Q(\mem[1][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1053_ (
    .CLK(wr_clk),
    .D(_0045_),
    .Q(\mem[1][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1054_ (
    .CLK(wr_clk),
    .D(_0046_),
    .Q(\mem[1][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1055_ (
    .CLK(wr_clk),
    .D(_0047_),
    .Q(\mem[1][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1056_ (
    .CLK(wr_clk),
    .D(_0048_),
    .Q(\mem[10][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1057_ (
    .CLK(wr_clk),
    .D(_0049_),
    .Q(\mem[10][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1058_ (
    .CLK(wr_clk),
    .D(_0050_),
    .Q(\mem[10][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1059_ (
    .CLK(wr_clk),
    .D(_0051_),
    .Q(\mem[10][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1060_ (
    .CLK(wr_clk),
    .D(_0052_),
    .Q(\mem[10][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1061_ (
    .CLK(wr_clk),
    .D(_0053_),
    .Q(\mem[10][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1062_ (
    .CLK(wr_clk),
    .D(_0054_),
    .Q(\mem[10][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1063_ (
    .CLK(wr_clk),
    .D(_0055_),
    .Q(\mem[10][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1064_ (
    .CLK(wr_clk),
    .D(_0056_),
    .Q(\mem[0][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1065_ (
    .CLK(wr_clk),
    .D(_0057_),
    .Q(\mem[0][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1066_ (
    .CLK(wr_clk),
    .D(_0058_),
    .Q(\mem[0][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1067_ (
    .CLK(wr_clk),
    .D(_0059_),
    .Q(\mem[0][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1068_ (
    .CLK(wr_clk),
    .D(_0060_),
    .Q(\mem[0][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1069_ (
    .CLK(wr_clk),
    .D(_0061_),
    .Q(\mem[0][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1070_ (
    .CLK(wr_clk),
    .D(_0062_),
    .Q(\mem[0][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1071_ (
    .CLK(wr_clk),
    .D(_0063_),
    .Q(\mem[0][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1072_ (
    .CLK(wr_clk),
    .D(_0064_),
    .Q(\mem[8][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1073_ (
    .CLK(wr_clk),
    .D(_0065_),
    .Q(\mem[8][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1074_ (
    .CLK(wr_clk),
    .D(_0066_),
    .Q(\mem[8][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1075_ (
    .CLK(wr_clk),
    .D(_0067_),
    .Q(\mem[8][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1076_ (
    .CLK(wr_clk),
    .D(_0068_),
    .Q(\mem[8][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1077_ (
    .CLK(wr_clk),
    .D(_0069_),
    .Q(\mem[8][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1078_ (
    .CLK(wr_clk),
    .D(_0070_),
    .Q(\mem[8][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1079_ (
    .CLK(wr_clk),
    .D(_0071_),
    .Q(\mem[8][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1080_ (
    .CLK(wr_clk),
    .D(_0072_),
    .Q(\mem[7][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1081_ (
    .CLK(wr_clk),
    .D(_0073_),
    .Q(\mem[7][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1082_ (
    .CLK(wr_clk),
    .D(_0074_),
    .Q(\mem[7][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1083_ (
    .CLK(wr_clk),
    .D(_0075_),
    .Q(\mem[7][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1084_ (
    .CLK(wr_clk),
    .D(_0076_),
    .Q(\mem[7][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1085_ (
    .CLK(wr_clk),
    .D(_0077_),
    .Q(\mem[7][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1086_ (
    .CLK(wr_clk),
    .D(_0078_),
    .Q(\mem[7][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1087_ (
    .CLK(wr_clk),
    .D(_0079_),
    .Q(\mem[7][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1088_ (
    .CLK(wr_clk),
    .D(_0080_),
    .Q(\mem[6][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1089_ (
    .CLK(wr_clk),
    .D(_0081_),
    .Q(\mem[6][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1090_ (
    .CLK(wr_clk),
    .D(_0082_),
    .Q(\mem[6][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1091_ (
    .CLK(wr_clk),
    .D(_0083_),
    .Q(\mem[6][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1092_ (
    .CLK(wr_clk),
    .D(_0084_),
    .Q(\mem[6][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1093_ (
    .CLK(wr_clk),
    .D(_0085_),
    .Q(\mem[6][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1094_ (
    .CLK(wr_clk),
    .D(_0086_),
    .Q(\mem[6][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1095_ (
    .CLK(wr_clk),
    .D(_0087_),
    .Q(\mem[6][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1096_ (
    .CLK(wr_clk),
    .D(_0088_),
    .Q(\mem[2][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1097_ (
    .CLK(wr_clk),
    .D(_0089_),
    .Q(\mem[2][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1098_ (
    .CLK(wr_clk),
    .D(_0090_),
    .Q(\mem[2][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1099_ (
    .CLK(wr_clk),
    .D(_0091_),
    .Q(\mem[2][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1100_ (
    .CLK(wr_clk),
    .D(_0092_),
    .Q(\mem[2][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1101_ (
    .CLK(wr_clk),
    .D(_0093_),
    .Q(\mem[2][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1102_ (
    .CLK(wr_clk),
    .D(_0094_),
    .Q(\mem[2][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1103_ (
    .CLK(wr_clk),
    .D(_0095_),
    .Q(\mem[2][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1104_ (
    .CLK(wr_clk),
    .D(_0096_),
    .Q(\mem[3][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1105_ (
    .CLK(wr_clk),
    .D(_0097_),
    .Q(\mem[3][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1106_ (
    .CLK(wr_clk),
    .D(_0098_),
    .Q(\mem[3][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1107_ (
    .CLK(wr_clk),
    .D(_0099_),
    .Q(\mem[3][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1108_ (
    .CLK(wr_clk),
    .D(_0100_),
    .Q(\mem[3][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1109_ (
    .CLK(wr_clk),
    .D(_0101_),
    .Q(\mem[3][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1110_ (
    .CLK(wr_clk),
    .D(_0102_),
    .Q(\mem[3][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1111_ (
    .CLK(wr_clk),
    .D(_0103_),
    .Q(\mem[3][7] )
  );
  sky130_fd_sc_hd__dfstp_2 _1112_ (
    .CLK(rd_clk),
    .D(empty_next),
    .Q(empty),
    .SET_B(arst_n)
  );
  sky130_fd_sc_hd__dfxtp_2 _1113_ (
    .CLK(wr_clk),
    .D(_0104_),
    .Q(\mem[5][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1114_ (
    .CLK(wr_clk),
    .D(_0105_),
    .Q(\mem[5][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1115_ (
    .CLK(wr_clk),
    .D(_0106_),
    .Q(\mem[5][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1116_ (
    .CLK(wr_clk),
    .D(_0107_),
    .Q(\mem[5][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1117_ (
    .CLK(wr_clk),
    .D(_0108_),
    .Q(\mem[5][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1118_ (
    .CLK(wr_clk),
    .D(_0109_),
    .Q(\mem[5][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1119_ (
    .CLK(wr_clk),
    .D(_0110_),
    .Q(\mem[5][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1120_ (
    .CLK(wr_clk),
    .D(_0111_),
    .Q(\mem[5][7] )
  );
  sky130_fd_sc_hd__dfstp_2 _1121_ (
    .CLK(rd_clk),
    .D(aempty_next),
    .Q(aempty),
    .SET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1122_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[0] ),
    .Q(\rd_bin[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1123_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[1] ),
    .Q(\rd_bin[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1124_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[2] ),
    .Q(\rd_bin[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1125_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[3] ),
    .Q(\rd_bin[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1126_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[4] ),
    .Q(\rd_bin[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1127_ (
    .CLK(rd_clk),
    .D(\rd_gray_next[0] ),
    .Q(\rd_gray[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1128_ (
    .CLK(rd_clk),
    .D(\rd_gray_next[1] ),
    .Q(\rd_gray[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1129_ (
    .CLK(rd_clk),
    .D(\rd_gray_next[2] ),
    .Q(\rd_gray[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1130_ (
    .CLK(rd_clk),
    .D(\rd_gray_next[3] ),
    .Q(\rd_gray[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1131_ (
    .CLK(wr_clk),
    .D(full_next),
    .Q(full),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1132_ (
    .CLK(wr_clk),
    .D(afull_next),
    .Q(afull),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1133_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[0] ),
    .Q(\wr_bin[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1134_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[1] ),
    .Q(\wr_bin[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1135_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[2] ),
    .Q(\wr_bin[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1136_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[3] ),
    .Q(\wr_bin[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1137_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[4] ),
    .Q(\wr_bin[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfxtp_2 _1138_ (
    .CLK(wr_clk),
    .D(_0112_),
    .Q(\mem[4][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1139_ (
    .CLK(wr_clk),
    .D(_0113_),
    .Q(\mem[4][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1140_ (
    .CLK(wr_clk),
    .D(_0114_),
    .Q(\mem[4][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1141_ (
    .CLK(wr_clk),
    .D(_0115_),
    .Q(\mem[4][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1142_ (
    .CLK(wr_clk),
    .D(_0116_),
    .Q(\mem[4][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1143_ (
    .CLK(wr_clk),
    .D(_0117_),
    .Q(\mem[4][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1144_ (
    .CLK(wr_clk),
    .D(_0118_),
    .Q(\mem[4][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1145_ (
    .CLK(wr_clk),
    .D(_0119_),
    .Q(\mem[4][7] )
  );
  sky130_fd_sc_hd__dfrtp_2 _1146_ (
    .CLK(wr_clk),
    .D(\wr_gray_next[0] ),
    .Q(\wr_gray[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1147_ (
    .CLK(wr_clk),
    .D(\wr_gray_next[1] ),
    .Q(\wr_gray[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1148_ (
    .CLK(wr_clk),
    .D(\wr_gray_next[2] ),
    .Q(\wr_gray[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1149_ (
    .CLK(wr_clk),
    .D(\wr_gray_next[3] ),
    .Q(\wr_gray[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1150_ (
    .CLK(rd_clk),
    .D(\wr_gray[0] ),
    .Q(\wr_gray_sync1[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1151_ (
    .CLK(rd_clk),
    .D(\wr_gray[1] ),
    .Q(\wr_gray_sync1[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1152_ (
    .CLK(rd_clk),
    .D(\wr_gray[2] ),
    .Q(\wr_gray_sync1[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1153_ (
    .CLK(rd_clk),
    .D(\wr_gray[3] ),
    .Q(\wr_gray_sync1[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1154_ (
    .CLK(rd_clk),
    .D(\wr_bin[4] ),
    .Q(\wr_gray_sync1[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1155_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[0] ),
    .Q(\wr_gray_sync2[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1156_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[1] ),
    .Q(\wr_gray_sync2[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1157_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[2] ),
    .Q(\wr_gray_sync2[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1158_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[3] ),
    .Q(\wr_gray_sync2[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1159_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[4] ),
    .Q(\wr_bin_sync[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1160_ (
    .CLK(wr_clk),
    .D(\rd_gray[0] ),
    .Q(\rd_gray_sync1[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1161_ (
    .CLK(wr_clk),
    .D(\rd_gray[1] ),
    .Q(\rd_gray_sync1[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1162_ (
    .CLK(wr_clk),
    .D(\rd_gray[2] ),
    .Q(\rd_gray_sync1[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1163_ (
    .CLK(wr_clk),
    .D(\rd_gray[3] ),
    .Q(\rd_gray_sync1[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1164_ (
    .CLK(wr_clk),
    .D(\rd_bin[4] ),
    .Q(\rd_gray_sync1[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1165_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[0] ),
    .Q(\full_compare[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1166_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[1] ),
    .Q(\full_compare[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1167_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[2] ),
    .Q(\full_compare[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1168_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[3] ),
    .Q(\rd_gray_sync2[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1169_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[4] ),
    .Q(\rd_bin_sync[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfxtp_2 _1170_ (
    .CLK(wr_clk),
    .D(_0120_),
    .Q(\mem[15][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1171_ (
    .CLK(wr_clk),
    .D(_0121_),
    .Q(\mem[15][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1172_ (
    .CLK(wr_clk),
    .D(_0122_),
    .Q(\mem[15][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1173_ (
    .CLK(wr_clk),
    .D(_0123_),
    .Q(\mem[15][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1174_ (
    .CLK(wr_clk),
    .D(_0124_),
    .Q(\mem[15][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1175_ (
    .CLK(wr_clk),
    .D(_0125_),
    .Q(\mem[15][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1176_ (
    .CLK(wr_clk),
    .D(_0126_),
    .Q(\mem[15][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1177_ (
    .CLK(wr_clk),
    .D(_0127_),
    .Q(\mem[15][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1178_ (
    .CLK(wr_clk),
    .D(_0128_),
    .Q(\mem[9][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1179_ (
    .CLK(wr_clk),
    .D(_0129_),
    .Q(\mem[9][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1180_ (
    .CLK(wr_clk),
    .D(_0130_),
    .Q(\mem[9][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1181_ (
    .CLK(wr_clk),
    .D(_0131_),
    .Q(\mem[9][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1182_ (
    .CLK(wr_clk),
    .D(_0132_),
    .Q(\mem[9][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1183_ (
    .CLK(wr_clk),
    .D(_0133_),
    .Q(\mem[9][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1184_ (
    .CLK(wr_clk),
    .D(_0134_),
    .Q(\mem[9][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1185_ (
    .CLK(wr_clk),
    .D(_0135_),
    .Q(\mem[9][7] )
  );
endmodule
