/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module async_fifo(wr_clk, rd_clk, arst_n, wr_en, wr_data, rd_en, rd_data, afull_threshold, aempty_threshold, full, empty, afull, aempty);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  output aempty;
  wire aempty;
  wire aempty_next;
  input [4:0] aempty_threshold;
  wire [4:0] aempty_threshold;
  output afull;
  wire afull;
  wire afull_next;
  input [4:0] afull_threshold;
  wire [4:0] afull_threshold;
  input arst_n;
  wire arst_n;
  output empty;
  wire empty;
  wire empty_next;
  output full;
  wire full;
  wire \full_compare[0] ;
  wire \full_compare[1] ;
  wire \full_compare[2] ;
  wire full_next;
  wire \mem[0][0] ;
  wire \mem[0][1] ;
  wire \mem[0][2] ;
  wire \mem[0][3] ;
  wire \mem[0][4] ;
  wire \mem[0][5] ;
  wire \mem[0][6] ;
  wire \mem[0][7] ;
  wire \mem[10][0] ;
  wire \mem[10][1] ;
  wire \mem[10][2] ;
  wire \mem[10][3] ;
  wire \mem[10][4] ;
  wire \mem[10][5] ;
  wire \mem[10][6] ;
  wire \mem[10][7] ;
  wire \mem[11][0] ;
  wire \mem[11][1] ;
  wire \mem[11][2] ;
  wire \mem[11][3] ;
  wire \mem[11][4] ;
  wire \mem[11][5] ;
  wire \mem[11][6] ;
  wire \mem[11][7] ;
  wire \mem[12][0] ;
  wire \mem[12][1] ;
  wire \mem[12][2] ;
  wire \mem[12][3] ;
  wire \mem[12][4] ;
  wire \mem[12][5] ;
  wire \mem[12][6] ;
  wire \mem[12][7] ;
  wire \mem[13][0] ;
  wire \mem[13][1] ;
  wire \mem[13][2] ;
  wire \mem[13][3] ;
  wire \mem[13][4] ;
  wire \mem[13][5] ;
  wire \mem[13][6] ;
  wire \mem[13][7] ;
  wire \mem[14][0] ;
  wire \mem[14][1] ;
  wire \mem[14][2] ;
  wire \mem[14][3] ;
  wire \mem[14][4] ;
  wire \mem[14][5] ;
  wire \mem[14][6] ;
  wire \mem[14][7] ;
  wire \mem[15][0] ;
  wire \mem[15][1] ;
  wire \mem[15][2] ;
  wire \mem[15][3] ;
  wire \mem[15][4] ;
  wire \mem[15][5] ;
  wire \mem[15][6] ;
  wire \mem[15][7] ;
  wire \mem[1][0] ;
  wire \mem[1][1] ;
  wire \mem[1][2] ;
  wire \mem[1][3] ;
  wire \mem[1][4] ;
  wire \mem[1][5] ;
  wire \mem[1][6] ;
  wire \mem[1][7] ;
  wire \mem[2][0] ;
  wire \mem[2][1] ;
  wire \mem[2][2] ;
  wire \mem[2][3] ;
  wire \mem[2][4] ;
  wire \mem[2][5] ;
  wire \mem[2][6] ;
  wire \mem[2][7] ;
  wire \mem[3][0] ;
  wire \mem[3][1] ;
  wire \mem[3][2] ;
  wire \mem[3][3] ;
  wire \mem[3][4] ;
  wire \mem[3][5] ;
  wire \mem[3][6] ;
  wire \mem[3][7] ;
  wire \mem[4][0] ;
  wire \mem[4][1] ;
  wire \mem[4][2] ;
  wire \mem[4][3] ;
  wire \mem[4][4] ;
  wire \mem[4][5] ;
  wire \mem[4][6] ;
  wire \mem[4][7] ;
  wire \mem[5][0] ;
  wire \mem[5][1] ;
  wire \mem[5][2] ;
  wire \mem[5][3] ;
  wire \mem[5][4] ;
  wire \mem[5][5] ;
  wire \mem[5][6] ;
  wire \mem[5][7] ;
  wire \mem[6][0] ;
  wire \mem[6][1] ;
  wire \mem[6][2] ;
  wire \mem[6][3] ;
  wire \mem[6][4] ;
  wire \mem[6][5] ;
  wire \mem[6][6] ;
  wire \mem[6][7] ;
  wire \mem[7][0] ;
  wire \mem[7][1] ;
  wire \mem[7][2] ;
  wire \mem[7][3] ;
  wire \mem[7][4] ;
  wire \mem[7][5] ;
  wire \mem[7][6] ;
  wire \mem[7][7] ;
  wire \mem[8][0] ;
  wire \mem[8][1] ;
  wire \mem[8][2] ;
  wire \mem[8][3] ;
  wire \mem[8][4] ;
  wire \mem[8][5] ;
  wire \mem[8][6] ;
  wire \mem[8][7] ;
  wire \mem[9][0] ;
  wire \mem[9][1] ;
  wire \mem[9][2] ;
  wire \mem[9][3] ;
  wire \mem[9][4] ;
  wire \mem[9][5] ;
  wire \mem[9][6] ;
  wire \mem[9][7] ;
  wire \rd_bin[0] ;
  wire \rd_bin[1] ;
  wire \rd_bin[2] ;
  wire \rd_bin[3] ;
  wire \rd_bin[4] ;
  wire \rd_bin_next[0] ;
  wire \rd_bin_next[1] ;
  wire \rd_bin_next[2] ;
  wire \rd_bin_next[3] ;
  wire \rd_bin_next[4] ;
  wire \rd_bin_sync[4] ;
  input rd_clk;
  wire rd_clk;
  output [7:0] rd_data;
  wire [7:0] rd_data;
  input rd_en;
  wire rd_en;
  wire \rd_gray[0] ;
  wire \rd_gray[1] ;
  wire \rd_gray[2] ;
  wire \rd_gray[3] ;
  wire \rd_gray_next[0] ;
  wire \rd_gray_next[1] ;
  wire \rd_gray_next[2] ;
  wire \rd_gray_next[3] ;
  wire \rd_gray_sync1[0] ;
  wire \rd_gray_sync1[1] ;
  wire \rd_gray_sync1[2] ;
  wire \rd_gray_sync1[3] ;
  wire \rd_gray_sync1[4] ;
  wire \rd_gray_sync2[3] ;
  wire \wr_bin[0] ;
  wire \wr_bin[1] ;
  wire \wr_bin[2] ;
  wire \wr_bin[3] ;
  wire \wr_bin[4] ;
  wire \wr_bin_next[0] ;
  wire \wr_bin_next[1] ;
  wire \wr_bin_next[2] ;
  wire \wr_bin_next[3] ;
  wire \wr_bin_next[4] ;
  wire \wr_bin_sync[4] ;
  input wr_clk;
  wire wr_clk;
  input [7:0] wr_data;
  wire [7:0] wr_data;
  input wr_en;
  wire wr_en;
  wire \wr_gray[0] ;
  wire \wr_gray[1] ;
  wire \wr_gray[2] ;
  wire \wr_gray[3] ;
  wire \wr_gray_next[0] ;
  wire \wr_gray_next[1] ;
  wire \wr_gray_next[2] ;
  wire \wr_gray_next[3] ;
  wire \wr_gray_sync1[0] ;
  wire \wr_gray_sync1[1] ;
  wire \wr_gray_sync1[2] ;
  wire \wr_gray_sync1[3] ;
  wire \wr_gray_sync1[4] ;
  wire \wr_gray_sync2[0] ;
  wire \wr_gray_sync2[1] ;
  wire \wr_gray_sync2[2] ;
  wire \wr_gray_sync2[3] ;
  sky130_fd_sc_hd__inv_2 _0654_ (
    .A(\rd_gray_sync2[3] ),
    .Y(_0142_)
  );
  sky130_fd_sc_hd__nand2_2 _0655_ (
    .A(_0142_),
    .B(\rd_bin_sync[4] ),
    .Y(_0143_)
  );
  sky130_fd_sc_hd__inv_2 _0656_ (
    .A(\rd_bin_sync[4] ),
    .Y(_0144_)
  );
  sky130_fd_sc_hd__nand2_2 _0657_ (
    .A(_0144_),
    .B(\rd_gray_sync2[3] ),
    .Y(_0145_)
  );
  sky130_fd_sc_hd__inv_2 _0658_ (
    .A(\full_compare[2] ),
    .Y(_0146_)
  );
  sky130_fd_sc_hd__nand3_2 _0659_ (
    .A(_0143_),
    .B(_0145_),
    .C(_0146_),
    .Y(_0147_)
  );
  sky130_fd_sc_hd__nand2_2 _0660_ (
    .A(_0144_),
    .B(_0142_),
    .Y(_0148_)
  );
  sky130_fd_sc_hd__nand2_2 _0661_ (
    .A(\rd_bin_sync[4] ),
    .B(\rd_gray_sync2[3] ),
    .Y(_0149_)
  );
  sky130_fd_sc_hd__nand3_2 _0662_ (
    .A(_0148_),
    .B(\full_compare[2] ),
    .C(_0149_),
    .Y(_0150_)
  );
  sky130_fd_sc_hd__nand2_2 _0663_ (
    .A(_0147_),
    .B(_0150_),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__inv_2 _0664_ (
    .A(\full_compare[1] ),
    .Y(_0152_)
  );
  sky130_fd_sc_hd__nand2_2 _0665_ (
    .A(_0151_),
    .B(_0152_),
    .Y(_0153_)
  );
  sky130_fd_sc_hd__nand3_2 _0666_ (
    .A(_0147_),
    .B(_0150_),
    .C(\full_compare[1] ),
    .Y(_0154_)
  );
  sky130_fd_sc_hd__nand3_2 _0667_ (
    .A(_0153_),
    .B(_0154_),
    .C(\full_compare[0] ),
    .Y(_0155_)
  );
  sky130_fd_sc_hd__nand2_2 _0668_ (
    .A(_0151_),
    .B(\full_compare[1] ),
    .Y(_0156_)
  );
  sky130_fd_sc_hd__nand3_2 _0669_ (
    .A(_0147_),
    .B(_0150_),
    .C(_0152_),
    .Y(_0157_)
  );
  sky130_fd_sc_hd__inv_2 _0670_ (
    .A(\full_compare[0] ),
    .Y(_0158_)
  );
  sky130_fd_sc_hd__nand3_2 _0671_ (
    .A(_0156_),
    .B(_0157_),
    .C(_0158_),
    .Y(_0159_)
  );
  sky130_fd_sc_hd__nand2_2 _0672_ (
    .A(_0155_),
    .B(_0159_),
    .Y(_0160_)
  );
  sky130_fd_sc_hd__inv_2 _0673_ (
    .A(_0160_),
    .Y(_0161_)
  );
  sky130_fd_sc_hd__inv_2 _0674_ (
    .A(\wr_bin[0] ),
    .Y(_0162_)
  );
  sky130_fd_sc_hd__nand3_2 _0675_ (
    .A(_0156_),
    .B(_0157_),
    .C(\wr_bin[1] ),
    .Y(_0163_)
  );
  sky130_fd_sc_hd__inv_2 _0676_ (
    .A(\wr_bin[1] ),
    .Y(_0164_)
  );
  sky130_fd_sc_hd__nand3_2 _0677_ (
    .A(_0153_),
    .B(_0154_),
    .C(_0164_),
    .Y(_0165_)
  );
  sky130_fd_sc_hd__nand2_2 _0678_ (
    .A(_0163_),
    .B(_0165_),
    .Y(_0166_)
  );
  sky130_fd_sc_hd__nand3_2 _0679_ (
    .A(_0161_),
    .B(_0162_),
    .C(_0166_),
    .Y(_0167_)
  );
  sky130_fd_sc_hd__inv_2 _0680_ (
    .A(afull_threshold[1]),
    .Y(_0168_)
  );
  sky130_fd_sc_hd__nand3_2 _0681_ (
    .A(_0155_),
    .B(_0159_),
    .C(_0162_),
    .Y(_0169_)
  );
  sky130_fd_sc_hd__inv_2 _0682_ (
    .A(_0166_),
    .Y(_0170_)
  );
  sky130_fd_sc_hd__nand2_2 _0683_ (
    .A(_0169_),
    .B(_0170_),
    .Y(_0171_)
  );
  sky130_fd_sc_hd__nand3_2 _0684_ (
    .A(_0167_),
    .B(_0168_),
    .C(_0171_),
    .Y(_0172_)
  );
  sky130_fd_sc_hd__nand2_2 _0685_ (
    .A(_0169_),
    .B(afull_threshold[0]),
    .Y(_0173_)
  );
  sky130_fd_sc_hd__nor2_2 _0686_ (
    .A(_0162_),
    .B(_0161_),
    .Y(_0174_)
  );
  sky130_fd_sc_hd__nor2_2 _0687_ (
    .A(_0173_),
    .B(_0174_),
    .Y(_0175_)
  );
  sky130_fd_sc_hd__nand2_2 _0688_ (
    .A(_0172_),
    .B(_0175_),
    .Y(_0176_)
  );
  sky130_fd_sc_hd__nand2_2 _0689_ (
    .A(_0167_),
    .B(_0171_),
    .Y(_0177_)
  );
  sky130_fd_sc_hd__nand2_2 _0690_ (
    .A(_0177_),
    .B(afull_threshold[1]),
    .Y(_0178_)
  );
  sky130_fd_sc_hd__nand2_2 _0691_ (
    .A(_0176_),
    .B(_0178_),
    .Y(_0179_)
  );
  sky130_fd_sc_hd__nand2_2 _0692_ (
    .A(_0171_),
    .B(_0163_),
    .Y(_0180_)
  );
  sky130_fd_sc_hd__or2_2 _0693_ (
    .A(\wr_bin[2] ),
    .B(_0151_),
    .X(_0181_)
  );
  sky130_fd_sc_hd__nand2_2 _0694_ (
    .A(_0151_),
    .B(\wr_bin[2] ),
    .Y(_0182_)
  );
  sky130_fd_sc_hd__nand2_2 _0695_ (
    .A(_0181_),
    .B(_0182_),
    .Y(_0183_)
  );
  sky130_fd_sc_hd__inv_2 _0696_ (
    .A(_0183_),
    .Y(_0184_)
  );
  sky130_fd_sc_hd__nand2_2 _0697_ (
    .A(_0180_),
    .B(_0184_),
    .Y(_0185_)
  );
  sky130_fd_sc_hd__nand3_2 _0698_ (
    .A(_0171_),
    .B(_0163_),
    .C(_0183_),
    .Y(_0186_)
  );
  sky130_fd_sc_hd__inv_2 _0699_ (
    .A(afull_threshold[2]),
    .Y(_0187_)
  );
  sky130_fd_sc_hd__nand3_2 _0700_ (
    .A(_0185_),
    .B(_0186_),
    .C(_0187_),
    .Y(_0188_)
  );
  sky130_fd_sc_hd__nand2_2 _0701_ (
    .A(_0179_),
    .B(_0188_),
    .Y(_0189_)
  );
  sky130_fd_sc_hd__a21o_2 _0702_ (
    .A1(_0185_),
    .A2(_0186_),
    .B1(_0187_),
    .X(_0190_)
  );
  sky130_fd_sc_hd__nand2_2 _0703_ (
    .A(_0189_),
    .B(_0190_),
    .Y(_0191_)
  );
  sky130_fd_sc_hd__nand2_2 _0704_ (
    .A(_0185_),
    .B(_0182_),
    .Y(_0192_)
  );
  sky130_fd_sc_hd__nand2_2 _0705_ (
    .A(_0148_),
    .B(_0149_),
    .Y(_0193_)
  );
  sky130_fd_sc_hd__or2_2 _0706_ (
    .A(\wr_bin[3] ),
    .B(_0193_),
    .X(_0194_)
  );
  sky130_fd_sc_hd__nand2_2 _0707_ (
    .A(_0193_),
    .B(\wr_bin[3] ),
    .Y(_0195_)
  );
  sky130_fd_sc_hd__and2_2 _0708_ (
    .A(_0194_),
    .B(_0195_),
    .X(_0196_)
  );
  sky130_fd_sc_hd__nand2_2 _0709_ (
    .A(_0192_),
    .B(_0196_),
    .Y(_0197_)
  );
  sky130_fd_sc_hd__inv_2 _0710_ (
    .A(_0196_),
    .Y(_0198_)
  );
  sky130_fd_sc_hd__nand3_2 _0711_ (
    .A(_0185_),
    .B(_0198_),
    .C(_0182_),
    .Y(_0199_)
  );
  sky130_fd_sc_hd__nand3b_2 _0712_ (
    .A_N(afull_threshold[3]),
    .B(_0197_),
    .C(_0199_),
    .Y(_0200_)
  );
  sky130_fd_sc_hd__nand2_2 _0713_ (
    .A(_0191_),
    .B(_0200_),
    .Y(_0201_)
  );
  sky130_fd_sc_hd__nand3_2 _0714_ (
    .A(_0180_),
    .B(_0196_),
    .C(_0184_),
    .Y(_0202_)
  );
  sky130_fd_sc_hd__o21ai_2 _0715_ (
    .A1(_0182_),
    .A2(_0198_),
    .B1(_0195_),
    .Y(_0203_)
  );
  sky130_fd_sc_hd__inv_2 _0716_ (
    .A(_0203_),
    .Y(_0204_)
  );
  sky130_fd_sc_hd__nand2_2 _0717_ (
    .A(_0202_),
    .B(_0204_),
    .Y(_0205_)
  );
  sky130_fd_sc_hd__xnor2_2 _0718_ (
    .A(\wr_bin[4] ),
    .B(\rd_bin_sync[4] ),
    .Y(_0206_)
  );
  sky130_fd_sc_hd__inv_2 _0719_ (
    .A(_0206_),
    .Y(_0207_)
  );
  sky130_fd_sc_hd__nand2_2 _0720_ (
    .A(_0205_),
    .B(_0207_),
    .Y(_0208_)
  );
  sky130_fd_sc_hd__nand3_2 _0721_ (
    .A(_0202_),
    .B(_0204_),
    .C(_0206_),
    .Y(_0209_)
  );
  sky130_fd_sc_hd__nand3_2 _0722_ (
    .A(_0208_),
    .B(afull_threshold[4]),
    .C(_0209_),
    .Y(_0210_)
  );
  sky130_fd_sc_hd__nand2_2 _0723_ (
    .A(_0197_),
    .B(_0199_),
    .Y(_0211_)
  );
  sky130_fd_sc_hd__nand2_2 _0724_ (
    .A(_0211_),
    .B(afull_threshold[3]),
    .Y(_0212_)
  );
  sky130_fd_sc_hd__nand3_2 _0725_ (
    .A(_0201_),
    .B(_0210_),
    .C(_0212_),
    .Y(_0213_)
  );
  sky130_fd_sc_hd__a21o_2 _0726_ (
    .A1(_0208_),
    .A2(_0209_),
    .B1(afull_threshold[4]),
    .X(_0214_)
  );
  sky130_fd_sc_hd__nand2_2 _0727_ (
    .A(_0213_),
    .B(_0214_),
    .Y(afull_next)
  );
  sky130_fd_sc_hd__inv_2 _0728_ (
    .A(\wr_bin_sync[4] ),
    .Y(_0215_)
  );
  sky130_fd_sc_hd__nand2_2 _0729_ (
    .A(_0215_),
    .B(\wr_gray_sync2[3] ),
    .Y(_0216_)
  );
  sky130_fd_sc_hd__inv_2 _0730_ (
    .A(\wr_gray_sync2[3] ),
    .Y(_0217_)
  );
  sky130_fd_sc_hd__nand2_2 _0731_ (
    .A(_0217_),
    .B(\wr_bin_sync[4] ),
    .Y(_0218_)
  );
  sky130_fd_sc_hd__inv_2 _0732_ (
    .A(\wr_gray_sync2[2] ),
    .Y(_0219_)
  );
  sky130_fd_sc_hd__nand3_2 _0733_ (
    .A(_0216_),
    .B(_0218_),
    .C(_0219_),
    .Y(_0220_)
  );
  sky130_fd_sc_hd__nand2_2 _0734_ (
    .A(_0217_),
    .B(_0215_),
    .Y(_0221_)
  );
  sky130_fd_sc_hd__nand2_2 _0735_ (
    .A(\wr_gray_sync2[3] ),
    .B(\wr_bin_sync[4] ),
    .Y(_0222_)
  );
  sky130_fd_sc_hd__nand3_2 _0736_ (
    .A(_0221_),
    .B(\wr_gray_sync2[2] ),
    .C(_0222_),
    .Y(_0223_)
  );
  sky130_fd_sc_hd__nand2_2 _0737_ (
    .A(_0220_),
    .B(_0223_),
    .Y(_0224_)
  );
  sky130_fd_sc_hd__inv_2 _0738_ (
    .A(\wr_gray_sync2[1] ),
    .Y(_0225_)
  );
  sky130_fd_sc_hd__nand2_2 _0739_ (
    .A(_0224_),
    .B(_0225_),
    .Y(_0226_)
  );
  sky130_fd_sc_hd__nand3_2 _0740_ (
    .A(_0220_),
    .B(_0223_),
    .C(\wr_gray_sync2[1] ),
    .Y(_0227_)
  );
  sky130_fd_sc_hd__inv_2 _0741_ (
    .A(\wr_gray_sync2[0] ),
    .Y(_0228_)
  );
  sky130_fd_sc_hd__nand3_2 _0742_ (
    .A(_0226_),
    .B(_0227_),
    .C(_0228_),
    .Y(_0229_)
  );
  sky130_fd_sc_hd__nand2_2 _0743_ (
    .A(_0224_),
    .B(\wr_gray_sync2[1] ),
    .Y(_0230_)
  );
  sky130_fd_sc_hd__nand3_2 _0744_ (
    .A(_0220_),
    .B(_0223_),
    .C(_0225_),
    .Y(_0231_)
  );
  sky130_fd_sc_hd__nand3_2 _0745_ (
    .A(_0230_),
    .B(_0231_),
    .C(\wr_gray_sync2[0] ),
    .Y(_0232_)
  );
  sky130_fd_sc_hd__nand3_2 _0746_ (
    .A(_0229_),
    .B(_0232_),
    .C(\rd_bin[0] ),
    .Y(_0233_)
  );
  sky130_fd_sc_hd__nand3_2 _0747_ (
    .A(_0226_),
    .B(_0227_),
    .C(\wr_gray_sync2[0] ),
    .Y(_0234_)
  );
  sky130_fd_sc_hd__nand3_2 _0748_ (
    .A(_0230_),
    .B(_0231_),
    .C(_0228_),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__inv_2 _0749_ (
    .A(\rd_bin[0] ),
    .Y(_0236_)
  );
  sky130_fd_sc_hd__buf_1 _0750_ (
    .A(_0236_),
    .X(_0237_)
  );
  sky130_fd_sc_hd__nand3_2 _0751_ (
    .A(_0234_),
    .B(_0235_),
    .C(_0237_),
    .Y(_0238_)
  );
  sky130_fd_sc_hd__nand2_2 _0752_ (
    .A(_0233_),
    .B(_0238_),
    .Y(_0239_)
  );
  sky130_fd_sc_hd__inv_2 _0753_ (
    .A(aempty_threshold[0]),
    .Y(_0240_)
  );
  sky130_fd_sc_hd__inv_2 _0754_ (
    .A(aempty_threshold[1]),
    .Y(_0241_)
  );
  sky130_fd_sc_hd__nand3_2 _0755_ (
    .A(_0239_),
    .B(_0240_),
    .C(_0241_),
    .Y(_0242_)
  );
  sky130_fd_sc_hd__nand2_2 _0756_ (
    .A(_0234_),
    .B(_0235_),
    .Y(_0243_)
  );
  sky130_fd_sc_hd__inv_2 _0757_ (
    .A(\rd_bin[1] ),
    .Y(_0244_)
  );
  sky130_fd_sc_hd__nand3_2 _0758_ (
    .A(_0226_),
    .B(_0227_),
    .C(_0244_),
    .Y(_0245_)
  );
  sky130_fd_sc_hd__nand3_2 _0759_ (
    .A(_0230_),
    .B(_0231_),
    .C(\rd_bin[1] ),
    .Y(_0246_)
  );
  sky130_fd_sc_hd__nand2_2 _0760_ (
    .A(_0245_),
    .B(_0246_),
    .Y(_0247_)
  );
  sky130_fd_sc_hd__nand3_2 _0761_ (
    .A(_0243_),
    .B(_0247_),
    .C(\rd_bin[0] ),
    .Y(_0248_)
  );
  sky130_fd_sc_hd__inv_2 _0762_ (
    .A(_0247_),
    .Y(_0249_)
  );
  sky130_fd_sc_hd__nand2_2 _0763_ (
    .A(_0233_),
    .B(_0249_),
    .Y(_0250_)
  );
  sky130_fd_sc_hd__nand2_2 _0764_ (
    .A(_0248_),
    .B(_0250_),
    .Y(_0251_)
  );
  sky130_fd_sc_hd__nand2_2 _0765_ (
    .A(_0242_),
    .B(_0251_),
    .Y(_0252_)
  );
  sky130_fd_sc_hd__nand2_2 _0766_ (
    .A(_0239_),
    .B(_0240_),
    .Y(_0253_)
  );
  sky130_fd_sc_hd__nand2_2 _0767_ (
    .A(_0253_),
    .B(aempty_threshold[1]),
    .Y(_0254_)
  );
  sky130_fd_sc_hd__nand2_2 _0768_ (
    .A(_0252_),
    .B(_0254_),
    .Y(_0255_)
  );
  sky130_fd_sc_hd__nand2_2 _0769_ (
    .A(_0250_),
    .B(_0245_),
    .Y(_0256_)
  );
  sky130_fd_sc_hd__or2_2 _0770_ (
    .A(\rd_bin[2] ),
    .B(_0224_),
    .X(_0257_)
  );
  sky130_fd_sc_hd__nand2_2 _0771_ (
    .A(_0224_),
    .B(\rd_bin[2] ),
    .Y(_0258_)
  );
  sky130_fd_sc_hd__nand2_2 _0772_ (
    .A(_0257_),
    .B(_0258_),
    .Y(_0259_)
  );
  sky130_fd_sc_hd__inv_2 _0773_ (
    .A(_0259_),
    .Y(_0260_)
  );
  sky130_fd_sc_hd__nand2_2 _0774_ (
    .A(_0256_),
    .B(_0260_),
    .Y(_0261_)
  );
  sky130_fd_sc_hd__inv_2 _0775_ (
    .A(aempty_threshold[2]),
    .Y(_0262_)
  );
  sky130_fd_sc_hd__nand3_2 _0776_ (
    .A(_0250_),
    .B(_0245_),
    .C(_0259_),
    .Y(_0263_)
  );
  sky130_fd_sc_hd__nand3_2 _0777_ (
    .A(_0261_),
    .B(_0262_),
    .C(_0263_),
    .Y(_0264_)
  );
  sky130_fd_sc_hd__nand2_2 _0778_ (
    .A(_0255_),
    .B(_0264_),
    .Y(_0265_)
  );
  sky130_fd_sc_hd__nand2_2 _0779_ (
    .A(_0261_),
    .B(_0263_),
    .Y(_0266_)
  );
  sky130_fd_sc_hd__nand2_2 _0780_ (
    .A(_0266_),
    .B(aempty_threshold[2]),
    .Y(_0267_)
  );
  sky130_fd_sc_hd__nand2_2 _0781_ (
    .A(_0265_),
    .B(_0267_),
    .Y(_0268_)
  );
  sky130_fd_sc_hd__nand2_2 _0782_ (
    .A(_0261_),
    .B(_0257_),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__nand2_2 _0783_ (
    .A(_0221_),
    .B(_0222_),
    .Y(_0270_)
  );
  sky130_fd_sc_hd__or2_2 _0784_ (
    .A(\rd_bin[3] ),
    .B(_0270_),
    .X(_0271_)
  );
  sky130_fd_sc_hd__nand2_2 _0785_ (
    .A(_0270_),
    .B(\rd_bin[3] ),
    .Y(_0272_)
  );
  sky130_fd_sc_hd__nand2_2 _0786_ (
    .A(_0271_),
    .B(_0272_),
    .Y(_0273_)
  );
  sky130_fd_sc_hd__inv_2 _0787_ (
    .A(_0273_),
    .Y(_0274_)
  );
  sky130_fd_sc_hd__nand2_2 _0788_ (
    .A(_0269_),
    .B(_0274_),
    .Y(_0275_)
  );
  sky130_fd_sc_hd__inv_2 _0789_ (
    .A(aempty_threshold[3]),
    .Y(_0276_)
  );
  sky130_fd_sc_hd__nand3_2 _0790_ (
    .A(_0261_),
    .B(_0273_),
    .C(_0257_),
    .Y(_0277_)
  );
  sky130_fd_sc_hd__nand3_2 _0791_ (
    .A(_0275_),
    .B(_0276_),
    .C(_0277_),
    .Y(_0278_)
  );
  sky130_fd_sc_hd__nand2_2 _0792_ (
    .A(_0268_),
    .B(_0278_),
    .Y(_0279_)
  );
  sky130_fd_sc_hd__nand2_2 _0793_ (
    .A(_0275_),
    .B(_0277_),
    .Y(_0280_)
  );
  sky130_fd_sc_hd__nand2_2 _0794_ (
    .A(_0280_),
    .B(aempty_threshold[3]),
    .Y(_0281_)
  );
  sky130_fd_sc_hd__nand2_2 _0795_ (
    .A(_0279_),
    .B(_0281_),
    .Y(_0282_)
  );
  sky130_fd_sc_hd__nand2_2 _0796_ (
    .A(_0275_),
    .B(_0271_),
    .Y(_0283_)
  );
  sky130_fd_sc_hd__xnor2_2 _0797_ (
    .A(\wr_bin_sync[4] ),
    .B(\rd_bin[4] ),
    .Y(_0284_)
  );
  sky130_fd_sc_hd__nand2_2 _0798_ (
    .A(_0283_),
    .B(_0284_),
    .Y(_0285_)
  );
  sky130_fd_sc_hd__inv_2 _0799_ (
    .A(aempty_threshold[4]),
    .Y(_0286_)
  );
  sky130_fd_sc_hd__inv_2 _0800_ (
    .A(_0284_),
    .Y(_0287_)
  );
  sky130_fd_sc_hd__nand3_2 _0801_ (
    .A(_0275_),
    .B(_0271_),
    .C(_0287_),
    .Y(_0288_)
  );
  sky130_fd_sc_hd__nand3_2 _0802_ (
    .A(_0285_),
    .B(_0286_),
    .C(_0288_),
    .Y(_0289_)
  );
  sky130_fd_sc_hd__nand2_2 _0803_ (
    .A(_0282_),
    .B(_0289_),
    .Y(_0290_)
  );
  sky130_fd_sc_hd__nand2_2 _0804_ (
    .A(_0285_),
    .B(_0288_),
    .Y(_0291_)
  );
  sky130_fd_sc_hd__nand2_2 _0805_ (
    .A(_0291_),
    .B(aempty_threshold[4]),
    .Y(_0292_)
  );
  sky130_fd_sc_hd__nand2_2 _0806_ (
    .A(_0290_),
    .B(_0292_),
    .Y(aempty_next)
  );
  sky130_fd_sc_hd__nor2b_4 _0807_ (
    .A(full),
    .B_N(wr_en),
    .Y(_0293_)
  );
  sky130_fd_sc_hd__or2_4 _0808_ (
    .A(\wr_bin[0] ),
    .B(_0293_),
    .X(_0294_)
  );
  sky130_fd_sc_hd__nand2_4 _0809_ (
    .A(_0293_),
    .B(\wr_bin[0] ),
    .Y(_0295_)
  );
  sky130_fd_sc_hd__nand2_2 _0810_ (
    .A(_0294_),
    .B(_0295_),
    .Y(_0296_)
  );
  sky130_fd_sc_hd__inv_2 _0811_ (
    .A(_0296_),
    .Y(\wr_bin_next[0] )
  );
  sky130_fd_sc_hd__nor2_8 _0812_ (
    .A(_0164_),
    .B(_0295_),
    .Y(_0297_)
  );
  sky130_fd_sc_hd__nand2_2 _0813_ (
    .A(_0295_),
    .B(_0164_),
    .Y(_0298_)
  );
  sky130_fd_sc_hd__and2b_2 _0814_ (
    .A_N(_0297_),
    .B(_0298_),
    .X(_0299_)
  );
  sky130_fd_sc_hd__buf_1 _0815_ (
    .A(_0299_),
    .X(\wr_bin_next[1] )
  );
  sky130_fd_sc_hd__nor2_2 _0816_ (
    .A(\wr_bin[2] ),
    .B(_0297_),
    .Y(_0300_)
  );
  sky130_fd_sc_hd__nand2_2 _0817_ (
    .A(_0297_),
    .B(\wr_bin[2] ),
    .Y(_0301_)
  );
  sky130_fd_sc_hd__and2b_2 _0818_ (
    .A_N(_0300_),
    .B(_0301_),
    .X(_0302_)
  );
  sky130_fd_sc_hd__buf_1 _0819_ (
    .A(_0302_),
    .X(\wr_bin_next[2] )
  );
  sky130_fd_sc_hd__inv_2 _0820_ (
    .A(\wr_bin[3] ),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__nand2_2 _0821_ (
    .A(_0301_),
    .B(_0303_),
    .Y(_0304_)
  );
  sky130_fd_sc_hd__xor2_4 _0822_ (
    .A(\wr_bin[4] ),
    .B(_0304_),
    .X(\wr_gray_next[3] )
  );
  sky130_fd_sc_hd__nand2_2 _0823_ (
    .A(\wr_gray_next[3] ),
    .B(_0142_),
    .Y(_0305_)
  );
  sky130_fd_sc_hd__or2_2 _0824_ (
    .A(_0142_),
    .B(\wr_gray_next[3] ),
    .X(_0306_)
  );
  sky130_fd_sc_hd__xor2_2 _0825_ (
    .A(_0303_),
    .B(_0300_),
    .X(\wr_gray_next[2] )
  );
  sky130_fd_sc_hd__or2_2 _0826_ (
    .A(\full_compare[2] ),
    .B(\wr_gray_next[2] ),
    .X(_0307_)
  );
  sky130_fd_sc_hd__nand2_2 _0827_ (
    .A(\wr_gray_next[2] ),
    .B(\full_compare[2] ),
    .Y(_0308_)
  );
  sky130_fd_sc_hd__xor2_4 _0828_ (
    .A(\wr_bin[1] ),
    .B(_0294_),
    .X(\wr_gray_next[0] )
  );
  sky130_fd_sc_hd__or2_4 _0829_ (
    .A(\full_compare[0] ),
    .B(\wr_gray_next[0] ),
    .X(_0309_)
  );
  sky130_fd_sc_hd__nand2_2 _0830_ (
    .A(\wr_gray_next[0] ),
    .B(\full_compare[0] ),
    .Y(_0310_)
  );
  sky130_fd_sc_hd__nand2_2 _0831_ (
    .A(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .Y(_0311_)
  );
  sky130_fd_sc_hd__inv_2 _0832_ (
    .A(_0311_),
    .Y(_0312_)
  );
  sky130_fd_sc_hd__nand2_2 _0833_ (
    .A(_0297_),
    .B(_0312_),
    .Y(_0313_)
  );
  sky130_fd_sc_hd__xor2_2 _0834_ (
    .A(_0207_),
    .B(_0313_),
    .X(_0314_)
  );
  sky130_fd_sc_hd__xor2_2 _0835_ (
    .A(\wr_bin[2] ),
    .B(_0298_),
    .X(\wr_gray_next[1] )
  );
  sky130_fd_sc_hd__xor2_2 _0836_ (
    .A(\full_compare[1] ),
    .B(\wr_gray_next[1] ),
    .X(_0315_)
  );
  sky130_fd_sc_hd__a211o_2 _0837_ (
    .A1(_0309_),
    .A2(_0310_),
    .B1(_0314_),
    .C1(_0315_),
    .X(_0316_)
  );
  sky130_fd_sc_hd__a221oi_4 _0838_ (
    .A1(_0305_),
    .A2(_0306_),
    .B1(_0307_),
    .B2(_0308_),
    .C1(_0316_),
    .Y(full_next)
  );
  sky130_fd_sc_hd__inv_4 _0839_ (
    .A(rd_en),
    .Y(_0317_)
  );
  sky130_fd_sc_hd__nor2_8 _0840_ (
    .A(empty),
    .B(_0317_),
    .Y(_0318_)
  );
  sky130_fd_sc_hd__or2_2 _0841_ (
    .A(\rd_bin[0] ),
    .B(_0318_),
    .X(_0319_)
  );
  sky130_fd_sc_hd__nand2_4 _0842_ (
    .A(_0318_),
    .B(\rd_bin[0] ),
    .Y(_0320_)
  );
  sky130_fd_sc_hd__nand2_2 _0843_ (
    .A(_0319_),
    .B(_0320_),
    .Y(_0321_)
  );
  sky130_fd_sc_hd__inv_2 _0844_ (
    .A(_0321_),
    .Y(\rd_bin_next[0] )
  );
  sky130_fd_sc_hd__nor2_4 _0845_ (
    .A(_0244_),
    .B(_0320_),
    .Y(_0322_)
  );
  sky130_fd_sc_hd__inv_2 _0846_ (
    .A(_0322_),
    .Y(_0323_)
  );
  sky130_fd_sc_hd__nand2_2 _0847_ (
    .A(_0320_),
    .B(_0244_),
    .Y(_0324_)
  );
  sky130_fd_sc_hd__and2_2 _0848_ (
    .A(_0323_),
    .B(_0324_),
    .X(_0325_)
  );
  sky130_fd_sc_hd__buf_1 _0849_ (
    .A(_0325_),
    .X(\rd_bin_next[1] )
  );
  sky130_fd_sc_hd__inv_2 _0850_ (
    .A(\rd_bin[2] ),
    .Y(_0326_)
  );
  sky130_fd_sc_hd__nand2_4 _0851_ (
    .A(_0323_),
    .B(_0326_),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__nand2_2 _0852_ (
    .A(_0322_),
    .B(\rd_bin[2] ),
    .Y(_0328_)
  );
  sky130_fd_sc_hd__and2_2 _0853_ (
    .A(_0327_),
    .B(_0328_),
    .X(_0329_)
  );
  sky130_fd_sc_hd__buf_1 _0854_ (
    .A(_0329_),
    .X(\rd_bin_next[2] )
  );
  sky130_fd_sc_hd__xor2_4 _0855_ (
    .A(\rd_bin[3] ),
    .B(_0327_),
    .X(\rd_gray_next[2] )
  );
  sky130_fd_sc_hd__xor2_2 _0856_ (
    .A(_0219_),
    .B(\rd_gray_next[2] ),
    .X(_0330_)
  );
  sky130_fd_sc_hd__inv_2 _0857_ (
    .A(\rd_bin[3] ),
    .Y(_0331_)
  );
  sky130_fd_sc_hd__nand2_4 _0858_ (
    .A(_0328_),
    .B(_0331_),
    .Y(_0332_)
  );
  sky130_fd_sc_hd__xor2_4 _0859_ (
    .A(\rd_bin[4] ),
    .B(_0332_),
    .X(\rd_gray_next[3] )
  );
  sky130_fd_sc_hd__or2_2 _0860_ (
    .A(_0217_),
    .B(\rd_gray_next[3] ),
    .X(_0333_)
  );
  sky130_fd_sc_hd__nand2_2 _0861_ (
    .A(\rd_gray_next[3] ),
    .B(_0217_),
    .Y(_0334_)
  );
  sky130_fd_sc_hd__and3_2 _0862_ (
    .A(_0330_),
    .B(_0333_),
    .C(_0334_),
    .X(_0335_)
  );
  sky130_fd_sc_hd__or2_4 _0863_ (
    .A(_0331_),
    .B(_0328_),
    .X(_0336_)
  );
  sky130_fd_sc_hd__or2_2 _0864_ (
    .A(_0287_),
    .B(_0336_),
    .X(_0337_)
  );
  sky130_fd_sc_hd__nand2_2 _0865_ (
    .A(_0336_),
    .B(_0287_),
    .Y(_0338_)
  );
  sky130_fd_sc_hd__xor2_4 _0866_ (
    .A(\rd_bin[1] ),
    .B(_0319_),
    .X(\rd_gray_next[0] )
  );
  sky130_fd_sc_hd__or2_2 _0867_ (
    .A(_0228_),
    .B(\rd_gray_next[0] ),
    .X(_0339_)
  );
  sky130_fd_sc_hd__nand2_2 _0868_ (
    .A(\rd_gray_next[0] ),
    .B(_0228_),
    .Y(_0340_)
  );
  sky130_fd_sc_hd__and4_2 _0869_ (
    .A(_0337_),
    .B(_0338_),
    .C(_0339_),
    .D(_0340_),
    .X(_0341_)
  );
  sky130_fd_sc_hd__xor2_2 _0870_ (
    .A(\rd_bin[2] ),
    .B(_0324_),
    .X(\rd_gray_next[1] )
  );
  sky130_fd_sc_hd__or2_2 _0871_ (
    .A(_0225_),
    .B(\rd_gray_next[1] ),
    .X(_0342_)
  );
  sky130_fd_sc_hd__nand2_2 _0872_ (
    .A(\rd_gray_next[1] ),
    .B(_0225_),
    .Y(_0343_)
  );
  sky130_fd_sc_hd__and4_4 _0873_ (
    .A(_0335_),
    .B(_0341_),
    .C(_0342_),
    .D(_0343_),
    .X(_0344_)
  );
  sky130_fd_sc_hd__buf_6 _0874_ (
    .A(_0344_),
    .X(empty_next)
  );
  sky130_fd_sc_hd__buf_2 _0875_ (
    .A(_0313_),
    .X(_0345_)
  );
  sky130_fd_sc_hd__nand2_2 _0876_ (
    .A(_0304_),
    .B(_0345_),
    .Y(_0346_)
  );
  sky130_fd_sc_hd__inv_2 _0877_ (
    .A(_0346_),
    .Y(\wr_bin_next[3] )
  );
  sky130_fd_sc_hd__xnor2_2 _0878_ (
    .A(\wr_bin[4] ),
    .B(_0345_),
    .Y(\wr_bin_next[4] )
  );
  sky130_fd_sc_hd__nand2_2 _0879_ (
    .A(_0336_),
    .B(_0332_),
    .Y(_0347_)
  );
  sky130_fd_sc_hd__inv_2 _0880_ (
    .A(_0347_),
    .Y(\rd_bin_next[3] )
  );
  sky130_fd_sc_hd__xnor2_2 _0881_ (
    .A(\rd_bin[4] ),
    .B(_0336_),
    .Y(\rd_bin_next[4] )
  );
  sky130_fd_sc_hd__buf_1 _0882_ (
    .A(_0318_),
    .X(_0348_)
  );
  sky130_fd_sc_hd__buf_1 _0883_ (
    .A(_0326_),
    .X(_0349_)
  );
  sky130_fd_sc_hd__mux2_2 _0884_ (
    .A0(\mem[14][0] ),
    .A1(\mem[15][0] ),
    .S(\rd_bin[0] ),
    .X(_0350_)
  );
  sky130_fd_sc_hd__mux2_2 _0885_ (
    .A0(\mem[12][0] ),
    .A1(\mem[13][0] ),
    .S(\rd_bin[0] ),
    .X(_0351_)
  );
  sky130_fd_sc_hd__buf_1 _0886_ (
    .A(_0244_),
    .X(_0352_)
  );
  sky130_fd_sc_hd__mux2_2 _0887_ (
    .A0(_0350_),
    .A1(_0351_),
    .S(_0352_),
    .X(_0353_)
  );
  sky130_fd_sc_hd__o21a_2 _0888_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[10][0] ),
    .B1(\rd_bin[1] ),
    .X(_0354_)
  );
  sky130_fd_sc_hd__buf_1 _0889_ (
    .A(_0236_),
    .X(_0355_)
  );
  sky130_fd_sc_hd__or2_2 _0890_ (
    .A(\mem[11][0] ),
    .B(_0355_),
    .X(_0356_)
  );
  sky130_fd_sc_hd__o21a_2 _0891_ (
    .A1(\mem[9][0] ),
    .A2(_0237_),
    .B1(_0352_),
    .X(_0357_)
  );
  sky130_fd_sc_hd__or2_2 _0892_ (
    .A(\rd_bin[0] ),
    .B(\mem[8][0] ),
    .X(_0358_)
  );
  sky130_fd_sc_hd__a221o_2 _0893_ (
    .A1(_0354_),
    .A2(_0356_),
    .B1(_0357_),
    .B2(_0358_),
    .C1(\rd_bin[2] ),
    .X(_0359_)
  );
  sky130_fd_sc_hd__o211a_2 _0894_ (
    .A1(_0349_),
    .A2(_0353_),
    .B1(\rd_bin[3] ),
    .C1(_0359_),
    .X(_0360_)
  );
  sky130_fd_sc_hd__or2_2 _0895_ (
    .A(\mem[7][0] ),
    .B(_0237_),
    .X(_0361_)
  );
  sky130_fd_sc_hd__o21a_2 _0896_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[6][0] ),
    .B1(\rd_bin[1] ),
    .X(_0362_)
  );
  sky130_fd_sc_hd__mux2_2 _0897_ (
    .A0(\mem[4][0] ),
    .A1(\mem[5][0] ),
    .S(\rd_bin[0] ),
    .X(_0363_)
  );
  sky130_fd_sc_hd__buf_1 _0898_ (
    .A(_0352_),
    .X(_0364_)
  );
  sky130_fd_sc_hd__a221o_2 _0899_ (
    .A1(_0361_),
    .A2(_0362_),
    .B1(_0363_),
    .B2(_0364_),
    .C1(_0349_),
    .X(_0365_)
  );
  sky130_fd_sc_hd__or2_2 _0900_ (
    .A(\mem[3][0] ),
    .B(_0237_),
    .X(_0366_)
  );
  sky130_fd_sc_hd__o21a_2 _0901_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[2][0] ),
    .B1(\rd_bin[1] ),
    .X(_0367_)
  );
  sky130_fd_sc_hd__mux2_2 _0902_ (
    .A0(\mem[0][0] ),
    .A1(\mem[1][0] ),
    .S(\rd_bin[0] ),
    .X(_0368_)
  );
  sky130_fd_sc_hd__a221o_2 _0903_ (
    .A1(_0366_),
    .A2(_0367_),
    .B1(_0368_),
    .B2(_0364_),
    .C1(\rd_bin[2] ),
    .X(_0369_)
  );
  sky130_fd_sc_hd__nand3_2 _0904_ (
    .A(_0365_),
    .B(_0369_),
    .C(_0331_),
    .Y(_0370_)
  );
  sky130_fd_sc_hd__nand2_2 _0905_ (
    .A(_0370_),
    .B(_0348_),
    .Y(_0371_)
  );
  sky130_fd_sc_hd__o22a_2 _0906_ (
    .A1(rd_data[0]),
    .A2(_0348_),
    .B1(_0360_),
    .B2(_0371_),
    .X(_0000_)
  );
  sky130_fd_sc_hd__or2_2 _0907_ (
    .A(\mem[7][1] ),
    .B(_0355_),
    .X(_0372_)
  );
  sky130_fd_sc_hd__o21a_2 _0908_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[6][1] ),
    .B1(\rd_bin[1] ),
    .X(_0373_)
  );
  sky130_fd_sc_hd__mux2_2 _0909_ (
    .A0(\mem[4][1] ),
    .A1(\mem[5][1] ),
    .S(\rd_bin[0] ),
    .X(_0374_)
  );
  sky130_fd_sc_hd__buf_1 _0910_ (
    .A(_0244_),
    .X(_0375_)
  );
  sky130_fd_sc_hd__a221o_2 _0911_ (
    .A1(_0372_),
    .A2(_0373_),
    .B1(_0374_),
    .B2(_0375_),
    .C1(_0326_),
    .X(_0376_)
  );
  sky130_fd_sc_hd__o21a_2 _0912_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[2][1] ),
    .B1(\rd_bin[1] ),
    .X(_0377_)
  );
  sky130_fd_sc_hd__or2_2 _0913_ (
    .A(\mem[3][1] ),
    .B(_0236_),
    .X(_0378_)
  );
  sky130_fd_sc_hd__buf_1 _0914_ (
    .A(_0236_),
    .X(_0379_)
  );
  sky130_fd_sc_hd__o21a_2 _0915_ (
    .A1(\mem[1][1] ),
    .A2(_0379_),
    .B1(_0244_),
    .X(_0380_)
  );
  sky130_fd_sc_hd__or2_2 _0916_ (
    .A(\rd_bin[0] ),
    .B(\mem[0][1] ),
    .X(_0381_)
  );
  sky130_fd_sc_hd__a221o_2 _0917_ (
    .A1(_0377_),
    .A2(_0378_),
    .B1(_0380_),
    .B2(_0381_),
    .C1(\rd_bin[2] ),
    .X(_0382_)
  );
  sky130_fd_sc_hd__and3_2 _0918_ (
    .A(_0376_),
    .B(_0382_),
    .C(_0331_),
    .X(_0383_)
  );
  sky130_fd_sc_hd__mux2_2 _0919_ (
    .A0(\mem[10][1] ),
    .A1(\mem[11][1] ),
    .S(\rd_bin[0] ),
    .X(_0384_)
  );
  sky130_fd_sc_hd__mux2_2 _0920_ (
    .A0(\mem[8][1] ),
    .A1(\mem[9][1] ),
    .S(\rd_bin[0] ),
    .X(_0385_)
  );
  sky130_fd_sc_hd__mux2_2 _0921_ (
    .A0(_0384_),
    .A1(_0385_),
    .S(_0352_),
    .X(_0386_)
  );
  sky130_fd_sc_hd__or2_2 _0922_ (
    .A(\mem[15][1] ),
    .B(_0237_),
    .X(_0387_)
  );
  sky130_fd_sc_hd__o21a_2 _0923_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[14][1] ),
    .B1(\rd_bin[1] ),
    .X(_0388_)
  );
  sky130_fd_sc_hd__mux2_2 _0924_ (
    .A0(\mem[12][1] ),
    .A1(\mem[13][1] ),
    .S(\rd_bin[0] ),
    .X(_0389_)
  );
  sky130_fd_sc_hd__a221o_2 _0925_ (
    .A1(_0387_),
    .A2(_0388_),
    .B1(_0389_),
    .B2(_0364_),
    .C1(_0349_),
    .X(_0390_)
  );
  sky130_fd_sc_hd__o211ai_2 _0926_ (
    .A1(\rd_bin[2] ),
    .A2(_0386_),
    .B1(\rd_bin[3] ),
    .C1(_0390_),
    .Y(_0391_)
  );
  sky130_fd_sc_hd__nand2_2 _0927_ (
    .A(_0391_),
    .B(_0348_),
    .Y(_0392_)
  );
  sky130_fd_sc_hd__o22a_2 _0928_ (
    .A1(rd_data[1]),
    .A2(_0348_),
    .B1(_0383_),
    .B2(_0392_),
    .X(_0001_)
  );
  sky130_fd_sc_hd__or2_2 _0929_ (
    .A(\mem[7][2] ),
    .B(_0355_),
    .X(_0393_)
  );
  sky130_fd_sc_hd__o21a_2 _0930_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[6][2] ),
    .B1(\rd_bin[1] ),
    .X(_0394_)
  );
  sky130_fd_sc_hd__mux2_2 _0931_ (
    .A0(\mem[4][2] ),
    .A1(\mem[5][2] ),
    .S(\rd_bin[0] ),
    .X(_0395_)
  );
  sky130_fd_sc_hd__a221o_2 _0932_ (
    .A1(_0393_),
    .A2(_0394_),
    .B1(_0395_),
    .B2(_0352_),
    .C1(_0326_),
    .X(_0396_)
  );
  sky130_fd_sc_hd__o21a_2 _0933_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[2][2] ),
    .B1(\rd_bin[1] ),
    .X(_0397_)
  );
  sky130_fd_sc_hd__or2_2 _0934_ (
    .A(\mem[3][2] ),
    .B(_0236_),
    .X(_0398_)
  );
  sky130_fd_sc_hd__o21a_2 _0935_ (
    .A1(\mem[1][2] ),
    .A2(_0379_),
    .B1(_0244_),
    .X(_0399_)
  );
  sky130_fd_sc_hd__or2_2 _0936_ (
    .A(\rd_bin[0] ),
    .B(\mem[0][2] ),
    .X(_0400_)
  );
  sky130_fd_sc_hd__a221o_2 _0937_ (
    .A1(_0397_),
    .A2(_0398_),
    .B1(_0399_),
    .B2(_0400_),
    .C1(\rd_bin[2] ),
    .X(_0401_)
  );
  sky130_fd_sc_hd__and3_2 _0938_ (
    .A(_0396_),
    .B(_0401_),
    .C(_0331_),
    .X(_0402_)
  );
  sky130_fd_sc_hd__mux2_2 _0939_ (
    .A0(\mem[10][2] ),
    .A1(\mem[11][2] ),
    .S(\rd_bin[0] ),
    .X(_0403_)
  );
  sky130_fd_sc_hd__mux2_2 _0940_ (
    .A0(\mem[8][2] ),
    .A1(\mem[9][2] ),
    .S(\rd_bin[0] ),
    .X(_0404_)
  );
  sky130_fd_sc_hd__mux2_2 _0941_ (
    .A0(_0403_),
    .A1(_0404_),
    .S(_0352_),
    .X(_0405_)
  );
  sky130_fd_sc_hd__or2_2 _0942_ (
    .A(\mem[15][2] ),
    .B(_0237_),
    .X(_0406_)
  );
  sky130_fd_sc_hd__o21a_2 _0943_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[14][2] ),
    .B1(\rd_bin[1] ),
    .X(_0407_)
  );
  sky130_fd_sc_hd__mux2_2 _0944_ (
    .A0(\mem[12][2] ),
    .A1(\mem[13][2] ),
    .S(\rd_bin[0] ),
    .X(_0408_)
  );
  sky130_fd_sc_hd__a221o_2 _0945_ (
    .A1(_0406_),
    .A2(_0407_),
    .B1(_0408_),
    .B2(_0364_),
    .C1(_0349_),
    .X(_0409_)
  );
  sky130_fd_sc_hd__o211ai_2 _0946_ (
    .A1(\rd_bin[2] ),
    .A2(_0405_),
    .B1(\rd_bin[3] ),
    .C1(_0409_),
    .Y(_0410_)
  );
  sky130_fd_sc_hd__nand2_2 _0947_ (
    .A(_0410_),
    .B(_0318_),
    .Y(_0411_)
  );
  sky130_fd_sc_hd__o22a_2 _0948_ (
    .A1(rd_data[2]),
    .A2(_0348_),
    .B1(_0402_),
    .B2(_0411_),
    .X(_0002_)
  );
  sky130_fd_sc_hd__mux2_2 _0949_ (
    .A0(\mem[14][3] ),
    .A1(\mem[15][3] ),
    .S(\rd_bin[0] ),
    .X(_0412_)
  );
  sky130_fd_sc_hd__mux2_2 _0950_ (
    .A0(\mem[12][3] ),
    .A1(\mem[13][3] ),
    .S(\rd_bin[0] ),
    .X(_0413_)
  );
  sky130_fd_sc_hd__mux2_2 _0951_ (
    .A0(_0412_),
    .A1(_0413_),
    .S(_0352_),
    .X(_0414_)
  );
  sky130_fd_sc_hd__o21a_2 _0952_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[10][3] ),
    .B1(\rd_bin[1] ),
    .X(_0415_)
  );
  sky130_fd_sc_hd__or2_2 _0953_ (
    .A(\mem[11][3] ),
    .B(_0355_),
    .X(_0416_)
  );
  sky130_fd_sc_hd__o21a_2 _0954_ (
    .A1(\mem[9][3] ),
    .A2(_0237_),
    .B1(_0352_),
    .X(_0417_)
  );
  sky130_fd_sc_hd__or2_2 _0955_ (
    .A(\rd_bin[0] ),
    .B(\mem[8][3] ),
    .X(_0418_)
  );
  sky130_fd_sc_hd__a221o_2 _0956_ (
    .A1(_0415_),
    .A2(_0416_),
    .B1(_0417_),
    .B2(_0418_),
    .C1(\rd_bin[2] ),
    .X(_0419_)
  );
  sky130_fd_sc_hd__o211a_2 _0957_ (
    .A1(_0349_),
    .A2(_0414_),
    .B1(\rd_bin[3] ),
    .C1(_0419_),
    .X(_0420_)
  );
  sky130_fd_sc_hd__or2_2 _0958_ (
    .A(\mem[7][3] ),
    .B(_0237_),
    .X(_0421_)
  );
  sky130_fd_sc_hd__o21a_2 _0959_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[6][3] ),
    .B1(\rd_bin[1] ),
    .X(_0422_)
  );
  sky130_fd_sc_hd__mux2_2 _0960_ (
    .A0(\mem[4][3] ),
    .A1(\mem[5][3] ),
    .S(\rd_bin[0] ),
    .X(_0423_)
  );
  sky130_fd_sc_hd__a221o_2 _0961_ (
    .A1(_0421_),
    .A2(_0422_),
    .B1(_0423_),
    .B2(_0364_),
    .C1(_0349_),
    .X(_0424_)
  );
  sky130_fd_sc_hd__or2_2 _0962_ (
    .A(\mem[3][3] ),
    .B(_0237_),
    .X(_0425_)
  );
  sky130_fd_sc_hd__o21a_2 _0963_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[2][3] ),
    .B1(\rd_bin[1] ),
    .X(_0426_)
  );
  sky130_fd_sc_hd__mux2_2 _0964_ (
    .A0(\mem[0][3] ),
    .A1(\mem[1][3] ),
    .S(\rd_bin[0] ),
    .X(_0427_)
  );
  sky130_fd_sc_hd__a221o_2 _0965_ (
    .A1(_0425_),
    .A2(_0426_),
    .B1(_0427_),
    .B2(_0364_),
    .C1(\rd_bin[2] ),
    .X(_0428_)
  );
  sky130_fd_sc_hd__nand3_2 _0966_ (
    .A(_0424_),
    .B(_0428_),
    .C(_0331_),
    .Y(_0429_)
  );
  sky130_fd_sc_hd__nand2_2 _0967_ (
    .A(_0429_),
    .B(_0318_),
    .Y(_0430_)
  );
  sky130_fd_sc_hd__o22a_2 _0968_ (
    .A1(rd_data[3]),
    .A2(_0348_),
    .B1(_0420_),
    .B2(_0430_),
    .X(_0003_)
  );
  sky130_fd_sc_hd__or2_2 _0969_ (
    .A(\mem[15][4] ),
    .B(_0379_),
    .X(_0431_)
  );
  sky130_fd_sc_hd__o21a_2 _0970_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[14][4] ),
    .B1(\rd_bin[1] ),
    .X(_0432_)
  );
  sky130_fd_sc_hd__mux2_2 _0971_ (
    .A0(\mem[12][4] ),
    .A1(\mem[13][4] ),
    .S(\rd_bin[0] ),
    .X(_0433_)
  );
  sky130_fd_sc_hd__a221o_2 _0972_ (
    .A1(_0431_),
    .A2(_0432_),
    .B1(_0433_),
    .B2(_0364_),
    .C1(_0349_),
    .X(_0434_)
  );
  sky130_fd_sc_hd__or2_2 _0973_ (
    .A(\mem[11][4] ),
    .B(_0379_),
    .X(_0435_)
  );
  sky130_fd_sc_hd__o21a_2 _0974_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[10][4] ),
    .B1(\rd_bin[1] ),
    .X(_0436_)
  );
  sky130_fd_sc_hd__mux2_2 _0975_ (
    .A0(\mem[8][4] ),
    .A1(\mem[9][4] ),
    .S(\rd_bin[0] ),
    .X(_0437_)
  );
  sky130_fd_sc_hd__a221o_2 _0976_ (
    .A1(_0435_),
    .A2(_0436_),
    .B1(_0437_),
    .B2(_0375_),
    .C1(\rd_bin[2] ),
    .X(_0438_)
  );
  sky130_fd_sc_hd__nand3_2 _0977_ (
    .A(_0434_),
    .B(_0438_),
    .C(\rd_bin[3] ),
    .Y(_0439_)
  );
  sky130_fd_sc_hd__nand2_2 _0978_ (
    .A(_0439_),
    .B(_0318_),
    .Y(_0440_)
  );
  sky130_fd_sc_hd__or2_2 _0979_ (
    .A(\mem[7][4] ),
    .B(_0379_),
    .X(_0441_)
  );
  sky130_fd_sc_hd__o21a_2 _0980_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[6][4] ),
    .B1(\rd_bin[1] ),
    .X(_0442_)
  );
  sky130_fd_sc_hd__mux2_2 _0981_ (
    .A0(\mem[4][4] ),
    .A1(\mem[5][4] ),
    .S(\rd_bin[0] ),
    .X(_0443_)
  );
  sky130_fd_sc_hd__a221o_2 _0982_ (
    .A1(_0441_),
    .A2(_0442_),
    .B1(_0443_),
    .B2(_0375_),
    .C1(_0326_),
    .X(_0444_)
  );
  sky130_fd_sc_hd__or2_2 _0983_ (
    .A(\mem[3][4] ),
    .B(_0355_),
    .X(_0445_)
  );
  sky130_fd_sc_hd__o21a_2 _0984_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[2][4] ),
    .B1(\rd_bin[1] ),
    .X(_0446_)
  );
  sky130_fd_sc_hd__mux2_2 _0985_ (
    .A0(\mem[0][4] ),
    .A1(\mem[1][4] ),
    .S(\rd_bin[0] ),
    .X(_0447_)
  );
  sky130_fd_sc_hd__a221o_2 _0986_ (
    .A1(_0445_),
    .A2(_0446_),
    .B1(_0447_),
    .B2(_0375_),
    .C1(\rd_bin[2] ),
    .X(_0448_)
  );
  sky130_fd_sc_hd__and3_2 _0987_ (
    .A(_0444_),
    .B(_0448_),
    .C(_0331_),
    .X(_0449_)
  );
  sky130_fd_sc_hd__o22a_2 _0988_ (
    .A1(rd_data[4]),
    .A2(_0348_),
    .B1(_0440_),
    .B2(_0449_),
    .X(_0004_)
  );
  sky130_fd_sc_hd__or2_2 _0989_ (
    .A(\mem[7][5] ),
    .B(_0379_),
    .X(_0450_)
  );
  sky130_fd_sc_hd__o21a_2 _0990_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[6][5] ),
    .B1(\rd_bin[1] ),
    .X(_0451_)
  );
  sky130_fd_sc_hd__mux2_2 _0991_ (
    .A0(\mem[4][5] ),
    .A1(\mem[5][5] ),
    .S(\rd_bin[0] ),
    .X(_0452_)
  );
  sky130_fd_sc_hd__a221o_2 _0992_ (
    .A1(_0450_),
    .A2(_0451_),
    .B1(_0452_),
    .B2(_0364_),
    .C1(_0349_),
    .X(_0453_)
  );
  sky130_fd_sc_hd__or2_2 _0993_ (
    .A(\mem[3][5] ),
    .B(_0379_),
    .X(_0454_)
  );
  sky130_fd_sc_hd__o21a_2 _0994_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[2][5] ),
    .B1(\rd_bin[1] ),
    .X(_0455_)
  );
  sky130_fd_sc_hd__mux2_2 _0995_ (
    .A0(\mem[0][5] ),
    .A1(\mem[1][5] ),
    .S(\rd_bin[0] ),
    .X(_0456_)
  );
  sky130_fd_sc_hd__a221o_2 _0996_ (
    .A1(_0454_),
    .A2(_0455_),
    .B1(_0456_),
    .B2(_0375_),
    .C1(\rd_bin[2] ),
    .X(_0457_)
  );
  sky130_fd_sc_hd__nand3_2 _0997_ (
    .A(_0453_),
    .B(_0457_),
    .C(_0331_),
    .Y(_0458_)
  );
  sky130_fd_sc_hd__nand2_2 _0998_ (
    .A(_0458_),
    .B(_0318_),
    .Y(_0459_)
  );
  sky130_fd_sc_hd__or2_2 _0999_ (
    .A(\mem[11][5] ),
    .B(_0355_),
    .X(_0460_)
  );
  sky130_fd_sc_hd__o21a_2 _1000_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[10][5] ),
    .B1(\rd_bin[1] ),
    .X(_0461_)
  );
  sky130_fd_sc_hd__mux2_2 _1001_ (
    .A0(\mem[8][5] ),
    .A1(\mem[9][5] ),
    .S(\rd_bin[0] ),
    .X(_0462_)
  );
  sky130_fd_sc_hd__a221o_2 _1002_ (
    .A1(_0460_),
    .A2(_0461_),
    .B1(_0462_),
    .B2(_0375_),
    .C1(\rd_bin[2] ),
    .X(_0463_)
  );
  sky130_fd_sc_hd__or2_2 _1003_ (
    .A(\mem[15][5] ),
    .B(_0355_),
    .X(_0464_)
  );
  sky130_fd_sc_hd__o21a_2 _1004_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[14][5] ),
    .B1(\rd_bin[1] ),
    .X(_0465_)
  );
  sky130_fd_sc_hd__mux2_2 _1005_ (
    .A0(\mem[12][5] ),
    .A1(\mem[13][5] ),
    .S(\rd_bin[0] ),
    .X(_0466_)
  );
  sky130_fd_sc_hd__a221o_2 _1006_ (
    .A1(_0464_),
    .A2(_0465_),
    .B1(_0466_),
    .B2(_0375_),
    .C1(_0326_),
    .X(_0467_)
  );
  sky130_fd_sc_hd__and3_2 _1007_ (
    .A(_0463_),
    .B(_0467_),
    .C(\rd_bin[3] ),
    .X(_0468_)
  );
  sky130_fd_sc_hd__o22a_2 _1008_ (
    .A1(rd_data[5]),
    .A2(_0348_),
    .B1(_0459_),
    .B2(_0468_),
    .X(_0005_)
  );
  sky130_fd_sc_hd__or2_2 _1009_ (
    .A(\mem[7][6] ),
    .B(_0355_),
    .X(_0469_)
  );
  sky130_fd_sc_hd__o21a_2 _1010_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[6][6] ),
    .B1(\rd_bin[1] ),
    .X(_0470_)
  );
  sky130_fd_sc_hd__mux2_2 _1011_ (
    .A0(\mem[4][6] ),
    .A1(\mem[5][6] ),
    .S(\rd_bin[0] ),
    .X(_0471_)
  );
  sky130_fd_sc_hd__a221o_2 _1012_ (
    .A1(_0469_),
    .A2(_0470_),
    .B1(_0471_),
    .B2(_0352_),
    .C1(_0326_),
    .X(_0472_)
  );
  sky130_fd_sc_hd__o21a_2 _1013_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[2][6] ),
    .B1(\rd_bin[1] ),
    .X(_0473_)
  );
  sky130_fd_sc_hd__or2_2 _1014_ (
    .A(\mem[3][6] ),
    .B(_0236_),
    .X(_0474_)
  );
  sky130_fd_sc_hd__o21a_2 _1015_ (
    .A1(\mem[1][6] ),
    .A2(_0379_),
    .B1(_0244_),
    .X(_0475_)
  );
  sky130_fd_sc_hd__or2_2 _1016_ (
    .A(\rd_bin[0] ),
    .B(\mem[0][6] ),
    .X(_0476_)
  );
  sky130_fd_sc_hd__a221o_2 _1017_ (
    .A1(_0473_),
    .A2(_0474_),
    .B1(_0475_),
    .B2(_0476_),
    .C1(\rd_bin[2] ),
    .X(_0477_)
  );
  sky130_fd_sc_hd__and3_2 _1018_ (
    .A(_0472_),
    .B(_0477_),
    .C(_0331_),
    .X(_0478_)
  );
  sky130_fd_sc_hd__mux2_2 _1019_ (
    .A0(\mem[10][6] ),
    .A1(\mem[11][6] ),
    .S(\rd_bin[0] ),
    .X(_0479_)
  );
  sky130_fd_sc_hd__mux2_2 _1020_ (
    .A0(\mem[8][6] ),
    .A1(\mem[9][6] ),
    .S(\rd_bin[0] ),
    .X(_0480_)
  );
  sky130_fd_sc_hd__mux2_2 _1021_ (
    .A0(_0479_),
    .A1(_0480_),
    .S(_0352_),
    .X(_0481_)
  );
  sky130_fd_sc_hd__or2_2 _1022_ (
    .A(\mem[15][6] ),
    .B(_0237_),
    .X(_0482_)
  );
  sky130_fd_sc_hd__o21a_2 _1023_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[14][6] ),
    .B1(\rd_bin[1] ),
    .X(_0483_)
  );
  sky130_fd_sc_hd__mux2_2 _1024_ (
    .A0(\mem[12][6] ),
    .A1(\mem[13][6] ),
    .S(\rd_bin[0] ),
    .X(_0484_)
  );
  sky130_fd_sc_hd__a221o_2 _1025_ (
    .A1(_0482_),
    .A2(_0483_),
    .B1(_0484_),
    .B2(_0364_),
    .C1(_0349_),
    .X(_0485_)
  );
  sky130_fd_sc_hd__o211ai_2 _1026_ (
    .A1(\rd_bin[2] ),
    .A2(_0481_),
    .B1(\rd_bin[3] ),
    .C1(_0485_),
    .Y(_0486_)
  );
  sky130_fd_sc_hd__nand2_2 _1027_ (
    .A(_0486_),
    .B(_0318_),
    .Y(_0487_)
  );
  sky130_fd_sc_hd__o22a_2 _1028_ (
    .A1(rd_data[6]),
    .A2(_0348_),
    .B1(_0478_),
    .B2(_0487_),
    .X(_0006_)
  );
  sky130_fd_sc_hd__or2_2 _1029_ (
    .A(\mem[7][7] ),
    .B(_0379_),
    .X(_0488_)
  );
  sky130_fd_sc_hd__o21a_2 _1030_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[6][7] ),
    .B1(\rd_bin[1] ),
    .X(_0489_)
  );
  sky130_fd_sc_hd__mux2_2 _1031_ (
    .A0(\mem[4][7] ),
    .A1(\mem[5][7] ),
    .S(\rd_bin[0] ),
    .X(_0490_)
  );
  sky130_fd_sc_hd__a221o_2 _1032_ (
    .A1(_0488_),
    .A2(_0489_),
    .B1(_0490_),
    .B2(_0364_),
    .C1(_0349_),
    .X(_0491_)
  );
  sky130_fd_sc_hd__or2_2 _1033_ (
    .A(\mem[3][7] ),
    .B(_0379_),
    .X(_0492_)
  );
  sky130_fd_sc_hd__o21a_2 _1034_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[2][7] ),
    .B1(\rd_bin[1] ),
    .X(_0493_)
  );
  sky130_fd_sc_hd__mux2_2 _1035_ (
    .A0(\mem[0][7] ),
    .A1(\mem[1][7] ),
    .S(\rd_bin[0] ),
    .X(_0494_)
  );
  sky130_fd_sc_hd__a221o_2 _1036_ (
    .A1(_0492_),
    .A2(_0493_),
    .B1(_0494_),
    .B2(_0375_),
    .C1(\rd_bin[2] ),
    .X(_0495_)
  );
  sky130_fd_sc_hd__nand3_2 _1037_ (
    .A(_0491_),
    .B(_0495_),
    .C(_0331_),
    .Y(_0496_)
  );
  sky130_fd_sc_hd__nand2_2 _1038_ (
    .A(_0496_),
    .B(_0318_),
    .Y(_0497_)
  );
  sky130_fd_sc_hd__or2_2 _1039_ (
    .A(\mem[11][7] ),
    .B(_0355_),
    .X(_0498_)
  );
  sky130_fd_sc_hd__o21a_2 _1040_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[10][7] ),
    .B1(\rd_bin[1] ),
    .X(_0499_)
  );
  sky130_fd_sc_hd__mux2_2 _1041_ (
    .A0(\mem[8][7] ),
    .A1(\mem[9][7] ),
    .S(\rd_bin[0] ),
    .X(_0500_)
  );
  sky130_fd_sc_hd__a221o_2 _1042_ (
    .A1(_0498_),
    .A2(_0499_),
    .B1(_0500_),
    .B2(_0375_),
    .C1(\rd_bin[2] ),
    .X(_0501_)
  );
  sky130_fd_sc_hd__or2_2 _1043_ (
    .A(\mem[15][7] ),
    .B(_0355_),
    .X(_0502_)
  );
  sky130_fd_sc_hd__o21a_2 _1044_ (
    .A1(\rd_bin[0] ),
    .A2(\mem[14][7] ),
    .B1(\rd_bin[1] ),
    .X(_0503_)
  );
  sky130_fd_sc_hd__mux2_2 _1045_ (
    .A0(\mem[12][7] ),
    .A1(\mem[13][7] ),
    .S(\rd_bin[0] ),
    .X(_0504_)
  );
  sky130_fd_sc_hd__a221o_2 _1046_ (
    .A1(_0502_),
    .A2(_0503_),
    .B1(_0504_),
    .B2(_0375_),
    .C1(_0326_),
    .X(_0505_)
  );
  sky130_fd_sc_hd__and3_2 _1047_ (
    .A(_0501_),
    .B(_0505_),
    .C(\rd_bin[3] ),
    .X(_0506_)
  );
  sky130_fd_sc_hd__o22a_2 _1048_ (
    .A1(rd_data[7]),
    .A2(_0348_),
    .B1(_0497_),
    .B2(_0506_),
    .X(_0007_)
  );
  sky130_fd_sc_hd__and3_2 _1049_ (
    .A(_0293_),
    .B(\wr_bin[1] ),
    .C(_0162_),
    .X(_0507_)
  );
  sky130_fd_sc_hd__nand2_2 _1050_ (
    .A(_0507_),
    .B(_0312_),
    .Y(_0508_)
  );
  sky130_fd_sc_hd__mux2_2 _1051_ (
    .A0(wr_data[0]),
    .A1(\mem[14][0] ),
    .S(_0508_),
    .X(_0509_)
  );
  sky130_fd_sc_hd__buf_1 _1052_ (
    .A(_0509_),
    .X(_0008_)
  );
  sky130_fd_sc_hd__mux2_2 _1053_ (
    .A0(wr_data[1]),
    .A1(\mem[14][1] ),
    .S(_0508_),
    .X(_0510_)
  );
  sky130_fd_sc_hd__buf_1 _1054_ (
    .A(_0510_),
    .X(_0009_)
  );
  sky130_fd_sc_hd__mux2_2 _1055_ (
    .A0(wr_data[2]),
    .A1(\mem[14][2] ),
    .S(_0508_),
    .X(_0511_)
  );
  sky130_fd_sc_hd__buf_1 _1056_ (
    .A(_0511_),
    .X(_0010_)
  );
  sky130_fd_sc_hd__mux2_2 _1057_ (
    .A0(wr_data[3]),
    .A1(\mem[14][3] ),
    .S(_0508_),
    .X(_0512_)
  );
  sky130_fd_sc_hd__buf_1 _1058_ (
    .A(_0512_),
    .X(_0011_)
  );
  sky130_fd_sc_hd__mux2_2 _1059_ (
    .A0(wr_data[4]),
    .A1(\mem[14][4] ),
    .S(_0508_),
    .X(_0513_)
  );
  sky130_fd_sc_hd__buf_1 _1060_ (
    .A(_0513_),
    .X(_0012_)
  );
  sky130_fd_sc_hd__mux2_2 _1061_ (
    .A0(wr_data[5]),
    .A1(\mem[14][5] ),
    .S(_0508_),
    .X(_0514_)
  );
  sky130_fd_sc_hd__buf_1 _1062_ (
    .A(_0514_),
    .X(_0013_)
  );
  sky130_fd_sc_hd__mux2_2 _1063_ (
    .A0(wr_data[6]),
    .A1(\mem[14][6] ),
    .S(_0508_),
    .X(_0515_)
  );
  sky130_fd_sc_hd__buf_1 _1064_ (
    .A(_0515_),
    .X(_0014_)
  );
  sky130_fd_sc_hd__mux2_2 _1065_ (
    .A0(wr_data[7]),
    .A1(\mem[14][7] ),
    .S(_0508_),
    .X(_0516_)
  );
  sky130_fd_sc_hd__buf_1 _1066_ (
    .A(_0516_),
    .X(_0015_)
  );
  sky130_fd_sc_hd__or3_2 _1067_ (
    .A(\wr_bin[1] ),
    .B(_0311_),
    .C(_0295_),
    .X(_0517_)
  );
  sky130_fd_sc_hd__buf_1 _1068_ (
    .A(_0517_),
    .X(_0518_)
  );
  sky130_fd_sc_hd__mux2_2 _1069_ (
    .A0(wr_data[0]),
    .A1(\mem[13][0] ),
    .S(_0518_),
    .X(_0519_)
  );
  sky130_fd_sc_hd__buf_1 _1070_ (
    .A(_0519_),
    .X(_0016_)
  );
  sky130_fd_sc_hd__mux2_2 _1071_ (
    .A0(wr_data[1]),
    .A1(\mem[13][1] ),
    .S(_0518_),
    .X(_0520_)
  );
  sky130_fd_sc_hd__buf_1 _1072_ (
    .A(_0520_),
    .X(_0017_)
  );
  sky130_fd_sc_hd__mux2_2 _1073_ (
    .A0(wr_data[2]),
    .A1(\mem[13][2] ),
    .S(_0518_),
    .X(_0521_)
  );
  sky130_fd_sc_hd__buf_1 _1074_ (
    .A(_0521_),
    .X(_0018_)
  );
  sky130_fd_sc_hd__mux2_2 _1075_ (
    .A0(wr_data[3]),
    .A1(\mem[13][3] ),
    .S(_0518_),
    .X(_0522_)
  );
  sky130_fd_sc_hd__buf_1 _1076_ (
    .A(_0522_),
    .X(_0019_)
  );
  sky130_fd_sc_hd__mux2_2 _1077_ (
    .A0(wr_data[4]),
    .A1(\mem[13][4] ),
    .S(_0518_),
    .X(_0523_)
  );
  sky130_fd_sc_hd__buf_1 _1078_ (
    .A(_0523_),
    .X(_0020_)
  );
  sky130_fd_sc_hd__mux2_2 _1079_ (
    .A0(wr_data[5]),
    .A1(\mem[13][5] ),
    .S(_0518_),
    .X(_0524_)
  );
  sky130_fd_sc_hd__buf_1 _1080_ (
    .A(_0524_),
    .X(_0021_)
  );
  sky130_fd_sc_hd__mux2_2 _1081_ (
    .A0(wr_data[6]),
    .A1(\mem[13][6] ),
    .S(_0518_),
    .X(_0525_)
  );
  sky130_fd_sc_hd__buf_1 _1082_ (
    .A(_0525_),
    .X(_0022_)
  );
  sky130_fd_sc_hd__mux2_2 _1083_ (
    .A0(wr_data[7]),
    .A1(\mem[13][7] ),
    .S(_0518_),
    .X(_0526_)
  );
  sky130_fd_sc_hd__buf_1 _1084_ (
    .A(_0526_),
    .X(_0023_)
  );
  sky130_fd_sc_hd__and3_2 _1085_ (
    .A(_0293_),
    .B(_0164_),
    .C(_0162_),
    .X(_0527_)
  );
  sky130_fd_sc_hd__nand2_2 _1086_ (
    .A(_0527_),
    .B(_0312_),
    .Y(_0528_)
  );
  sky130_fd_sc_hd__mux2_2 _1087_ (
    .A0(wr_data[0]),
    .A1(\mem[12][0] ),
    .S(_0528_),
    .X(_0529_)
  );
  sky130_fd_sc_hd__buf_1 _1088_ (
    .A(_0529_),
    .X(_0024_)
  );
  sky130_fd_sc_hd__mux2_2 _1089_ (
    .A0(wr_data[1]),
    .A1(\mem[12][1] ),
    .S(_0528_),
    .X(_0530_)
  );
  sky130_fd_sc_hd__buf_1 _1090_ (
    .A(_0530_),
    .X(_0025_)
  );
  sky130_fd_sc_hd__mux2_2 _1091_ (
    .A0(wr_data[2]),
    .A1(\mem[12][2] ),
    .S(_0528_),
    .X(_0531_)
  );
  sky130_fd_sc_hd__buf_1 _1092_ (
    .A(_0531_),
    .X(_0026_)
  );
  sky130_fd_sc_hd__mux2_2 _1093_ (
    .A0(wr_data[3]),
    .A1(\mem[12][3] ),
    .S(_0528_),
    .X(_0532_)
  );
  sky130_fd_sc_hd__buf_1 _1094_ (
    .A(_0532_),
    .X(_0027_)
  );
  sky130_fd_sc_hd__mux2_2 _1095_ (
    .A0(wr_data[4]),
    .A1(\mem[12][4] ),
    .S(_0528_),
    .X(_0533_)
  );
  sky130_fd_sc_hd__buf_1 _1096_ (
    .A(_0533_),
    .X(_0028_)
  );
  sky130_fd_sc_hd__mux2_2 _1097_ (
    .A0(wr_data[5]),
    .A1(\mem[12][5] ),
    .S(_0528_),
    .X(_0534_)
  );
  sky130_fd_sc_hd__buf_1 _1098_ (
    .A(_0534_),
    .X(_0029_)
  );
  sky130_fd_sc_hd__mux2_2 _1099_ (
    .A0(wr_data[6]),
    .A1(\mem[12][6] ),
    .S(_0528_),
    .X(_0535_)
  );
  sky130_fd_sc_hd__buf_1 _1100_ (
    .A(_0535_),
    .X(_0030_)
  );
  sky130_fd_sc_hd__mux2_2 _1101_ (
    .A0(wr_data[7]),
    .A1(\mem[12][7] ),
    .S(_0528_),
    .X(_0536_)
  );
  sky130_fd_sc_hd__buf_1 _1102_ (
    .A(_0536_),
    .X(_0031_)
  );
  sky130_fd_sc_hd__nor2_2 _1103_ (
    .A(\wr_bin[2] ),
    .B(_0303_),
    .Y(_0537_)
  );
  sky130_fd_sc_hd__nand2_2 _1104_ (
    .A(_0297_),
    .B(_0537_),
    .Y(_0538_)
  );
  sky130_fd_sc_hd__mux2_2 _1105_ (
    .A0(wr_data[0]),
    .A1(\mem[11][0] ),
    .S(_0538_),
    .X(_0539_)
  );
  sky130_fd_sc_hd__buf_1 _1106_ (
    .A(_0539_),
    .X(_0032_)
  );
  sky130_fd_sc_hd__mux2_2 _1107_ (
    .A0(wr_data[1]),
    .A1(\mem[11][1] ),
    .S(_0538_),
    .X(_0540_)
  );
  sky130_fd_sc_hd__buf_1 _1108_ (
    .A(_0540_),
    .X(_0033_)
  );
  sky130_fd_sc_hd__mux2_2 _1109_ (
    .A0(wr_data[2]),
    .A1(\mem[11][2] ),
    .S(_0538_),
    .X(_0541_)
  );
  sky130_fd_sc_hd__buf_1 _1110_ (
    .A(_0541_),
    .X(_0034_)
  );
  sky130_fd_sc_hd__mux2_2 _1111_ (
    .A0(wr_data[3]),
    .A1(\mem[11][3] ),
    .S(_0538_),
    .X(_0542_)
  );
  sky130_fd_sc_hd__buf_1 _1112_ (
    .A(_0542_),
    .X(_0035_)
  );
  sky130_fd_sc_hd__mux2_2 _1113_ (
    .A0(wr_data[4]),
    .A1(\mem[11][4] ),
    .S(_0538_),
    .X(_0543_)
  );
  sky130_fd_sc_hd__buf_1 _1114_ (
    .A(_0543_),
    .X(_0036_)
  );
  sky130_fd_sc_hd__mux2_2 _1115_ (
    .A0(wr_data[5]),
    .A1(\mem[11][5] ),
    .S(_0538_),
    .X(_0544_)
  );
  sky130_fd_sc_hd__buf_1 _1116_ (
    .A(_0544_),
    .X(_0037_)
  );
  sky130_fd_sc_hd__mux2_2 _1117_ (
    .A0(wr_data[6]),
    .A1(\mem[11][6] ),
    .S(_0538_),
    .X(_0545_)
  );
  sky130_fd_sc_hd__buf_1 _1118_ (
    .A(_0545_),
    .X(_0038_)
  );
  sky130_fd_sc_hd__mux2_2 _1119_ (
    .A0(wr_data[7]),
    .A1(\mem[11][7] ),
    .S(_0538_),
    .X(_0546_)
  );
  sky130_fd_sc_hd__buf_1 _1120_ (
    .A(_0546_),
    .X(_0039_)
  );
  sky130_fd_sc_hd__nor2_2 _1121_ (
    .A(\wr_bin[3] ),
    .B(\wr_bin[2] ),
    .Y(_0547_)
  );
  sky130_fd_sc_hd__or3b_2 _1122_ (
    .A(\wr_bin[1] ),
    .B(_0295_),
    .C_N(_0547_),
    .X(_0548_)
  );
  sky130_fd_sc_hd__buf_1 _1123_ (
    .A(_0548_),
    .X(_0549_)
  );
  sky130_fd_sc_hd__mux2_2 _1124_ (
    .A0(wr_data[0]),
    .A1(\mem[1][0] ),
    .S(_0549_),
    .X(_0550_)
  );
  sky130_fd_sc_hd__buf_1 _1125_ (
    .A(_0550_),
    .X(_0040_)
  );
  sky130_fd_sc_hd__mux2_2 _1126_ (
    .A0(wr_data[1]),
    .A1(\mem[1][1] ),
    .S(_0549_),
    .X(_0551_)
  );
  sky130_fd_sc_hd__buf_1 _1127_ (
    .A(_0551_),
    .X(_0041_)
  );
  sky130_fd_sc_hd__mux2_2 _1128_ (
    .A0(wr_data[2]),
    .A1(\mem[1][2] ),
    .S(_0549_),
    .X(_0552_)
  );
  sky130_fd_sc_hd__buf_1 _1129_ (
    .A(_0552_),
    .X(_0042_)
  );
  sky130_fd_sc_hd__mux2_2 _1130_ (
    .A0(wr_data[3]),
    .A1(\mem[1][3] ),
    .S(_0549_),
    .X(_0553_)
  );
  sky130_fd_sc_hd__buf_1 _1131_ (
    .A(_0553_),
    .X(_0043_)
  );
  sky130_fd_sc_hd__mux2_2 _1132_ (
    .A0(wr_data[4]),
    .A1(\mem[1][4] ),
    .S(_0549_),
    .X(_0554_)
  );
  sky130_fd_sc_hd__buf_1 _1133_ (
    .A(_0554_),
    .X(_0044_)
  );
  sky130_fd_sc_hd__mux2_2 _1134_ (
    .A0(wr_data[5]),
    .A1(\mem[1][5] ),
    .S(_0549_),
    .X(_0555_)
  );
  sky130_fd_sc_hd__buf_1 _1135_ (
    .A(_0555_),
    .X(_0045_)
  );
  sky130_fd_sc_hd__mux2_2 _1136_ (
    .A0(wr_data[6]),
    .A1(\mem[1][6] ),
    .S(_0549_),
    .X(_0556_)
  );
  sky130_fd_sc_hd__buf_1 _1137_ (
    .A(_0556_),
    .X(_0046_)
  );
  sky130_fd_sc_hd__mux2_2 _1138_ (
    .A0(wr_data[7]),
    .A1(\mem[1][7] ),
    .S(_0549_),
    .X(_0557_)
  );
  sky130_fd_sc_hd__buf_1 _1139_ (
    .A(_0557_),
    .X(_0047_)
  );
  sky130_fd_sc_hd__nand2_2 _1140_ (
    .A(_0507_),
    .B(_0537_),
    .Y(_0558_)
  );
  sky130_fd_sc_hd__mux2_2 _1141_ (
    .A0(wr_data[0]),
    .A1(\mem[10][0] ),
    .S(_0558_),
    .X(_0559_)
  );
  sky130_fd_sc_hd__buf_1 _1142_ (
    .A(_0559_),
    .X(_0048_)
  );
  sky130_fd_sc_hd__mux2_2 _1143_ (
    .A0(wr_data[1]),
    .A1(\mem[10][1] ),
    .S(_0558_),
    .X(_0560_)
  );
  sky130_fd_sc_hd__buf_1 _1144_ (
    .A(_0560_),
    .X(_0049_)
  );
  sky130_fd_sc_hd__mux2_2 _1145_ (
    .A0(wr_data[2]),
    .A1(\mem[10][2] ),
    .S(_0558_),
    .X(_0561_)
  );
  sky130_fd_sc_hd__buf_1 _1146_ (
    .A(_0561_),
    .X(_0050_)
  );
  sky130_fd_sc_hd__mux2_2 _1147_ (
    .A0(wr_data[3]),
    .A1(\mem[10][3] ),
    .S(_0558_),
    .X(_0562_)
  );
  sky130_fd_sc_hd__buf_1 _1148_ (
    .A(_0562_),
    .X(_0051_)
  );
  sky130_fd_sc_hd__mux2_2 _1149_ (
    .A0(wr_data[4]),
    .A1(\mem[10][4] ),
    .S(_0558_),
    .X(_0563_)
  );
  sky130_fd_sc_hd__buf_1 _1150_ (
    .A(_0563_),
    .X(_0052_)
  );
  sky130_fd_sc_hd__mux2_2 _1151_ (
    .A0(wr_data[5]),
    .A1(\mem[10][5] ),
    .S(_0558_),
    .X(_0564_)
  );
  sky130_fd_sc_hd__buf_1 _1152_ (
    .A(_0564_),
    .X(_0053_)
  );
  sky130_fd_sc_hd__mux2_2 _1153_ (
    .A0(wr_data[6]),
    .A1(\mem[10][6] ),
    .S(_0558_),
    .X(_0565_)
  );
  sky130_fd_sc_hd__buf_1 _1154_ (
    .A(_0565_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__mux2_2 _1155_ (
    .A0(wr_data[7]),
    .A1(\mem[10][7] ),
    .S(_0558_),
    .X(_0566_)
  );
  sky130_fd_sc_hd__buf_1 _1156_ (
    .A(_0566_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__nand2_2 _1157_ (
    .A(_0527_),
    .B(_0547_),
    .Y(_0567_)
  );
  sky130_fd_sc_hd__mux2_2 _1158_ (
    .A0(wr_data[0]),
    .A1(\mem[0][0] ),
    .S(_0567_),
    .X(_0568_)
  );
  sky130_fd_sc_hd__buf_1 _1159_ (
    .A(_0568_),
    .X(_0056_)
  );
  sky130_fd_sc_hd__mux2_2 _1160_ (
    .A0(wr_data[1]),
    .A1(\mem[0][1] ),
    .S(_0567_),
    .X(_0569_)
  );
  sky130_fd_sc_hd__buf_1 _1161_ (
    .A(_0569_),
    .X(_0057_)
  );
  sky130_fd_sc_hd__mux2_2 _1162_ (
    .A0(wr_data[2]),
    .A1(\mem[0][2] ),
    .S(_0567_),
    .X(_0570_)
  );
  sky130_fd_sc_hd__buf_1 _1163_ (
    .A(_0570_),
    .X(_0058_)
  );
  sky130_fd_sc_hd__mux2_2 _1164_ (
    .A0(wr_data[3]),
    .A1(\mem[0][3] ),
    .S(_0567_),
    .X(_0571_)
  );
  sky130_fd_sc_hd__buf_1 _1165_ (
    .A(_0571_),
    .X(_0059_)
  );
  sky130_fd_sc_hd__mux2_2 _1166_ (
    .A0(wr_data[4]),
    .A1(\mem[0][4] ),
    .S(_0567_),
    .X(_0572_)
  );
  sky130_fd_sc_hd__buf_1 _1167_ (
    .A(_0572_),
    .X(_0060_)
  );
  sky130_fd_sc_hd__mux2_2 _1168_ (
    .A0(wr_data[5]),
    .A1(\mem[0][5] ),
    .S(_0567_),
    .X(_0573_)
  );
  sky130_fd_sc_hd__buf_1 _1169_ (
    .A(_0573_),
    .X(_0061_)
  );
  sky130_fd_sc_hd__mux2_2 _1170_ (
    .A0(wr_data[6]),
    .A1(\mem[0][6] ),
    .S(_0567_),
    .X(_0574_)
  );
  sky130_fd_sc_hd__buf_1 _1171_ (
    .A(_0574_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__mux2_2 _1172_ (
    .A0(wr_data[7]),
    .A1(\mem[0][7] ),
    .S(_0567_),
    .X(_0575_)
  );
  sky130_fd_sc_hd__buf_1 _1173_ (
    .A(_0575_),
    .X(_0063_)
  );
  sky130_fd_sc_hd__nand2_2 _1174_ (
    .A(_0527_),
    .B(_0537_),
    .Y(_0576_)
  );
  sky130_fd_sc_hd__mux2_2 _1175_ (
    .A0(wr_data[0]),
    .A1(\mem[8][0] ),
    .S(_0576_),
    .X(_0577_)
  );
  sky130_fd_sc_hd__buf_1 _1176_ (
    .A(_0577_),
    .X(_0064_)
  );
  sky130_fd_sc_hd__mux2_2 _1177_ (
    .A0(wr_data[1]),
    .A1(\mem[8][1] ),
    .S(_0576_),
    .X(_0578_)
  );
  sky130_fd_sc_hd__buf_1 _1178_ (
    .A(_0578_),
    .X(_0065_)
  );
  sky130_fd_sc_hd__mux2_2 _1179_ (
    .A0(wr_data[2]),
    .A1(\mem[8][2] ),
    .S(_0576_),
    .X(_0579_)
  );
  sky130_fd_sc_hd__buf_1 _1180_ (
    .A(_0579_),
    .X(_0066_)
  );
  sky130_fd_sc_hd__mux2_2 _1181_ (
    .A0(wr_data[3]),
    .A1(\mem[8][3] ),
    .S(_0576_),
    .X(_0580_)
  );
  sky130_fd_sc_hd__buf_1 _1182_ (
    .A(_0580_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__mux2_2 _1183_ (
    .A0(wr_data[4]),
    .A1(\mem[8][4] ),
    .S(_0576_),
    .X(_0581_)
  );
  sky130_fd_sc_hd__buf_1 _1184_ (
    .A(_0581_),
    .X(_0068_)
  );
  sky130_fd_sc_hd__mux2_2 _1185_ (
    .A0(wr_data[5]),
    .A1(\mem[8][5] ),
    .S(_0576_),
    .X(_0582_)
  );
  sky130_fd_sc_hd__buf_1 _1186_ (
    .A(_0582_),
    .X(_0069_)
  );
  sky130_fd_sc_hd__mux2_2 _1187_ (
    .A0(wr_data[6]),
    .A1(\mem[8][6] ),
    .S(_0576_),
    .X(_0583_)
  );
  sky130_fd_sc_hd__buf_1 _1188_ (
    .A(_0583_),
    .X(_0070_)
  );
  sky130_fd_sc_hd__mux2_2 _1189_ (
    .A0(wr_data[7]),
    .A1(\mem[8][7] ),
    .S(_0576_),
    .X(_0584_)
  );
  sky130_fd_sc_hd__buf_1 _1190_ (
    .A(_0584_),
    .X(_0071_)
  );
  sky130_fd_sc_hd__or2_2 _1191_ (
    .A(\wr_bin[3] ),
    .B(_0301_),
    .X(_0585_)
  );
  sky130_fd_sc_hd__buf_2 _1192_ (
    .A(_0585_),
    .X(_0586_)
  );
  sky130_fd_sc_hd__mux2_2 _1193_ (
    .A0(wr_data[0]),
    .A1(\mem[7][0] ),
    .S(_0586_),
    .X(_0587_)
  );
  sky130_fd_sc_hd__buf_1 _1194_ (
    .A(_0587_),
    .X(_0072_)
  );
  sky130_fd_sc_hd__mux2_2 _1195_ (
    .A0(wr_data[1]),
    .A1(\mem[7][1] ),
    .S(_0586_),
    .X(_0588_)
  );
  sky130_fd_sc_hd__buf_1 _1196_ (
    .A(_0588_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__mux2_2 _1197_ (
    .A0(wr_data[2]),
    .A1(\mem[7][2] ),
    .S(_0586_),
    .X(_0589_)
  );
  sky130_fd_sc_hd__buf_1 _1198_ (
    .A(_0589_),
    .X(_0074_)
  );
  sky130_fd_sc_hd__mux2_2 _1199_ (
    .A0(wr_data[3]),
    .A1(\mem[7][3] ),
    .S(_0586_),
    .X(_0590_)
  );
  sky130_fd_sc_hd__buf_1 _1200_ (
    .A(_0590_),
    .X(_0075_)
  );
  sky130_fd_sc_hd__mux2_2 _1201_ (
    .A0(wr_data[4]),
    .A1(\mem[7][4] ),
    .S(_0586_),
    .X(_0591_)
  );
  sky130_fd_sc_hd__buf_1 _1202_ (
    .A(_0591_),
    .X(_0076_)
  );
  sky130_fd_sc_hd__mux2_2 _1203_ (
    .A0(wr_data[5]),
    .A1(\mem[7][5] ),
    .S(_0586_),
    .X(_0592_)
  );
  sky130_fd_sc_hd__buf_1 _1204_ (
    .A(_0592_),
    .X(_0077_)
  );
  sky130_fd_sc_hd__mux2_2 _1205_ (
    .A0(wr_data[6]),
    .A1(\mem[7][6] ),
    .S(_0586_),
    .X(_0593_)
  );
  sky130_fd_sc_hd__buf_1 _1206_ (
    .A(_0593_),
    .X(_0078_)
  );
  sky130_fd_sc_hd__mux2_2 _1207_ (
    .A0(wr_data[7]),
    .A1(\mem[7][7] ),
    .S(_0586_),
    .X(_0594_)
  );
  sky130_fd_sc_hd__buf_1 _1208_ (
    .A(_0594_),
    .X(_0079_)
  );
  sky130_fd_sc_hd__and2_2 _1209_ (
    .A(_0303_),
    .B(\wr_bin[2] ),
    .X(_0595_)
  );
  sky130_fd_sc_hd__nand2_2 _1210_ (
    .A(_0507_),
    .B(_0595_),
    .Y(_0596_)
  );
  sky130_fd_sc_hd__mux2_2 _1211_ (
    .A0(wr_data[0]),
    .A1(\mem[6][0] ),
    .S(_0596_),
    .X(_0597_)
  );
  sky130_fd_sc_hd__buf_1 _1212_ (
    .A(_0597_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__mux2_2 _1213_ (
    .A0(wr_data[1]),
    .A1(\mem[6][1] ),
    .S(_0596_),
    .X(_0598_)
  );
  sky130_fd_sc_hd__buf_1 _1214_ (
    .A(_0598_),
    .X(_0081_)
  );
  sky130_fd_sc_hd__mux2_2 _1215_ (
    .A0(wr_data[2]),
    .A1(\mem[6][2] ),
    .S(_0596_),
    .X(_0599_)
  );
  sky130_fd_sc_hd__buf_1 _1216_ (
    .A(_0599_),
    .X(_0082_)
  );
  sky130_fd_sc_hd__mux2_2 _1217_ (
    .A0(wr_data[3]),
    .A1(\mem[6][3] ),
    .S(_0596_),
    .X(_0600_)
  );
  sky130_fd_sc_hd__buf_1 _1218_ (
    .A(_0600_),
    .X(_0083_)
  );
  sky130_fd_sc_hd__mux2_2 _1219_ (
    .A0(wr_data[4]),
    .A1(\mem[6][4] ),
    .S(_0596_),
    .X(_0601_)
  );
  sky130_fd_sc_hd__buf_1 _1220_ (
    .A(_0601_),
    .X(_0084_)
  );
  sky130_fd_sc_hd__mux2_2 _1221_ (
    .A0(wr_data[5]),
    .A1(\mem[6][5] ),
    .S(_0596_),
    .X(_0602_)
  );
  sky130_fd_sc_hd__buf_1 _1222_ (
    .A(_0602_),
    .X(_0085_)
  );
  sky130_fd_sc_hd__mux2_2 _1223_ (
    .A0(wr_data[6]),
    .A1(\mem[6][6] ),
    .S(_0596_),
    .X(_0603_)
  );
  sky130_fd_sc_hd__buf_1 _1224_ (
    .A(_0603_),
    .X(_0086_)
  );
  sky130_fd_sc_hd__mux2_2 _1225_ (
    .A0(wr_data[7]),
    .A1(\mem[6][7] ),
    .S(_0596_),
    .X(_0604_)
  );
  sky130_fd_sc_hd__buf_1 _1226_ (
    .A(_0604_),
    .X(_0087_)
  );
  sky130_fd_sc_hd__nand2_2 _1227_ (
    .A(_0507_),
    .B(_0547_),
    .Y(_0605_)
  );
  sky130_fd_sc_hd__mux2_2 _1228_ (
    .A0(wr_data[0]),
    .A1(\mem[2][0] ),
    .S(_0605_),
    .X(_0606_)
  );
  sky130_fd_sc_hd__buf_1 _1229_ (
    .A(_0606_),
    .X(_0088_)
  );
  sky130_fd_sc_hd__mux2_2 _1230_ (
    .A0(wr_data[1]),
    .A1(\mem[2][1] ),
    .S(_0605_),
    .X(_0607_)
  );
  sky130_fd_sc_hd__buf_1 _1231_ (
    .A(_0607_),
    .X(_0089_)
  );
  sky130_fd_sc_hd__mux2_2 _1232_ (
    .A0(wr_data[2]),
    .A1(\mem[2][2] ),
    .S(_0605_),
    .X(_0608_)
  );
  sky130_fd_sc_hd__buf_1 _1233_ (
    .A(_0608_),
    .X(_0090_)
  );
  sky130_fd_sc_hd__mux2_2 _1234_ (
    .A0(wr_data[3]),
    .A1(\mem[2][3] ),
    .S(_0605_),
    .X(_0609_)
  );
  sky130_fd_sc_hd__buf_1 _1235_ (
    .A(_0609_),
    .X(_0091_)
  );
  sky130_fd_sc_hd__mux2_2 _1236_ (
    .A0(wr_data[4]),
    .A1(\mem[2][4] ),
    .S(_0605_),
    .X(_0610_)
  );
  sky130_fd_sc_hd__buf_1 _1237_ (
    .A(_0610_),
    .X(_0092_)
  );
  sky130_fd_sc_hd__mux2_2 _1238_ (
    .A0(wr_data[5]),
    .A1(\mem[2][5] ),
    .S(_0605_),
    .X(_0611_)
  );
  sky130_fd_sc_hd__buf_1 _1239_ (
    .A(_0611_),
    .X(_0093_)
  );
  sky130_fd_sc_hd__mux2_2 _1240_ (
    .A0(wr_data[6]),
    .A1(\mem[2][6] ),
    .S(_0605_),
    .X(_0612_)
  );
  sky130_fd_sc_hd__buf_1 _1241_ (
    .A(_0612_),
    .X(_0094_)
  );
  sky130_fd_sc_hd__mux2_2 _1242_ (
    .A0(wr_data[7]),
    .A1(\mem[2][7] ),
    .S(_0605_),
    .X(_0613_)
  );
  sky130_fd_sc_hd__buf_1 _1243_ (
    .A(_0613_),
    .X(_0095_)
  );
  sky130_fd_sc_hd__nand2_2 _1244_ (
    .A(_0297_),
    .B(_0547_),
    .Y(_0614_)
  );
  sky130_fd_sc_hd__mux2_2 _1245_ (
    .A0(wr_data[0]),
    .A1(\mem[3][0] ),
    .S(_0614_),
    .X(_0615_)
  );
  sky130_fd_sc_hd__buf_1 _1246_ (
    .A(_0615_),
    .X(_0096_)
  );
  sky130_fd_sc_hd__mux2_2 _1247_ (
    .A0(wr_data[1]),
    .A1(\mem[3][1] ),
    .S(_0614_),
    .X(_0616_)
  );
  sky130_fd_sc_hd__buf_1 _1248_ (
    .A(_0616_),
    .X(_0097_)
  );
  sky130_fd_sc_hd__mux2_2 _1249_ (
    .A0(wr_data[2]),
    .A1(\mem[3][2] ),
    .S(_0614_),
    .X(_0617_)
  );
  sky130_fd_sc_hd__buf_1 _1250_ (
    .A(_0617_),
    .X(_0098_)
  );
  sky130_fd_sc_hd__mux2_2 _1251_ (
    .A0(wr_data[3]),
    .A1(\mem[3][3] ),
    .S(_0614_),
    .X(_0618_)
  );
  sky130_fd_sc_hd__buf_1 _1252_ (
    .A(_0618_),
    .X(_0099_)
  );
  sky130_fd_sc_hd__mux2_2 _1253_ (
    .A0(wr_data[4]),
    .A1(\mem[3][4] ),
    .S(_0614_),
    .X(_0619_)
  );
  sky130_fd_sc_hd__buf_1 _1254_ (
    .A(_0619_),
    .X(_0100_)
  );
  sky130_fd_sc_hd__mux2_2 _1255_ (
    .A0(wr_data[5]),
    .A1(\mem[3][5] ),
    .S(_0614_),
    .X(_0620_)
  );
  sky130_fd_sc_hd__buf_1 _1256_ (
    .A(_0620_),
    .X(_0101_)
  );
  sky130_fd_sc_hd__mux2_2 _1257_ (
    .A0(wr_data[6]),
    .A1(\mem[3][6] ),
    .S(_0614_),
    .X(_0621_)
  );
  sky130_fd_sc_hd__buf_1 _1258_ (
    .A(_0621_),
    .X(_0102_)
  );
  sky130_fd_sc_hd__mux2_2 _1259_ (
    .A0(wr_data[7]),
    .A1(\mem[3][7] ),
    .S(_0614_),
    .X(_0622_)
  );
  sky130_fd_sc_hd__buf_1 _1260_ (
    .A(_0622_),
    .X(_0103_)
  );
  sky130_fd_sc_hd__or3b_2 _1261_ (
    .A(\wr_bin[1] ),
    .B(_0295_),
    .C_N(_0595_),
    .X(_0623_)
  );
  sky130_fd_sc_hd__buf_1 _1262_ (
    .A(_0623_),
    .X(_0624_)
  );
  sky130_fd_sc_hd__mux2_2 _1263_ (
    .A0(wr_data[0]),
    .A1(\mem[5][0] ),
    .S(_0624_),
    .X(_0625_)
  );
  sky130_fd_sc_hd__buf_1 _1264_ (
    .A(_0625_),
    .X(_0104_)
  );
  sky130_fd_sc_hd__mux2_2 _1265_ (
    .A0(wr_data[1]),
    .A1(\mem[5][1] ),
    .S(_0624_),
    .X(_0626_)
  );
  sky130_fd_sc_hd__buf_1 _1266_ (
    .A(_0626_),
    .X(_0105_)
  );
  sky130_fd_sc_hd__mux2_2 _1267_ (
    .A0(wr_data[2]),
    .A1(\mem[5][2] ),
    .S(_0624_),
    .X(_0627_)
  );
  sky130_fd_sc_hd__buf_1 _1268_ (
    .A(_0627_),
    .X(_0106_)
  );
  sky130_fd_sc_hd__mux2_2 _1269_ (
    .A0(wr_data[3]),
    .A1(\mem[5][3] ),
    .S(_0624_),
    .X(_0628_)
  );
  sky130_fd_sc_hd__buf_1 _1270_ (
    .A(_0628_),
    .X(_0107_)
  );
  sky130_fd_sc_hd__mux2_2 _1271_ (
    .A0(wr_data[4]),
    .A1(\mem[5][4] ),
    .S(_0624_),
    .X(_0629_)
  );
  sky130_fd_sc_hd__buf_1 _1272_ (
    .A(_0629_),
    .X(_0108_)
  );
  sky130_fd_sc_hd__mux2_2 _1273_ (
    .A0(wr_data[5]),
    .A1(\mem[5][5] ),
    .S(_0624_),
    .X(_0630_)
  );
  sky130_fd_sc_hd__buf_1 _1274_ (
    .A(_0630_),
    .X(_0109_)
  );
  sky130_fd_sc_hd__mux2_2 _1275_ (
    .A0(wr_data[6]),
    .A1(\mem[5][6] ),
    .S(_0624_),
    .X(_0631_)
  );
  sky130_fd_sc_hd__buf_1 _1276_ (
    .A(_0631_),
    .X(_0110_)
  );
  sky130_fd_sc_hd__mux2_2 _1277_ (
    .A0(wr_data[7]),
    .A1(\mem[5][7] ),
    .S(_0624_),
    .X(_0632_)
  );
  sky130_fd_sc_hd__buf_1 _1278_ (
    .A(_0632_),
    .X(_0111_)
  );
  sky130_fd_sc_hd__nand2_2 _1279_ (
    .A(_0527_),
    .B(_0595_),
    .Y(_0633_)
  );
  sky130_fd_sc_hd__mux2_2 _1280_ (
    .A0(wr_data[0]),
    .A1(\mem[4][0] ),
    .S(_0633_),
    .X(_0634_)
  );
  sky130_fd_sc_hd__buf_1 _1281_ (
    .A(_0634_),
    .X(_0112_)
  );
  sky130_fd_sc_hd__mux2_2 _1282_ (
    .A0(wr_data[1]),
    .A1(\mem[4][1] ),
    .S(_0633_),
    .X(_0635_)
  );
  sky130_fd_sc_hd__buf_1 _1283_ (
    .A(_0635_),
    .X(_0113_)
  );
  sky130_fd_sc_hd__mux2_2 _1284_ (
    .A0(wr_data[2]),
    .A1(\mem[4][2] ),
    .S(_0633_),
    .X(_0636_)
  );
  sky130_fd_sc_hd__buf_1 _1285_ (
    .A(_0636_),
    .X(_0114_)
  );
  sky130_fd_sc_hd__mux2_2 _1286_ (
    .A0(wr_data[3]),
    .A1(\mem[4][3] ),
    .S(_0633_),
    .X(_0637_)
  );
  sky130_fd_sc_hd__buf_1 _1287_ (
    .A(_0637_),
    .X(_0115_)
  );
  sky130_fd_sc_hd__mux2_2 _1288_ (
    .A0(wr_data[4]),
    .A1(\mem[4][4] ),
    .S(_0633_),
    .X(_0638_)
  );
  sky130_fd_sc_hd__buf_1 _1289_ (
    .A(_0638_),
    .X(_0116_)
  );
  sky130_fd_sc_hd__mux2_2 _1290_ (
    .A0(wr_data[5]),
    .A1(\mem[4][5] ),
    .S(_0633_),
    .X(_0639_)
  );
  sky130_fd_sc_hd__buf_1 _1291_ (
    .A(_0639_),
    .X(_0117_)
  );
  sky130_fd_sc_hd__mux2_2 _1292_ (
    .A0(wr_data[6]),
    .A1(\mem[4][6] ),
    .S(_0633_),
    .X(_0640_)
  );
  sky130_fd_sc_hd__buf_1 _1293_ (
    .A(_0640_),
    .X(_0118_)
  );
  sky130_fd_sc_hd__mux2_2 _1294_ (
    .A0(wr_data[7]),
    .A1(\mem[4][7] ),
    .S(_0633_),
    .X(_0641_)
  );
  sky130_fd_sc_hd__buf_1 _1295_ (
    .A(_0641_),
    .X(_0119_)
  );
  sky130_fd_sc_hd__mux2_2 _1296_ (
    .A0(wr_data[0]),
    .A1(\mem[15][0] ),
    .S(_0345_),
    .X(_0642_)
  );
  sky130_fd_sc_hd__buf_1 _1297_ (
    .A(_0642_),
    .X(_0120_)
  );
  sky130_fd_sc_hd__mux2_2 _1298_ (
    .A0(wr_data[1]),
    .A1(\mem[15][1] ),
    .S(_0345_),
    .X(_0643_)
  );
  sky130_fd_sc_hd__buf_1 _1299_ (
    .A(_0643_),
    .X(_0121_)
  );
  sky130_fd_sc_hd__mux2_2 _1300_ (
    .A0(wr_data[2]),
    .A1(\mem[15][2] ),
    .S(_0345_),
    .X(_0644_)
  );
  sky130_fd_sc_hd__buf_1 _1301_ (
    .A(_0644_),
    .X(_0122_)
  );
  sky130_fd_sc_hd__mux2_2 _1302_ (
    .A0(wr_data[3]),
    .A1(\mem[15][3] ),
    .S(_0345_),
    .X(_0645_)
  );
  sky130_fd_sc_hd__buf_1 _1303_ (
    .A(_0645_),
    .X(_0123_)
  );
  sky130_fd_sc_hd__mux2_2 _1304_ (
    .A0(wr_data[4]),
    .A1(\mem[15][4] ),
    .S(_0345_),
    .X(_0646_)
  );
  sky130_fd_sc_hd__buf_1 _1305_ (
    .A(_0646_),
    .X(_0124_)
  );
  sky130_fd_sc_hd__mux2_2 _1306_ (
    .A0(wr_data[5]),
    .A1(\mem[15][5] ),
    .S(_0345_),
    .X(_0647_)
  );
  sky130_fd_sc_hd__buf_1 _1307_ (
    .A(_0647_),
    .X(_0125_)
  );
  sky130_fd_sc_hd__mux2_2 _1308_ (
    .A0(wr_data[6]),
    .A1(\mem[15][6] ),
    .S(_0345_),
    .X(_0648_)
  );
  sky130_fd_sc_hd__buf_1 _1309_ (
    .A(_0648_),
    .X(_0126_)
  );
  sky130_fd_sc_hd__mux2_2 _1310_ (
    .A0(wr_data[7]),
    .A1(\mem[15][7] ),
    .S(_0345_),
    .X(_0649_)
  );
  sky130_fd_sc_hd__buf_1 _1311_ (
    .A(_0649_),
    .X(_0127_)
  );
  sky130_fd_sc_hd__or3b_2 _1312_ (
    .A(\wr_bin[1] ),
    .B(_0295_),
    .C_N(_0537_),
    .X(_0650_)
  );
  sky130_fd_sc_hd__buf_1 _1313_ (
    .A(_0650_),
    .X(_0651_)
  );
  sky130_fd_sc_hd__mux2_2 _1314_ (
    .A0(wr_data[0]),
    .A1(\mem[9][0] ),
    .S(_0651_),
    .X(_0652_)
  );
  sky130_fd_sc_hd__buf_1 _1315_ (
    .A(_0652_),
    .X(_0128_)
  );
  sky130_fd_sc_hd__mux2_2 _1316_ (
    .A0(wr_data[1]),
    .A1(\mem[9][1] ),
    .S(_0651_),
    .X(_0653_)
  );
  sky130_fd_sc_hd__buf_1 _1317_ (
    .A(_0653_),
    .X(_0129_)
  );
  sky130_fd_sc_hd__mux2_2 _1318_ (
    .A0(wr_data[2]),
    .A1(\mem[9][2] ),
    .S(_0651_),
    .X(_0136_)
  );
  sky130_fd_sc_hd__buf_1 _1319_ (
    .A(_0136_),
    .X(_0130_)
  );
  sky130_fd_sc_hd__mux2_2 _1320_ (
    .A0(wr_data[3]),
    .A1(\mem[9][3] ),
    .S(_0651_),
    .X(_0137_)
  );
  sky130_fd_sc_hd__buf_1 _1321_ (
    .A(_0137_),
    .X(_0131_)
  );
  sky130_fd_sc_hd__mux2_2 _1322_ (
    .A0(wr_data[4]),
    .A1(\mem[9][4] ),
    .S(_0651_),
    .X(_0138_)
  );
  sky130_fd_sc_hd__buf_1 _1323_ (
    .A(_0138_),
    .X(_0132_)
  );
  sky130_fd_sc_hd__mux2_2 _1324_ (
    .A0(wr_data[5]),
    .A1(\mem[9][5] ),
    .S(_0651_),
    .X(_0139_)
  );
  sky130_fd_sc_hd__buf_1 _1325_ (
    .A(_0139_),
    .X(_0133_)
  );
  sky130_fd_sc_hd__mux2_2 _1326_ (
    .A0(wr_data[6]),
    .A1(\mem[9][6] ),
    .S(_0651_),
    .X(_0140_)
  );
  sky130_fd_sc_hd__buf_1 _1327_ (
    .A(_0140_),
    .X(_0134_)
  );
  sky130_fd_sc_hd__mux2_2 _1328_ (
    .A0(wr_data[7]),
    .A1(\mem[9][7] ),
    .S(_0651_),
    .X(_0141_)
  );
  sky130_fd_sc_hd__buf_1 _1329_ (
    .A(_0141_),
    .X(_0135_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1330_ (
    .CLK(rd_clk),
    .D(_0000_),
    .Q(rd_data[0]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1331_ (
    .CLK(rd_clk),
    .D(_0001_),
    .Q(rd_data[1]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1332_ (
    .CLK(rd_clk),
    .D(_0002_),
    .Q(rd_data[2]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1333_ (
    .CLK(rd_clk),
    .D(_0003_),
    .Q(rd_data[3]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1334_ (
    .CLK(rd_clk),
    .D(_0004_),
    .Q(rd_data[4]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1335_ (
    .CLK(rd_clk),
    .D(_0005_),
    .Q(rd_data[5]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1336_ (
    .CLK(rd_clk),
    .D(_0006_),
    .Q(rd_data[6]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1337_ (
    .CLK(rd_clk),
    .D(_0007_),
    .Q(rd_data[7]),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfxtp_2 _1338_ (
    .CLK(wr_clk),
    .D(_0008_),
    .Q(\mem[14][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1339_ (
    .CLK(wr_clk),
    .D(_0009_),
    .Q(\mem[14][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1340_ (
    .CLK(wr_clk),
    .D(_0010_),
    .Q(\mem[14][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1341_ (
    .CLK(wr_clk),
    .D(_0011_),
    .Q(\mem[14][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1342_ (
    .CLK(wr_clk),
    .D(_0012_),
    .Q(\mem[14][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1343_ (
    .CLK(wr_clk),
    .D(_0013_),
    .Q(\mem[14][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1344_ (
    .CLK(wr_clk),
    .D(_0014_),
    .Q(\mem[14][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1345_ (
    .CLK(wr_clk),
    .D(_0015_),
    .Q(\mem[14][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1346_ (
    .CLK(wr_clk),
    .D(_0016_),
    .Q(\mem[13][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1347_ (
    .CLK(wr_clk),
    .D(_0017_),
    .Q(\mem[13][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1348_ (
    .CLK(wr_clk),
    .D(_0018_),
    .Q(\mem[13][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1349_ (
    .CLK(wr_clk),
    .D(_0019_),
    .Q(\mem[13][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1350_ (
    .CLK(wr_clk),
    .D(_0020_),
    .Q(\mem[13][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1351_ (
    .CLK(wr_clk),
    .D(_0021_),
    .Q(\mem[13][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1352_ (
    .CLK(wr_clk),
    .D(_0022_),
    .Q(\mem[13][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1353_ (
    .CLK(wr_clk),
    .D(_0023_),
    .Q(\mem[13][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1354_ (
    .CLK(wr_clk),
    .D(_0024_),
    .Q(\mem[12][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1355_ (
    .CLK(wr_clk),
    .D(_0025_),
    .Q(\mem[12][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1356_ (
    .CLK(wr_clk),
    .D(_0026_),
    .Q(\mem[12][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1357_ (
    .CLK(wr_clk),
    .D(_0027_),
    .Q(\mem[12][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1358_ (
    .CLK(wr_clk),
    .D(_0028_),
    .Q(\mem[12][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1359_ (
    .CLK(wr_clk),
    .D(_0029_),
    .Q(\mem[12][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1360_ (
    .CLK(wr_clk),
    .D(_0030_),
    .Q(\mem[12][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1361_ (
    .CLK(wr_clk),
    .D(_0031_),
    .Q(\mem[12][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1362_ (
    .CLK(wr_clk),
    .D(_0032_),
    .Q(\mem[11][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1363_ (
    .CLK(wr_clk),
    .D(_0033_),
    .Q(\mem[11][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1364_ (
    .CLK(wr_clk),
    .D(_0034_),
    .Q(\mem[11][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1365_ (
    .CLK(wr_clk),
    .D(_0035_),
    .Q(\mem[11][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1366_ (
    .CLK(wr_clk),
    .D(_0036_),
    .Q(\mem[11][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1367_ (
    .CLK(wr_clk),
    .D(_0037_),
    .Q(\mem[11][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1368_ (
    .CLK(wr_clk),
    .D(_0038_),
    .Q(\mem[11][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1369_ (
    .CLK(wr_clk),
    .D(_0039_),
    .Q(\mem[11][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1370_ (
    .CLK(wr_clk),
    .D(_0040_),
    .Q(\mem[1][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1371_ (
    .CLK(wr_clk),
    .D(_0041_),
    .Q(\mem[1][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1372_ (
    .CLK(wr_clk),
    .D(_0042_),
    .Q(\mem[1][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1373_ (
    .CLK(wr_clk),
    .D(_0043_),
    .Q(\mem[1][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1374_ (
    .CLK(wr_clk),
    .D(_0044_),
    .Q(\mem[1][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1375_ (
    .CLK(wr_clk),
    .D(_0045_),
    .Q(\mem[1][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1376_ (
    .CLK(wr_clk),
    .D(_0046_),
    .Q(\mem[1][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1377_ (
    .CLK(wr_clk),
    .D(_0047_),
    .Q(\mem[1][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1378_ (
    .CLK(wr_clk),
    .D(_0048_),
    .Q(\mem[10][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1379_ (
    .CLK(wr_clk),
    .D(_0049_),
    .Q(\mem[10][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1380_ (
    .CLK(wr_clk),
    .D(_0050_),
    .Q(\mem[10][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1381_ (
    .CLK(wr_clk),
    .D(_0051_),
    .Q(\mem[10][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1382_ (
    .CLK(wr_clk),
    .D(_0052_),
    .Q(\mem[10][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1383_ (
    .CLK(wr_clk),
    .D(_0053_),
    .Q(\mem[10][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1384_ (
    .CLK(wr_clk),
    .D(_0054_),
    .Q(\mem[10][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1385_ (
    .CLK(wr_clk),
    .D(_0055_),
    .Q(\mem[10][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1386_ (
    .CLK(wr_clk),
    .D(_0056_),
    .Q(\mem[0][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1387_ (
    .CLK(wr_clk),
    .D(_0057_),
    .Q(\mem[0][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1388_ (
    .CLK(wr_clk),
    .D(_0058_),
    .Q(\mem[0][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1389_ (
    .CLK(wr_clk),
    .D(_0059_),
    .Q(\mem[0][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1390_ (
    .CLK(wr_clk),
    .D(_0060_),
    .Q(\mem[0][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1391_ (
    .CLK(wr_clk),
    .D(_0061_),
    .Q(\mem[0][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1392_ (
    .CLK(wr_clk),
    .D(_0062_),
    .Q(\mem[0][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1393_ (
    .CLK(wr_clk),
    .D(_0063_),
    .Q(\mem[0][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1394_ (
    .CLK(wr_clk),
    .D(_0064_),
    .Q(\mem[8][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1395_ (
    .CLK(wr_clk),
    .D(_0065_),
    .Q(\mem[8][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1396_ (
    .CLK(wr_clk),
    .D(_0066_),
    .Q(\mem[8][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1397_ (
    .CLK(wr_clk),
    .D(_0067_),
    .Q(\mem[8][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1398_ (
    .CLK(wr_clk),
    .D(_0068_),
    .Q(\mem[8][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1399_ (
    .CLK(wr_clk),
    .D(_0069_),
    .Q(\mem[8][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1400_ (
    .CLK(wr_clk),
    .D(_0070_),
    .Q(\mem[8][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1401_ (
    .CLK(wr_clk),
    .D(_0071_),
    .Q(\mem[8][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1402_ (
    .CLK(wr_clk),
    .D(_0072_),
    .Q(\mem[7][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1403_ (
    .CLK(wr_clk),
    .D(_0073_),
    .Q(\mem[7][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1404_ (
    .CLK(wr_clk),
    .D(_0074_),
    .Q(\mem[7][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1405_ (
    .CLK(wr_clk),
    .D(_0075_),
    .Q(\mem[7][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1406_ (
    .CLK(wr_clk),
    .D(_0076_),
    .Q(\mem[7][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1407_ (
    .CLK(wr_clk),
    .D(_0077_),
    .Q(\mem[7][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1408_ (
    .CLK(wr_clk),
    .D(_0078_),
    .Q(\mem[7][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1409_ (
    .CLK(wr_clk),
    .D(_0079_),
    .Q(\mem[7][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1410_ (
    .CLK(wr_clk),
    .D(_0080_),
    .Q(\mem[6][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1411_ (
    .CLK(wr_clk),
    .D(_0081_),
    .Q(\mem[6][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1412_ (
    .CLK(wr_clk),
    .D(_0082_),
    .Q(\mem[6][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1413_ (
    .CLK(wr_clk),
    .D(_0083_),
    .Q(\mem[6][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1414_ (
    .CLK(wr_clk),
    .D(_0084_),
    .Q(\mem[6][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1415_ (
    .CLK(wr_clk),
    .D(_0085_),
    .Q(\mem[6][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1416_ (
    .CLK(wr_clk),
    .D(_0086_),
    .Q(\mem[6][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1417_ (
    .CLK(wr_clk),
    .D(_0087_),
    .Q(\mem[6][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1418_ (
    .CLK(wr_clk),
    .D(_0088_),
    .Q(\mem[2][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1419_ (
    .CLK(wr_clk),
    .D(_0089_),
    .Q(\mem[2][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1420_ (
    .CLK(wr_clk),
    .D(_0090_),
    .Q(\mem[2][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1421_ (
    .CLK(wr_clk),
    .D(_0091_),
    .Q(\mem[2][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1422_ (
    .CLK(wr_clk),
    .D(_0092_),
    .Q(\mem[2][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1423_ (
    .CLK(wr_clk),
    .D(_0093_),
    .Q(\mem[2][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1424_ (
    .CLK(wr_clk),
    .D(_0094_),
    .Q(\mem[2][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1425_ (
    .CLK(wr_clk),
    .D(_0095_),
    .Q(\mem[2][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1426_ (
    .CLK(wr_clk),
    .D(_0096_),
    .Q(\mem[3][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1427_ (
    .CLK(wr_clk),
    .D(_0097_),
    .Q(\mem[3][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1428_ (
    .CLK(wr_clk),
    .D(_0098_),
    .Q(\mem[3][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1429_ (
    .CLK(wr_clk),
    .D(_0099_),
    .Q(\mem[3][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1430_ (
    .CLK(wr_clk),
    .D(_0100_),
    .Q(\mem[3][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1431_ (
    .CLK(wr_clk),
    .D(_0101_),
    .Q(\mem[3][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1432_ (
    .CLK(wr_clk),
    .D(_0102_),
    .Q(\mem[3][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1433_ (
    .CLK(wr_clk),
    .D(_0103_),
    .Q(\mem[3][7] )
  );
  sky130_fd_sc_hd__dfstp_2 _1434_ (
    .CLK(rd_clk),
    .D(empty_next),
    .Q(empty),
    .SET_B(arst_n)
  );
  sky130_fd_sc_hd__dfxtp_2 _1435_ (
    .CLK(wr_clk),
    .D(_0104_),
    .Q(\mem[5][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1436_ (
    .CLK(wr_clk),
    .D(_0105_),
    .Q(\mem[5][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1437_ (
    .CLK(wr_clk),
    .D(_0106_),
    .Q(\mem[5][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1438_ (
    .CLK(wr_clk),
    .D(_0107_),
    .Q(\mem[5][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1439_ (
    .CLK(wr_clk),
    .D(_0108_),
    .Q(\mem[5][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1440_ (
    .CLK(wr_clk),
    .D(_0109_),
    .Q(\mem[5][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1441_ (
    .CLK(wr_clk),
    .D(_0110_),
    .Q(\mem[5][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1442_ (
    .CLK(wr_clk),
    .D(_0111_),
    .Q(\mem[5][7] )
  );
  sky130_fd_sc_hd__dfstp_2 _1443_ (
    .CLK(rd_clk),
    .D(aempty_next),
    .Q(aempty),
    .SET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1444_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[0] ),
    .Q(\rd_bin[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1445_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[1] ),
    .Q(\rd_bin[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1446_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[2] ),
    .Q(\rd_bin[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1447_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[3] ),
    .Q(\rd_bin[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1448_ (
    .CLK(rd_clk),
    .D(\rd_bin_next[4] ),
    .Q(\rd_bin[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1449_ (
    .CLK(rd_clk),
    .D(\rd_gray_next[0] ),
    .Q(\rd_gray[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1450_ (
    .CLK(rd_clk),
    .D(\rd_gray_next[1] ),
    .Q(\rd_gray[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1451_ (
    .CLK(rd_clk),
    .D(\rd_gray_next[2] ),
    .Q(\rd_gray[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1452_ (
    .CLK(rd_clk),
    .D(\rd_gray_next[3] ),
    .Q(\rd_gray[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1453_ (
    .CLK(wr_clk),
    .D(full_next),
    .Q(full),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1454_ (
    .CLK(wr_clk),
    .D(afull_next),
    .Q(afull),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1455_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[0] ),
    .Q(\wr_bin[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1456_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[1] ),
    .Q(\wr_bin[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1457_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[2] ),
    .Q(\wr_bin[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1458_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[3] ),
    .Q(\wr_bin[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1459_ (
    .CLK(wr_clk),
    .D(\wr_bin_next[4] ),
    .Q(\wr_bin[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfxtp_2 _1460_ (
    .CLK(wr_clk),
    .D(_0112_),
    .Q(\mem[4][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1461_ (
    .CLK(wr_clk),
    .D(_0113_),
    .Q(\mem[4][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1462_ (
    .CLK(wr_clk),
    .D(_0114_),
    .Q(\mem[4][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1463_ (
    .CLK(wr_clk),
    .D(_0115_),
    .Q(\mem[4][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1464_ (
    .CLK(wr_clk),
    .D(_0116_),
    .Q(\mem[4][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1465_ (
    .CLK(wr_clk),
    .D(_0117_),
    .Q(\mem[4][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1466_ (
    .CLK(wr_clk),
    .D(_0118_),
    .Q(\mem[4][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1467_ (
    .CLK(wr_clk),
    .D(_0119_),
    .Q(\mem[4][7] )
  );
  sky130_fd_sc_hd__dfrtp_2 _1468_ (
    .CLK(wr_clk),
    .D(\wr_gray_next[0] ),
    .Q(\wr_gray[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1469_ (
    .CLK(wr_clk),
    .D(\wr_gray_next[1] ),
    .Q(\wr_gray[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1470_ (
    .CLK(wr_clk),
    .D(\wr_gray_next[2] ),
    .Q(\wr_gray[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1471_ (
    .CLK(wr_clk),
    .D(\wr_gray_next[3] ),
    .Q(\wr_gray[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1472_ (
    .CLK(rd_clk),
    .D(\wr_gray[0] ),
    .Q(\wr_gray_sync1[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1473_ (
    .CLK(rd_clk),
    .D(\wr_gray[1] ),
    .Q(\wr_gray_sync1[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1474_ (
    .CLK(rd_clk),
    .D(\wr_gray[2] ),
    .Q(\wr_gray_sync1[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1475_ (
    .CLK(rd_clk),
    .D(\wr_gray[3] ),
    .Q(\wr_gray_sync1[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1476_ (
    .CLK(rd_clk),
    .D(\wr_bin[4] ),
    .Q(\wr_gray_sync1[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1477_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[0] ),
    .Q(\wr_gray_sync2[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1478_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[1] ),
    .Q(\wr_gray_sync2[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1479_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[2] ),
    .Q(\wr_gray_sync2[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1480_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[3] ),
    .Q(\wr_gray_sync2[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1481_ (
    .CLK(rd_clk),
    .D(\wr_gray_sync1[4] ),
    .Q(\wr_bin_sync[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1482_ (
    .CLK(wr_clk),
    .D(\rd_gray[0] ),
    .Q(\rd_gray_sync1[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1483_ (
    .CLK(wr_clk),
    .D(\rd_gray[1] ),
    .Q(\rd_gray_sync1[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1484_ (
    .CLK(wr_clk),
    .D(\rd_gray[2] ),
    .Q(\rd_gray_sync1[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1485_ (
    .CLK(wr_clk),
    .D(\rd_gray[3] ),
    .Q(\rd_gray_sync1[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1486_ (
    .CLK(wr_clk),
    .D(\rd_bin[4] ),
    .Q(\rd_gray_sync1[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1487_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[0] ),
    .Q(\full_compare[0] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1488_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[1] ),
    .Q(\full_compare[1] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1489_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[2] ),
    .Q(\full_compare[2] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1490_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[3] ),
    .Q(\rd_gray_sync2[3] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1491_ (
    .CLK(wr_clk),
    .D(\rd_gray_sync1[4] ),
    .Q(\rd_bin_sync[4] ),
    .RESET_B(arst_n)
  );
  sky130_fd_sc_hd__dfxtp_2 _1492_ (
    .CLK(wr_clk),
    .D(_0120_),
    .Q(\mem[15][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1493_ (
    .CLK(wr_clk),
    .D(_0121_),
    .Q(\mem[15][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1494_ (
    .CLK(wr_clk),
    .D(_0122_),
    .Q(\mem[15][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1495_ (
    .CLK(wr_clk),
    .D(_0123_),
    .Q(\mem[15][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1496_ (
    .CLK(wr_clk),
    .D(_0124_),
    .Q(\mem[15][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1497_ (
    .CLK(wr_clk),
    .D(_0125_),
    .Q(\mem[15][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1498_ (
    .CLK(wr_clk),
    .D(_0126_),
    .Q(\mem[15][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1499_ (
    .CLK(wr_clk),
    .D(_0127_),
    .Q(\mem[15][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1500_ (
    .CLK(wr_clk),
    .D(_0128_),
    .Q(\mem[9][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1501_ (
    .CLK(wr_clk),
    .D(_0129_),
    .Q(\mem[9][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1502_ (
    .CLK(wr_clk),
    .D(_0130_),
    .Q(\mem[9][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1503_ (
    .CLK(wr_clk),
    .D(_0131_),
    .Q(\mem[9][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1504_ (
    .CLK(wr_clk),
    .D(_0132_),
    .Q(\mem[9][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1505_ (
    .CLK(wr_clk),
    .D(_0133_),
    .Q(\mem[9][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1506_ (
    .CLK(wr_clk),
    .D(_0134_),
    .Q(\mem[9][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _1507_ (
    .CLK(wr_clk),
    .D(_0135_),
    .Q(\mem[9][7] )
  );
endmodule
